// K9 Operations — Training Module: default Hour-Analysis labor-model data.
// Built verbatim from TrainingPage.jsx (no behavior change).

import { LABOR_MODEL_WEEKDAY_COLUMNS, LABOR_MODEL_WEEKDAY_EMPTY, LABOR_MODEL_WEEKDAY_PATTERNS, LABOR_MODEL_WEEKEND_COLUMNS, LABOR_MODEL_WEEKEND_EMPTY, LABOR_MODEL_WEEKEND_PATTERNS } from "./constants";
import { makeDefaultLaborModelDay } from "./helpers";

export const DEFAULT_HOUR_ANALYSIS_LABOR_MODEL = {
  version: 1,
  source: "CH Labor Model Revisited - Clean Daily Pages FIXED.xlsx",
  days: {
    monday: makeDefaultLaborModelDay("monday", "5:30 AM - 7:30 PM", LABOR_MODEL_WEEKDAY_COLUMNS, [
      ["csr", "CSR 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.csrAm],
      ["csr", "CSR 2 AM", LABOR_MODEL_WEEKDAY_PATTERNS.csrAmExtended],
      ["csr", "CSR 3 Mid", LABOR_MODEL_WEEKDAY_PATTERNS.csrMondayMid],
      ["csr", "CSR 1 PM", LABOR_MODEL_WEEKDAY_PATTERNS.csrPm],
      ["csr", "CSR 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.csrPm],
      ["csr", "CSR 3", LABOR_MODEL_WEEKDAY_EMPTY],
      ["pct", "PCT 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAmExtended],
      ["pct", "PCT 2 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAm],
      ["pct", "PCT 3 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAm],
      ["pct", "PCT 4 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAm],
      ["pct", "PCT 5 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAm],
      ["pct", "PCT 1 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 3 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 4 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["supervisor", "SUP 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.supAm],
      ["supervisor", "SUP 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.supMondayPm],
      ["assistant_manager", "MOD 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.modAm],
      ["assistant_manager", "MOD 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.modMondayPm],
    ]),
    tuesday: makeDefaultLaborModelDay("tuesday", "5:30 AM - 7:30 PM", LABOR_MODEL_WEEKDAY_COLUMNS, [
      ["csr", "CSR 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.csrAm],
      ["csr", "CSR 2 AM", LABOR_MODEL_WEEKDAY_PATTERNS.csrAmExtended],
      ["csr", "CSR 3 Mid", LABOR_MODEL_WEEKDAY_PATTERNS.csrWeekdayMid],
      ["csr", "CSR 1 PM", LABOR_MODEL_WEEKDAY_PATTERNS.csrPm],
      ["csr", "CSR 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.csrPm],
      ["csr", "CSR 3", LABOR_MODEL_WEEKDAY_PATTERNS.csrWeekdayPmFlex],
      ["pct", "PCT 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAmExtended],
      ["pct", "PCT 2 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAm],
      ["pct", "PCT 3 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAm],
      ["pct", "PCT 4 AM", LABOR_MODEL_WEEKDAY_EMPTY],
      ["pct", "PCT 5 AM", LABOR_MODEL_WEEKDAY_EMPTY],
      ["pct", "PCT 1 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 3 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 4 PM", LABOR_MODEL_WEEKDAY_EMPTY],
      ["supervisor", "SUP 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.supAm],
      ["supervisor", "SUP 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.supWeekdayPm],
      ["assistant_manager", "MOD 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.modAm],
      ["assistant_manager", "MOD 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.modWeekdayPm],
    ]),
    wednesday: makeDefaultLaborModelDay("wednesday", "5:30 AM - 7:30 PM", LABOR_MODEL_WEEKDAY_COLUMNS, [
      ["csr", "CSR 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.csrAm],
      ["csr", "CSR 2 AM", LABOR_MODEL_WEEKDAY_PATTERNS.csrAmExtended],
      ["csr", "CSR 3 Mid", LABOR_MODEL_WEEKDAY_PATTERNS.csrWeekdayMid],
      ["csr", "CSR 1 PM", LABOR_MODEL_WEEKDAY_PATTERNS.csrPm],
      ["csr", "CSR 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.csrPm],
      ["csr", "CSR 3", LABOR_MODEL_WEEKDAY_PATTERNS.csrWeekdayPmFlex],
      ["pct", "PCT 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAmExtended],
      ["pct", "PCT 2 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAm],
      ["pct", "PCT 3 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAm],
      ["pct", "PCT 4 AM", LABOR_MODEL_WEEKDAY_EMPTY],
      ["pct", "PCT 5 AM", LABOR_MODEL_WEEKDAY_EMPTY],
      ["pct", "PCT 1 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 3 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 4 PM", LABOR_MODEL_WEEKDAY_EMPTY],
      ["supervisor", "SUP 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.supAm],
      ["supervisor", "SUP 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.supWeekdayPm],
      ["assistant_manager", "MOD 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.modAm],
      ["assistant_manager", "MOD 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.modWeekdayPm],
    ]),
    thursday: makeDefaultLaborModelDay("thursday", "5:30 AM - 7:30 PM", LABOR_MODEL_WEEKDAY_COLUMNS, [
      ["csr", "CSR 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.csrAm],
      ["csr", "CSR 2 AM", LABOR_MODEL_WEEKDAY_PATTERNS.csrAmExtended],
      ["csr", "CSR 3 Mid", LABOR_MODEL_WEEKDAY_PATTERNS.csrWeekdayMid],
      ["csr", "CSR 1 PM", LABOR_MODEL_WEEKDAY_PATTERNS.csrPm],
      ["csr", "CSR 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.csrPm],
      ["csr", "CSR 3", LABOR_MODEL_WEEKDAY_PATTERNS.csrWeekdayPmFlex],
      ["pct", "PCT 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAmExtended],
      ["pct", "PCT 2 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAm],
      ["pct", "PCT 3 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAm],
      ["pct", "PCT 4 AM", LABOR_MODEL_WEEKDAY_EMPTY],
      ["pct", "PCT 5 AM", LABOR_MODEL_WEEKDAY_EMPTY],
      ["pct", "PCT 1 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 3 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 4 PM", LABOR_MODEL_WEEKDAY_EMPTY],
      ["supervisor", "SUP 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.supAm],
      ["supervisor", "SUP 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.supWeekdayPm],
      ["assistant_manager", "MOD 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.modAm],
      ["assistant_manager", "MOD 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.modWeekdayPm],
    ]),
    friday: makeDefaultLaborModelDay("friday", "5:30 AM - 7:30 PM", LABOR_MODEL_WEEKDAY_COLUMNS, [
      ["csr", "CSR 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.csrAm],
      ["csr", "CSR 2 AM", LABOR_MODEL_WEEKDAY_PATTERNS.csrAmExtended],
      ["csr", "CSR 3 Mid", LABOR_MODEL_WEEKDAY_PATTERNS.csrWeekdayMid],
      ["csr", "CSR 1 PM", LABOR_MODEL_WEEKDAY_PATTERNS.csrPm],
      ["csr", "CSR 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.csrPm],
      ["csr", "CSR 3", LABOR_MODEL_WEEKDAY_PATTERNS.csrWeekdayPmFlex],
      ["pct", "PCT 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAmExtended],
      ["pct", "PCT 2 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAm],
      ["pct", "PCT 3 AM", LABOR_MODEL_WEEKDAY_PATTERNS.pctAm],
      ["pct", "PCT 4 AM", LABOR_MODEL_WEEKDAY_EMPTY],
      ["pct", "PCT 5 AM", LABOR_MODEL_WEEKDAY_EMPTY],
      ["pct", "PCT 1 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 3 PM", LABOR_MODEL_WEEKDAY_PATTERNS.pctPm],
      ["pct", "PCT 4 PM", LABOR_MODEL_WEEKDAY_EMPTY],
      ["supervisor", "SUP 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.supAm],
      ["supervisor", "SUP 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.supWeekdayPm],
      ["assistant_manager", "MOD 1 AM", LABOR_MODEL_WEEKDAY_PATTERNS.modAm],
      ["assistant_manager", "MOD 2 PM", LABOR_MODEL_WEEKDAY_PATTERNS.modWeekdayPm],
    ]),
    saturday: makeDefaultLaborModelDay("saturday", "6:30 AM - 7:00 PM", LABOR_MODEL_WEEKEND_COLUMNS, [
      ["csr", "CSR 1 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["csr", "CSR 2 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["csr", "CSR 3 Mid", LABOR_MODEL_WEEKEND_EMPTY],
      ["csr", "CSR 1 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
      ["csr", "CSR 2 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
      ["csr", "CSR 3", LABOR_MODEL_WEEKEND_EMPTY],
      ["pct", "PCT 1 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["pct", "PCT 2 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["pct", "PCT 3 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["pct", "PCT 4 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["pct", "PCT 5 AM", LABOR_MODEL_WEEKEND_EMPTY],
      ["pct", "PCT 1 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
      ["pct", "PCT 2 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
      ["pct", "PCT 3 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
      ["pct", "PCT 4 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
      ["supervisor", "SUP 1 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["supervisor", "SUP 2 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
      ["assistant_manager", "MOD 1 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["assistant_manager", "MOD 2 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
    ]),
    sunday: makeDefaultLaborModelDay("sunday", "6:30 AM - 7:00 PM", LABOR_MODEL_WEEKEND_COLUMNS, [
      ["csr", "CSR 1 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["csr", "CSR 2 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["csr", "CSR 3 Mid", LABOR_MODEL_WEEKEND_EMPTY],
      ["csr", "CSR 1 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
      ["csr", "CSR 2 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
      ["csr", "CSR 3", LABOR_MODEL_WEEKEND_EMPTY],
      ["pct", "PCT 1 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["pct", "PCT 2 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["pct", "PCT 3 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["pct", "PCT 4 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["pct", "PCT 5 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["pct", "PCT 1 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
      ["pct", "PCT 2 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
      ["pct", "PCT 3 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
      ["pct", "PCT 4 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
      ["supervisor", "SUP 1 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["supervisor", "SUP 2 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
      ["assistant_manager", "MOD 1 AM", LABOR_MODEL_WEEKEND_PATTERNS.am],
      ["assistant_manager", "MOD 2 PM", LABOR_MODEL_WEEKEND_PATTERNS.pm],
    ]),
  },
};

export function cloneDefaultHourAnalysisLaborModel() {
  return JSON.parse(JSON.stringify(DEFAULT_HOUR_ANALYSIS_LABOR_MODEL));
}
