// ─── EOD Template ─────────────────────────────────────────────────────────────
const DEF_EOD_TEMPLATE = [
  { id:"sales", title:"Sales", emoji:"💵", type:"text", defaultContent:"Today's Goal:\nWTD:\nMTD:\nYTD:" },
  { id:"csr_checklist", title:"CSR Checklist", emoji:"📋", type:"checklist", defaultContent:"Turn on Luxury TV's\nTurn on music\nCreate Private Play log\nVacuum and Cherry front lobby before 7:00 am\nUnlock latches on front door\nCheck incoming Tours\nDo body checks on dogs leaving today and fill out form" },
  { id:"alerts", title:"Alerts", emoji:"📢", type:"text", defaultContent:"- Goal for Each CSR to book at least 1 Eval/Tour and Sell 1 Package/book reservation w/paid deposit daily" },
  { id:"team_notes", title:"Team Notes / Communications", emoji:"💬", type:"text", defaultContent:"" },
  { id:"leads", title:"Leads to Target Today", emoji:"🎯", type:"text", defaultContent:"" },
  { id:"tours", title:"Tours", emoji:"🏠", type:"text", defaultContent:"" },
  { id:"meds", title:"Meds", emoji:"💊", type:"text", defaultContent:"Boarding:\nAM:\n-\nNOON:\n-\nPM:\n-\n\nDaycare:\n-" },
  { id:"birthdays", title:"Birthdays", emoji:"🎉", type:"text", defaultContent:"" },
  { id:"ice_cream", title:"Doggie Ice Cream", emoji:"🍦", type:"text", defaultContent:"" },
  { id:"extra_play", title:"Extra Play Sessions", emoji:"⚽", type:"text", defaultContent:"" },
  { id:"baths", title:"Baths", emoji:"🛁", type:"checklist", defaultContent:"" },
  { id:"day_boarders", title:"Day Boarders / PP", emoji:"🚩", type:"text", defaultContent:"" },
  { id:"evaluations", title:"Evaluations", emoji:"📊", type:"text", defaultContent:"Name, L/S daycare, Room # - Pass/fail, if parents have been contacted\n-" },
  { id:"small_daycare_notes", title:"Small Daycare Notes", emoji:"🐕", type:"text", defaultContent:"(Dogs name, last initial, date/time and details of incident)\n-" },
  { id:"large_daycare_notes", title:"Large Daycare Notes", emoji:"🐕", type:"text", defaultContent:"(Dogs name, last initial, date/time and details of incident)\n-" },
  { id:"boarding_notes", title:"Boarding Notes", emoji:"🏨", type:"text", defaultContent:"" },
  { id:"social_media", title:"Social Media Photos", emoji:"📸", type:"checklist", defaultContent:"Instagram Stories\nInstagram Post" },
  { id:"picture_requests", title:"Picture Requests", emoji:"📷", type:"checklist", defaultContent:"" },
  { id:"building_supplies", title:"Building / Supplies", emoji:"🔧", type:"text", defaultContent:"" },
  { id:"other", title:"Other", emoji:"📝", type:"text", defaultContent:"" },
];

// ─── Daily Operations Default Templates ──────────────────────────────────────
const DEF_OPENING_TEMPLATE = [
  {id:"ot1",label:"Disarm alarm system (during business hours only) & make sure door is locked behind you"},
  {id:"ot2",label:"Turn on all inside lights"},
  {id:"ot3",label:"Raise or lower the thermostat"},
  {id:"ot4",label:"Check rooms closest to lobby for accidents and smells"},
  {id:"ot5",label:"Open POS system and log in"},
  {id:"ot6",label:"Confirm all staff radios are on"},
  {id:"ot7",label:"Unlock Private Play yard"},
  {id:"ot8",label:"Follow POD procedure or ensure it is being done"},
  {id:"ot9",label:"Check fax, emails & voicemails"},
  {id:"ot10",label:"Confirm staff has begun doing baths if necessary"},
  {id:"ot11",label:"Make sure all dogs not receiving a bath are scheduled for Fresh n Clean"},
  {id:"ot12",label:"Make sure all Bodycheck forms & nametags are prepared for the day"},
];

const DEF_FE_TEMPLATE = [
  {id:"fe1",time:"6:15",label:"AM feeding and medication"},
  {id:"fe2",time:"6:45",label:"Check voicemails, document on Voicemail Log"},
  {id:"fe3",time:"7:00",label:"Confirm everyone has a radio and name tag"},
  {id:"fe4",time:"7:15",label:"Review & Start EOD"},
  {id:"fe5",time:"8:00",label:"Check tour book / evals, document on Tour Log & Eval Log"},
  {id:"fe6",time:"8:15",label:"Confirm transport of boarding dogs to daycare"},
  {id:"fe7",time:"8:45",label:"After baths check dogs leaving that day, compare w/ check-in sheet"},
  {id:"fe8",time:"9:00",label:"Check belongings for dogs leaving"},
  {id:"fe9",time:"9:15",label:"Return calls from voicemail log"},
  {id:"fe10",time:"9:30",label:"Check & return emails"},
  {id:"fe11",time:"9:45",label:"Notate any Day Boarders"},
  {id:"fe12",time:"10:00",label:"Evaluations - 10am to noon, document on Eval Log"},
  {id:"fe13",time:"10:15",label:"Clean counters"},
  {id:"fe14",time:"10:30",label:"Clean tour area with rescue wipes as needed"},
  {id:"fe15",time:"10:45",label:"Dust Lobby"},
  {id:"fe16",time:"11:00",label:"AM playtime and let outs begin (initial only when completed)"},
  {id:"fe17",time:"11:15",label:"Recheck EOD"},
  {id:"fe18",time:"11:30",label:"Check & return emails"},
  {id:"fe19",time:"11:45",label:"Open invoice check - Reports > Revenue > Open Invoices"},
  {id:"fe20",time:"12:00",label:"Noon feeding and medication (if needed), Noon feeding/med log"},
  {id:"fe21",time:"12:30",label:"Afternoon walkthrough - Compliance check"},
  {id:"fe22",time:"12:45",label:"Double check dogs that have not left yet, perform Fresh & Clean when needed"},
  {id:"fe23",time:"13:00",label:"Baths for daycare dogs"},
  {id:"fe24",time:"13:15",label:"Run day charge for any boarding dogs that have not been picked up"},
  {id:"fe25",time:"13:30",label:"Check daycare board - daycare list"},
  {id:"fe26",time:"13:45",label:"Make booklet list - 3 or less - daycare list"},
  {id:"fe27",time:"14:00",label:"Vaccinations check"},
  {id:"fe28",time:"14:15",label:"Front Lobby/Tour Area swept & mopped"},
  {id:"fe29",time:"14:30",label:"PM playtime and let outs begin"},
  {id:"fe30",time:"14:45",label:"Exterior walkthrough / perimeter inspections"},
  {id:"fe31",time:"15:00",label:"Paperwork for next day"},
  {id:"fe32",time:"15:15",label:"Check belongings for next day departures"},
  {id:"fe33",time:"15:30",label:"Check & return emails"},
  {id:"fe34",time:"16:00",label:"Scan, name & store new customer policy sheets"},
  {id:"fe35",time:"17:30",label:"PM feeding and medication - replace all food bowls (start earlier if busy)"},
  {id:"fe36",time:"18:00",label:"Clean and set food cart"},
  {id:"fe37",time:"18:30",label:"Double check / update paperwork"},
  {id:"fe38",time:"18:45",label:"Review, close & save EOD"},
  {id:"fe39",time:"19:00",label:"Closing Instructions Checklist"},
  {id:"fe40",time:"19:30",label:"Evening walkthrough / lock up"},
  // Admin Day - Wednesday
  {id:"fe_ad1",time:"",label:"Follow up on tour forms",dayOfWeek:3},
  {id:"fe_ad2",time:"",label:"Client follow up for minor and major issues (handle within 24hrs)",dayOfWeek:3},
  {id:"fe_ad3",time:"",label:"Send out thank you cards",dayOfWeek:3},
  {id:"fe_ad4",time:"",label:"Print any needed forms",dayOfWeek:3},
  {id:"fe_ad5",time:"",label:"Take inventory for front and back end",dayOfWeek:3},
  {id:"fe_ad6",time:"",label:"Sign check - Upcoming holidays and scheduling",dayOfWeek:3},
];

const DEF_BE_TEMPLATE = [
  {id:"be1",time:"6:00",label:"(2) People - Prepare mops for spot cleaning, each daycare, disinfecting and lobby"},
  {id:"be2",time:"6:00",label:"Prepare janitor cart with cleaning supplies, trash bag, gloves and safety materials"},
  {id:"be3",time:"6:10",label:"(2) People - Perform spot cleaning of all accommodation prior to feeding - follow the standard path"},
  {id:"be4",time:"6:10",label:"(1) Person - Mop front lobby and luxury hallway with OdorPet Cherry"},
  {id:"be5",time:"6:45",label:"Clean windows in all customer facing areas"},
  {id:"be6",time:"7:00",label:"Large & Small Daycare will go into daycare to allow for transportation of boarding dogs"},
  {id:"be7",time:"7:00",label:"Daily Room Cleaning of all overnight dogs (follow standard path) - transport daycare dogs to daycare, red collar dogs 1 by 1 for elimination breaks"},
  {id:"be8",time:"7:00",label:"Bring fresh water to each daycare. Note: Mop hallways of each section as you exit"},
  {id:"be9",time:"7:30",label:"Replace water in all boarding rooms"},
  {id:"be10",time:"7:45",label:"Perform all baths (standard and waterless) - check bath list"},
  {id:"be11",time:"8:30",label:"Ensure all drying units are set to 85 or less & never leave a dog unattended"},
  {id:"be12",time:"8:45",label:"Clean bathing area once complete"},
  {id:"be13",time:"9:00",label:"Disinfect rooms - check disinfecting list"},
  {id:"be14",time:"10:00",label:"Shift Change"},
  {id:"be15",time:"10:15",label:"Disinfect bowls, dry and place in storage area"},
  {id:"be16",time:"10:30",label:"Refill water in all boarding rooms and spot clean as needed - Check happiness and health"},
  {id:"be17",time:"11:00",label:"Remove daycare water bowls & clean - leave a new one with water in it behind"},
  {id:"be18",time:"11:15",label:"Clean Kitchen/break area"},
  {id:"be19",time:"11:30",label:"Rake hair and wysiwash outdoor areas - fence/grass of Pens (after personal playtimes)"},
  {id:"be20",time:"12:00",label:"Lunch Change"},
  {id:"be21",time:"12:30",label:"Lunch Change"},
  {id:"be22",time:"13:00",label:"Lunch Change"},
  {id:"be23",time:"13:30",label:"Daycare/additional baths - check bath list"},
  {id:"be24",time:"14:15",label:"Weekly Task - See Weekly Task List"},
  {id:"be25",time:"15:00",label:"Restock any supplies needed from storage"},
  {id:"be26",time:"15:15",label:"Mop with Rescue the front lobby, tour area, and bathrooms; daily clean bathrooms"},
  {id:"be27",time:"16:00",label:"Shift Change"},
  {id:"be28",time:"16:15",label:"Rake hair and wysiwash outdoor areas - fence/grass of Large daycare"},
  {id:"be29",time:"16:45",label:"Rake hair and wysiwash outdoor areas - fence/grass of Small daycare"},
  {id:"be30",time:"17:00",label:"Disinfect outgoing red collar rooms"},
  {id:"be31",time:"17:30",label:"Replace all water bowls with similar size and fill all water bowls"},
  {id:"be32",time:"17:45",label:"Remove daycare water bowls & clean"},
  {id:"be33",time:"18:00",label:"Evening let outs for red collars"},
  {id:"be34",time:"18:30",label:"Bring boarding dogs from small and large daycare back to their rooms"},
  {id:"be35",time:"19:00",label:"Mop small daycare"},
  {id:"be36",time:"19:00",label:"Mop large daycare"},
  {id:"be37",time:"19:00",label:"Change garbages"},
  {id:"be38",time:"19:00",label:"Clean out all mop buckets"},
  {id:"be39",time:"19:15",label:"End of Day"},
  // Weekly tasks
  {id:"be_w1",time:"",label:"Disinfect leads, boots, and aprons",dayOfWeek:1},
  {id:"be_w2",time:"",label:"Take inventory and report to front end",dayOfWeek:1},
  {id:"be_w3",time:"",label:"Disinfect outdoor pen area w/ Rescue",dayOfWeek:2},
  {id:"be_w4",time:"",label:"Disinfect small outdoor area w/ Rescue",dayOfWeek:3},
  {id:"be_w5",time:"",label:"Disinfect large outdoor area w/ Rescue",dayOfWeek:4},
  {id:"be_w6",time:"",label:"Disinfect bathrooms",dayOfWeek:5},
  {id:"be_w7",time:"",label:"Disinfect bathing area",dayOfWeek:6},
  {id:"be_w8",time:"",label:"Vacuum and clean vents",dayOfWeek:0},
];

const DEF_CLOSING_TEMPLATE = [
  {id:"ct1",label:"Make sure all dogs have checked out for daycare"},
  {id:"ct2",label:"Make sure body check forms are completed, bath list is made, disinfecting list is made, vaccines are checked for all check-ins, and name tags are made"},
  {id:"ct3",label:"Charge all radios for the night"},
  {id:"ct4",label:"Make sure all dogs have been fed & medicated"},
  {id:"ct5",label:"Make sure no dogs were left outside"},
  {id:"ct6",label:"Check all Playtime pens and yards in both daycare areas"},
  {id:"ct7",label:"Make sure all dogs have full bowls of water"},
  {id:"ct8",label:"Make sure no dogs have gone to the bathroom in their accommodation"},
  {id:"ct9",label:"Make sure all dogs have proper collars on & belongings are stored properly"},
  {id:"ct10",label:"Logout and close POS on all computers"},
  {id:"ct11",label:"Make sure all lights are off indoors"},
  {id:"ct12",label:"Lock appropriate exterior doors that might be unlocked"},
  {id:"ct13",label:"Set your alarm & lock front doors"},
];

const OPS_TYPES = {opening:{key:"openingTemplate",def:DEF_OPENING_TEMPLATE,title:"Opening Checklist"},fe_checklist:{key:"feTemplate",def:DEF_FE_TEMPLATE,title:"Front-End Checklist",showTime:true},be_checklist:{key:"beTemplate",def:DEF_BE_TEMPLATE,title:"Back-End Checklist",showTime:true},closing:{key:"closingTemplate",def:DEF_CLOSING_TEMPLATE,title:"Closing Checklist"},room_cleaning:{title:"Room Cleaning & Setups"},pictures:{title:"Picture Checklist"},pp:{title:"Private Play Checklist"}};
const DAY_NAMES_SHORT=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];

// ─── Operations Hub Catalog ───────────────────────────────────────────────────
const OPERATIONS_CATALOG = [
  // Daily items (route to existing pages)
  { id:"ops-opening", label:"Opening Checklist", frequency:"daily", dataKey:"dailyOps", typeSub:"opening", routeTo:"ops-opening", permission:"view_daily_ops" },
  { id:"ops-fe", label:"Front-End Checklist", frequency:"daily", dataKey:"dailyOps", typeSub:"fe_checklist", routeTo:"ops-fe", permission:"view_daily_ops" },
  { id:"ops-be", label:"Back-End Checklist", frequency:"daily", dataKey:"dailyOps", typeSub:"be_checklist", routeTo:"ops-be", permission:"view_daily_ops" },
  { id:"ops-rooms", label:"Room Cleaning & Setups", frequency:"daily", dataKey:"dailyOps", typeSub:"room_cleaning", routeTo:"ops-rooms", permission:"view_daily_ops" },
  { id:"ops-pictures", label:"Pictures", frequency:"daily", dataKey:"dailyOps", typeSub:"pictures", routeTo:"ops-pictures", permission:"view_daily_ops" },
  { id:"ops-pp", label:"Private Play Checklist", frequency:"daily", dataKey:"dailyOps", typeSub:"pp", routeTo:"ops-pp", permission:"view_daily_ops" },
  { id:"ops-closing", label:"Closing Checklist", frequency:"daily", dataKey:"dailyOps", typeSub:"closing", routeTo:"ops-closing", permission:"view_daily_ops" },
  { id:"eod", label:"EOD Report", frequency:"daily", dataKey:"eodEntries", typeSub:null, routeTo:"eod", permission:"view_eod" },
  // Weekly placeholders
  { id:"weekly-inventory", label:"Weekly Inventory", frequency:"weekly", comingSoon:true },
  { id:"weekly-maintenance", label:"Weekly Maintenance", frequency:"weekly", comingSoon:true },
  // Monthly placeholders
  { id:"monthly-safety", label:"Monthly Safety Audit", frequency:"monthly", comingSoon:true },
  { id:"monthly-deep-clean", label:"Monthly Deep Clean", frequency:"monthly", comingSoon:true },
];

export { DEF_EOD_TEMPLATE, DEF_OPENING_TEMPLATE, DEF_FE_TEMPLATE, DEF_BE_TEMPLATE, DEF_CLOSING_TEMPLATE, OPS_TYPES, DAY_NAMES_SHORT, OPERATIONS_CATALOG };
