export const PLAY_ICON_CAPABILITY_KEYS = [
  "play.private_play",
  "play.large_daycare",
  "play.small_daycare",
  "play.evaluation",
];

export const BATHING_ICON_CAPABILITY_KEYS = [
  "bathing.include",
  "bathing.type.standard",
  "bathing.type.premium",
  "bathing.type.medicated",
  "bathing.type.whitening",
  "bathing.type.shampoo_from_home",
  "bathing.type.hypoallergenic",
  "bathing.type.hypoallergenic_no_spray",
  "bathing.type.hypoallergenic_with_spray",
  "bathing.type.water_rinse",
  "bathing.type.fresh_n_clean",
  "bathing.modifier.no_dryer",
  "bathing.modifier.no_crate_dryer",
  "bathing.modifier.no_velocity_dryer",
  "bathing.modifier.towel_dry_only",
  "bathing.modifier.see_account_notes",
];

export const RESERVATION_CATEGORY_WORKFLOW_KEYS = new Set([
  "bathing",
  "room_cleaning",
  "collar_prep",
  "roll_call",
  "feeding_meds",
  "lodging_transfers",
  "belongings",
]);

export const ROOM_CLEANING_RUN_CAPABILITIES = [
  { value: "", label: "Ignore / unmapped" },
  { value: "room_cleaning.lodging_room", label: "Lodging room" },
  { value: "room_cleaning.private_play_room", label: "Private play room" },
  { value: "room_cleaning.isolation_room", label: "Isolation room" },
];

export const WORKFLOW_COLUMNS = [
  {
    key: "bathing",
    label: "Bathing Report",
    short: "Bathing",
    iconCapabilityKey: null,
    serviceCapabilityKey: "bathing.include",
    legacyDisplayCapabilityKeys: [
      ...BATHING_ICON_CAPABILITY_KEYS,
      ...PLAY_ICON_CAPABILITY_KEYS,
    ],
    severity: "cosmetic",
    note: "Selected icons display on bathing rows and carry their Gingr comments into notes. Services/add-ons and stay logic decide who appears.",
  },
  {
    key: "private_play",
    label: "Private Play",
    short: "PP",
    iconCapabilityKey: "play.private_play",
    serviceCapabilityKey: "private_play.include",
    severity: "driver",
    note: "Icon choices can change which dogs appear on the private play list.",
  },
  {
    key: "room_cleaning",
    label: "Room Cleaning",
    short: "Rooms",
    serviceCapabilityKey: "room_cleaning.include",
    severity: "cosmetic",
    note: "Room cleaning is still driven by room and stay logic; icons are display context.",
  },
  {
    key: "shutouts",
    label: "Shutouts",
    short: "Shutouts",
    serviceCapabilityKey: "shutouts.include",
    severity: "cosmetic",
    note: "Display flag for shutout workflows.",
  },
  {
    key: "enrichment",
    label: "Enrichment",
    short: "Enrich.",
    serviceCapabilityKey: "enrichment.include",
    legacyDisplayCapabilityKeys: PLAY_ICON_CAPABILITY_KEYS,
    severity: "driver",
    note: "Services/add-ons drive enrichment report inclusion; play icons display playgroup context on the workflow rows.",
  },
  {
    key: "pamper",
    label: "Pamper Package",
    short: "Pamper",
    serviceCapabilityKey: "pamper.include",
    legacyDisplayCapabilityKeys: PLAY_ICON_CAPABILITY_KEYS,
    severity: "driver",
    note: "Services/add-ons and configured suite logic drive pamper inclusion; play icons display playgroup context on the workflow rows.",
  },
  {
    key: "collar_prep",
    label: "Collar Prep",
    short: "Collars",
    serviceCapabilityKey: "collar_prep.include",
    legacyDisplayCapabilityKeys: PLAY_ICON_CAPABILITY_KEYS,
    severity: "cosmetic",
    note: "Collar prep is category and play-icon driven; play icons are shown as operational context.",
  },
  {
    key: "roll_call",
    label: "Roll Call",
    short: "Roll Call",
    serviceCapabilityKey: "roll_call.include",
    legacyDisplayCapabilityKeys: PLAY_ICON_CAPABILITY_KEYS,
    severity: "cosmetic",
    note: "Roll call is category and room driven; play icons display as dog-level context.",
  },
  {
    key: "feeding_meds",
    label: "Feeding & Meds",
    short: "Feed/Meds",
    serviceCapabilityKey: "feeding_meds.include",
    legacyDisplayCapabilityKeys: PLAY_ICON_CAPABILITY_KEYS,
    severity: "cosmetic",
    note: "Feeding and medication tasks remain schedule-driven; play icons display as dog-level context.",
  },
  {
    key: "lodging_transfers",
    label: "Transfers",
    short: "Transfers",
    serviceCapabilityKey: "lodging_transfers.include",
    severity: "cosmetic",
    note: "Transfers remain room-change driven; icons are display context.",
  },
  {
    key: "gourmet_ice_cream",
    label: "Gourmet Ice Cream",
    short: "Ice Cream",
    serviceCapabilityKey: "gourmet_ice_cream.include",
    legacyDisplayCapabilityKeys: PLAY_ICON_CAPABILITY_KEYS,
    severity: "driver",
    note: "Services/add-ons drive ice cream inclusion; play icons display playgroup context on service rows.",
  },
  {
    key: "belongings",
    label: "Belongings",
    short: "Belong.",
    serviceCapabilityKey: "belongings.include",
    severity: "cosmetic",
    note: "Belongings remains departure/check-in form driven; icons are display context.",
  },
];

export const WORKFLOW_SOURCE_INVENTORY = [
  {
    key: "gingr_reference_sync",
    label: "Gingr Reference Sync",
    roleIds: ["bootstrap", "onboarding"],
    route: "settings",
    dailyOpsId: "gingr_reference_sync_runs",
    completionKey: "v_gingr_initial_sync_status",
    configStatus: "covered",
    sources: ["Animal icons", "Reservation types", "Services/add-ons", "Runs/rooms", "Feeding and medication source data"],
    currentDefaults: ["full historical pull on initial sync", "reference refresh can be rerun from this page"],
    configCoverage: ["Summary tiles", "Initial sync status", "Refresh Gingr Data"],
  },
  {
    key: "reservation_categories",
    label: "Shared Reservation Categories",
    roleIds: ["reservation_categories"],
    route: "shared server dependency",
    dailyOpsId: "not a daily row",
    completionKey: "not applicable",
    configStatus: "covered",
    sources: ["Gingr reservation types"],
    currentDefaults: ["boarding", "day boarding", "daycare", "evaluation", "grooming", "tour", "other"],
    configCoverage: ["Reservation Types"],
  },
  {
    key: "playgroups",
    label: "Shared Playgroup Icons",
    roleIds: ["playgroups"],
    route: "shared server dependency",
    dailyOpsId: "v_dog_playgroups / v_dog_playgroup_icon_tags",
    completionKey: "not applicable",
    configStatus: "covered",
    sources: ["Gingr animal icons"],
    currentDefaults: ["private play", "large daycare", "small daycare", "evaluation"],
    configCoverage: ["Icon Matrix"],
  },
  {
    key: "room_occupancy",
    label: "Room Occupancy Source",
    roleIds: ["room_occupancy"],
    route: "shared server dependency",
    dailyOpsId: "ops_room_occupancy_${date}",
    completionKey: "not applicable",
    configStatus: "partial",
    sources: ["Gingr runs/rooms", "Room occupancy table", "Reservation categories"],
    currentDefaults: ["lodging-only categories", "room code extraction", "daycare/evaluation exclusion"],
    configCoverage: ["Runs / Rooms", "Reservation Types"],
  },
  {
    key: "bathing",
    label: "Bathing Report",
    roleIds: ["bathing"],
    route: "ops-bathing",
    dailyOpsId: "ops_bathing_${date}",
    completionKey: "ops_bathing_${date}",
    configStatus: "covered",
    sources: ["Bath services/add-ons", "Bath and play icons for display", "Boarding stay logic"],
    currentDefaults: ["service/add-on contains bath or groom", "bath icons display shampoo/modifier notes", "play icons display playgroup context"],
    configCoverage: ["Services/Add-ons", "Icon Matrix", "Reservation Types"],
  },
  {
    key: "private_play",
    label: "Private Play",
    roleIds: ["pp", "private_play"],
    route: "ops-pp",
    dailyOpsId: "ops_pp_${date}",
    completionKey: "ops_pp_${date}",
    configStatus: "covered",
    sources: ["Private Play icon", "Private Play / play-time services", "Day boarding / reservation type rules"],
    currentDefaults: ["icon capability play.private_play", "service/add-on contains private play or play time", "default required sessions = 3"],
    configCoverage: ["Icon Matrix", "Services/Add-ons", "Reservation Types", "PP sessions"],
  },
  {
    key: "room_cleaning",
    label: "Room Cleaning & Setups",
    roleIds: ["room_cleaning"],
    route: "ops-rooms",
    dailyOpsId: "ops_room_cleaning_${date}",
    completionKey: "task ids in ops_room_cleaning_${date}",
    configStatus: "covered",
    sources: ["Gingr runs/rooms", "Room occupancy", "Boarding arrival/departure dates"],
    currentDefaults: ["run.is_private_play", "run.is_isolation", "otherwise lodging room", "refresh/full disinfect/setup business rules stay server-side"],
    configCoverage: ["Runs / Rooms", "Reservation Types"],
  },
  {
    key: "enrichment",
    label: "Enrichment",
    roleIds: ["enrichment"],
    route: "ops-svc",
    dailyOpsId: "ops_svc_${date}",
    completionKey: "ops_svc_Enrichment_${date}",
    configStatus: "covered",
    sources: ["Enrichment services/add-ons", "Play icons for display"],
    currentDefaults: ["service/add-on contains enrichment", "play icons display playgroup context"],
    configCoverage: ["Services/Add-ons", "Icon Matrix", "Reservation Types"],
  },
  {
    key: "pamper",
    label: "Pamper Package",
    roleIds: ["pamper"],
    route: "ops-pamper",
    dailyOpsId: "ops_pamper_${date}",
    completionKey: "ops_pamper_${date}",
    configStatus: "covered",
    sources: ["Pamper services/add-ons", "Luxury Suite reservation types", "Play icons for display"],
    currentDefaults: ["service/add-on contains pamper", "reservation type contains luxury suite"],
    configCoverage: ["Services/Add-ons", "Reservation Types", "Icon Matrix"],
  },
  {
    key: "collar_prep",
    label: "Next Day Collars",
    roleIds: ["collars", "collar_prep"],
    route: "ops-collars",
    dailyOpsId: "ops_collars_${tomorrow}",
    completionKey: "ops_collars_completions_${tomorrow}",
    configStatus: "partial",
    sources: ["Next-day reservations", "Play icons", "Collar color rules"],
    currentDefaults: ["small/large/private/evaluation play parsing", "pink/red/green/blue/yellow/half-and-half collar buckets"],
    configCoverage: ["Icon Matrix now covers play icons", "Collar color policy still needs runtime config"],
  },
  {
    key: "roll_call_opening",
    label: "Opening Roll Call",
    roleIds: ["roll_call_opening"],
    route: "ops-roll-call-opening",
    dailyOpsId: "ops_roll_call_opening_${date}",
    completionKey: "room/reservation row completions",
    configStatus: "partial",
    sources: ["Current in-resort dogs", "Reservation categories", "Room/area order", "Play icons for display"],
    currentDefaults: ["area order and boarding classification are code-defined"],
    configCoverage: ["Reservation Types", "Icon Matrix", "Runs / Rooms visible; area ordering still needs runtime config"],
  },
  {
    key: "roll_call_closing",
    label: "Closing Roll Call",
    roleIds: ["roll_call_closing", "roll_call"],
    route: "ops-roll-call-closing",
    dailyOpsId: "ops_roll_call_closing_${date}",
    completionKey: "room/reservation row completions",
    configStatus: "partial",
    sources: ["Current in-resort dogs", "Reservation categories", "Room/area order", "Play icons for display"],
    currentDefaults: ["closing roll call shares the same area and category assumptions"],
    configCoverage: ["Reservation Types", "Icon Matrix", "Runs / Rooms visible; area ordering still needs runtime config"],
  },
  {
    key: "feeding_meds_am",
    label: "AM Feeding & Meds",
    roleIds: ["feeding_meds_am"],
    route: "ops-feeding-meds-am",
    dailyOpsId: "ops_feeding_meds_am_${date}",
    completionKey: "instruction item ids",
    configStatus: "partial",
    sources: ["Feeding schedules", "Medication schedules", "Reservation status", "Play icons for display"],
    currentDefaults: ["AM aliases include morning/breakfast and early hour matches", "BID/TID schedule handling is code-defined"],
    configCoverage: ["Icon Matrix; care schedule aliases still need runtime config"],
  },
  {
    key: "feeding_meds_midday",
    label: "Midday Feeding & Meds",
    roleIds: ["feeding_meds_midday"],
    route: "ops-feeding-meds-midday",
    dailyOpsId: "ops_feeding_meds_midday_${date}",
    completionKey: "instruction item ids",
    configStatus: "partial",
    sources: ["Feeding schedules", "Medication schedules", "Reservation status", "Play icons for display"],
    currentDefaults: ["midday aliases include noon and 12", "BID/TID schedule handling is code-defined"],
    configCoverage: ["Icon Matrix; care schedule aliases still need runtime config"],
  },
  {
    key: "feeding_meds_pm",
    label: "PM Feeding & Meds",
    roleIds: ["feeding_meds_pm"],
    route: "ops-feeding-meds-pm",
    dailyOpsId: "ops_feeding_meds_pm_${date}",
    completionKey: "instruction item ids",
    configStatus: "partial",
    sources: ["Feeding schedules", "Medication schedules", "Reservation status", "Play icons for display"],
    currentDefaults: ["PM aliases include evening/dinner and 17/18/19", "BID/TID schedule handling is code-defined"],
    configCoverage: ["Icon Matrix; care schedule aliases still need runtime config"],
  },
  {
    key: "feeding_report",
    label: "Feeding Report",
    roleIds: ["feeding_report"],
    route: "ops-feeding-report",
    dailyOpsId: "ops_feeding_report_${date}",
    completionKey: "row ids with outcome",
    configStatus: "partial",
    sources: ["Feeding schedules", "Overnight boarding category", "Reservation status"],
    currentDefaults: ["overnight boarding is text/category classified"],
    configCoverage: ["Reservation Types; care report filters still need runtime config"],
  },
  {
    key: "medication_report",
    label: "Medication Report",
    roleIds: ["meds", "medication_report"],
    route: "ops-medication-report",
    dailyOpsId: "ops_medication_report_${date}",
    completionKey: "row ids with decision/outcome",
    configStatus: "partial",
    sources: ["Medication schedules", "Reservation status"],
    currentDefaults: ["web/mobile ids currently alias meds to medication_report"],
    configCoverage: ["care schedule aliases still need runtime config"],
  },
  {
    key: "lodging_transfer",
    label: "Lodging Transfers",
    roleIds: ["lodging_transfer", "lodging_transfers"],
    route: "ops-lodging-transfers",
    dailyOpsId: "ops_lodging_transfer_${date}",
    completionKey: "ops_lodging_transfer_completions_${date}",
    configStatus: "partial",
    sources: ["Gingr lodging transfer report", "Room assignment changes", "Current occupancy fallback"],
    currentDefaults: ["move belongings / update collar / clean old room / setup new room action taxonomy is code-defined"],
    configCoverage: ["Runs / Rooms visible; action taxonomy still needs runtime config"],
  },
  {
    key: "gourmet_ice_cream",
    label: "Gourmet Ice Cream",
    roleIds: ["ice_cream", "gourmet_ice_cream"],
    route: "eod",
    dailyOpsId: "ops_svc_${date}",
    completionKey: "ops_svc_Ice_Cream_${date}",
    configStatus: "covered",
    sources: ["Ice cream / gourmet services", "Play icons for display"],
    currentDefaults: ["service/add-on contains ice cream or gourmet"],
    configCoverage: ["Services/Add-ons", "Icon Matrix"],
  },
  {
    key: "belongings",
    label: "Belongings",
    roleIds: ["belongings"],
    route: "ops-belongings",
    dailyOpsId: "ops_belongings_${tomorrow}",
    completionKey: "ops_belongings_completions_${tomorrow}",
    configStatus: "partial",
    sources: ["Departing reservations", "Gingr belongings fields/forms"],
    currentDefaults: ["tomorrow departure window", "row key g${reservationGingrId}"],
    configCoverage: ["Reservation Types; departure field/window rules still need runtime config"],
  },
  {
    key: "shutouts",
    label: "Shutouts",
    roleIds: ["shutouts"],
    route: "",
    dailyOpsId: "No current runtime row found",
    completionKey: "No current completion source found",
    configStatus: "gap",
    sources: ["Requested workflow, but no current report code path was found in this repo"],
    currentDefaults: ["none found"],
    configCoverage: ["Column is reserved so icons/services can be paired when the runtime exists"],
  },
  {
    key: "scheduling_capacity",
    label: "Staffing Capacity",
    roleIds: ["scheduling_capacity"],
    route: "scheduling",
    dailyOpsId: "scheduling projection snapshots",
    completionKey: "not applicable",
    configStatus: "partial",
    sources: ["Reservation types", "Playgroup icons", "Bath services", "Medication services", "Runs/rooms"],
    currentDefaults: ["reservation bucket names", "medication service keyword", "departure bath logic", "capacity factors"],
    configCoverage: ["Reservation Types", "Icon Matrix", "Services/Add-ons; staffing factors still live outside this screen"],
  },
  {
    key: "checkout_tv",
    label: "Checkout TV / Facility Presence",
    roleIds: ["checkout_tv", "facility_presence"],
    route: "checkout-tv",
    dailyOpsId: "facility_presence_current",
    completionKey: "not applicable",
    configStatus: "partial",
    sources: ["Checked-in reservations", "Room assignments", "Playgroup icons", "Presence sync settings"],
    currentDefaults: ["presence cadence and business-hour behavior", "boarding/daycare/evaluation/day-boarding sets", "playgroup priority"],
    configCoverage: ["Reservation Types", "Icon Matrix", "Runs / Rooms; sync settings remain separate"],
  },
  {
    key: "re_eval",
    label: "Re-eval / Evaluations",
    roleIds: ["re_eval", "evaluations"],
    route: "eod / re-eval",
    dailyOpsId: "ops_re_eval_${date}",
    completionKey: "row ids with decision",
    configStatus: "gap",
    sources: ["Reservation history", "Evaluation outcomes", "Bad-note flags"],
    currentDefaults: ["365-day default threshold", "183-day bad-note threshold"],
    configCoverage: ["Thresholds and flags should move to workflow settings"],
  },
  {
    key: "departing",
    label: "Departing",
    roleIds: ["departing"],
    route: "departing",
    dailyOpsId: "count-only / Gingr reservations",
    completionKey: "No completion state",
    configStatus: "gap",
    sources: ["Gingr departures", "Bath service badge"],
    currentDefaults: ["bath keyword", "legacy location fallback needs removal"],
    configCoverage: ["Should reuse Bathing service config"],
  },
  {
    key: "emergency_contacts",
    label: "Emergency Contacts",
    roleIds: ["emergency_contacts"],
    route: "settings / emergency-contacts",
    dailyOpsId: "No canonical lite_daily_ops row",
    completionKey: "localStorage on mobile today",
    configStatus: "gap",
    sources: ["Active reservations", "Owner contact cache"],
    currentDefaults: ["repeat verification interval and completion storage are not canonical"],
    configCoverage: ["Needs canonical completion source before config switchover"],
  },
  {
    key: "attendance",
    label: "Attendance",
    roleIds: ["attendance"],
    route: "attendance",
    dailyOpsId: "non-Gingr",
    completionKey: "non-Gingr",
    configStatus: "non_gingr",
    sources: ["Labor / attendance data"],
    currentDefaults: ["managed outside Gingr workflow pairing"],
    configCoverage: ["Role layout, not Gingr Configuration"],
  },
  {
    key: "weekly_inventory",
    label: "Weekly Inventory",
    roleIds: ["weekly_inventory"],
    route: "inventory",
    dailyOpsId: "non-Gingr",
    completionKey: "inventory workflow state",
    configStatus: "non_gingr",
    sources: ["Inventory catalog"],
    currentDefaults: ["managed outside Gingr workflow pairing"],
    configCoverage: ["Inventory settings, not Gingr Configuration"],
  },
  {
    key: "weekly_maintenance",
    label: "Weekly Maintenance",
    roleIds: ["weekly_maintenance"],
    route: "ops-weekly-maintenance",
    dailyOpsId: "ops_weekly_maintenance_${date}",
    completionKey: "maintenance task ids",
    configStatus: "non_gingr",
    sources: ["Maintenance templates"],
    currentDefaults: ["managed outside Gingr workflow pairing"],
    configCoverage: ["Resort upkeep / checklist config, not Gingr Configuration"],
  },
  {
    key: "training",
    label: "Labor / Training",
    roleIds: ["training"],
    route: "training",
    dailyOpsId: "non-Gingr",
    completionKey: "training records",
    configStatus: "non_gingr",
    sources: ["Labor training data"],
    currentDefaults: ["managed outside Gingr workflow pairing"],
    configCoverage: ["Training settings, not Gingr Configuration"],
  },
  {
    key: "vendor_log",
    label: "Vendor Log",
    roleIds: ["vendor_log"],
    route: "",
    dailyOpsId: "non-Gingr",
    completionKey: "non-Gingr",
    configStatus: "non_gingr",
    sources: ["Vendor / maintenance logging"],
    currentDefaults: ["managed outside Gingr workflow pairing"],
    configCoverage: ["Not a Gingr pairing workflow"],
  },
];

export const WORKFLOW_COLUMN_WIDTH = 88;
export const ICON_NUMBER_COLUMN_WIDTH = 54;
export const ICON_NAME_COLUMN_WIDTH = 260;
export const ICON_GROUP_COLUMN_WIDTH = 140;
export const ICON_ASSIGNED_COLUMN_WIDTH = 96;
export const WORKFLOW_LEAD_COLUMN_WIDTH = ICON_NUMBER_COLUMN_WIDTH + ICON_NAME_COLUMN_WIDTH + ICON_GROUP_COLUMN_WIDTH + ICON_ASSIGNED_COLUMN_WIDTH;
export const WORKFLOW_TABLE_WIDTH = WORKFLOW_LEAD_COLUMN_WIDTH + (WORKFLOW_COLUMNS.length * WORKFLOW_COLUMN_WIDTH);

export const RESERVATION_CATEGORY_OPTIONS = [
  { value: "", label: "Unmapped" },
  { value: "boarding", label: "Boarding / Lodging" },
  { value: "daycare", label: "Daycare" },
  { value: "day_boarding", label: "Day Boarding" },
  { value: "evaluation", label: "Evaluation" },
  { value: "grooming", label: "Grooming" },
  { value: "tour", label: "Tour" },
  { value: "other", label: "Other" },
];

export const EMPTY_SECTIONS = {
  icons: true,
  services: true,
  reservations: true,
  rooms: true,
  workflows: true,
  review: true,
};

export const DEFAULT_ICON_FILTERS = {
  group: "",
  assignedOperator: "",
  assignedValue: "",
  workflowKey: "",
  workflowState: "enabled",
};

export const ASSIGNED_OPERATOR_OPTIONS = [
  { value: "", label: "Any assigned count" },
  { value: "over", label: "Over" },
  { value: "under", label: "Under" },
  { value: "equals", label: "Exactly" },
];

export const WORKFLOW_STATE_OPTIONS = [
  { value: "enabled", label: "Enabled" },
  { value: "disabled", label: "Not enabled" },
];

export const ICON_FILTER_FIELDS = [
  { key: "group", section: "Inventory", label: "Icon Group" },
  { key: "assigned", section: "Usage", label: "Assigned Count" },
  { key: "workflow", section: "Workflow", label: "Workflow Pairing" },
];

export const ICON_FILTER_OP_LABELS = {
  is: "is",
  over: "over",
  under: "under",
  equals: "exactly",
  enabled: "enabled for",
  disabled: "not enabled for",
};
