import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const CHERRY_HILL_LOCATION_ID = "11111111-1111-1111-1111-111111111111";

const LOCATION_ALIASES: Record<string, string> = {
  "cherry-hill": CHERRY_HILL_LOCATION_ID,
  your-gingr-subdomain: CHERRY_HILL_LOCATION_ID,
};

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const REPORT_CHECKS = [
  {
    key: "bathing",
    idPrefix: "ops_bathing",
    label: "Bathing Report",
    description: "Canonical daily bathing workload generated by ops-compute.",
    usedFor: ["Bathing Report", "Dashboard workflow progress"],
    warnMinutes: 5,
    failMinutes: 10,
  },
  {
    key: "room_cleaning",
    idPrefix: "ops_room_cleaning",
    label: "Room Cleaning + Setups",
    description: "Canonical room cleaning, setup, refresh, and disinfect workload generated by ops-compute.",
    usedFor: ["Room Cleaning", "Setups", "Dashboard workflow progress"],
    warnMinutes: 5,
    failMinutes: 10,
  },
  {
    key: "room_occupancy",
    idPrefix: "ops_room_occupancy",
    label: "Room Occupancy",
    description: "Canonical lodging-room occupancy output generated from today's Gingr reservations and room assignments.",
    usedFor: ["Room Occupancy", "Facility status"],
    warnMinutes: 5,
    failMinutes: 10,
  },
];

const CRON_CHECKS = [
  {
    jobname: "ops-compute-poll",
    label: "Ops Compute",
    functionName: "ops-compute",
    cadenceMinutes: 1,
    failMinutes: 4,
    criticality: "critical",
    description: "Runs the canonical daily operations compute pipeline and writes bathing, room cleaning, room occupancy, and related workflow outputs.",
    usedFor: ["Bathing Report", "Room Cleaning + Setups", "Room Occupancy", "Private Play"],
    affects: ["Bathing", "Room cleaning", "Room occupancy", "Private play"],
  },
  {
    jobname: "gingr-presence-sync",
    label: "Gingr Presence Worker",
    functionName: "gingr-sync",
    syncType: "presence-worker",
    cadenceMinutes: 1,
    failMinutes: 4,
    criticality: "critical",
    description: "Starts the server-owned presence worker loop that reconciles canonical facility presence every few seconds.",
    usedFor: ["Dashboard facility status", "Checkout TV", "Live checked-in dogs", "Today reservations"],
    affects: ["Live checked-in dogs", "Checkout TV transitions", "Today reservations"],
  },
  {
    jobname: "gingr-today-sync",
    label: "Gingr Today Sync",
    functionName: "gingr-sync",
    syncType: "today-sync",
    cadenceMinutes: 5,
    failMinutes: 12,
    criticality: "critical",
    description: "Pulls today's Gingr reservations, animals, owners, services, and room context needed by the daily reports.",
    usedFor: ["Today reservations", "Bathing Report", "Room Cleaning + Setups", "Room Occupancy"],
    affects: ["Today reservations", "Runs", "Occupancy"],
  },
  {
    jobname: "gingr-today-notes-refresh",
    label: "Gingr Notes Refresh",
    functionName: "gingr-today-notes",
    cadenceMinutes: 5,
    failMinutes: 12,
    criticality: "warning",
    description: "Refreshes same-day Gingr notes so checkout and care-note surfaces show current notes.",
    usedFor: ["Checkout notes", "Daily notes visibility"],
    affects: ["Checkout notes"],
  },
  {
    jobname: "compute-scheduling-matrix-cherry-hill-current-week",
    label: "Scheduling Matrix",
    functionName: "compute-scheduling-matrix",
    cadenceMinutes: 5,
    failMinutes: 15,
    criticality: "warning",
    description: "Computes the current-week scheduling matrix for Adair Forsythe staffing and planning surfaces.",
    usedFor: ["Scheduling matrix", "Staffing visibility"],
    affects: ["Scheduling matrix"],
  },
  {
    jobname: "gingr-incremental-sync",
    label: "Gingr Incremental Sync",
    functionName: "gingr-sync",
    syncType: "incremental",
    cadenceMinutes: 15,
    failMinutes: 45,
    criticality: "warning",
    description: "Backfills changed Gingr source records outside the live same-day polling path.",
    usedFor: ["Source-data backfill", "Historical correction", "Drift recovery"],
    affects: ["Source data backfill"],
  },
];

const ALERT_SYNC_ERROR_ENTITIES = new Set([
  "feeding_schedules",
  "medications",
  "reservations_today",
  "today-sync",
]);

type HealthAlert = {
  severity: string;
  kind: string;
  message: string;
  label?: string;
  function_name?: string | null;
  jobname?: string | null;
  key?: string | null;
  report_id?: string | null;
  affects?: string[];
  last_run_at?: string | null;
  last_run_status?: string | null;
  last_success_at?: string | null;
  last_failure_at?: string | null;
  last_failure_status_code?: number | null;
  age_minutes?: number | null;
  computed_at?: string | null;
  updated_at?: string | null;
  action?: string;
};

const SYNC_ENTITY_AFFECTS: Record<string, string[]> = {
  feeding_schedules: ["Feeding schedules", "Daily care notes"],
  medications: ["Medication visibility", "Daily care notes"],
  reservations_today: ["Today reservations", "Bathing", "Room cleaning", "Room occupancy"],
  "today-sync": ["Today reservations", "Runs", "Bathing", "Room cleaning", "Room occupancy"],
};

function nowEtDate() {
  const now = new Date(new Date().toLocaleString("en-US", { timeZone: "America/New_York" }));
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;
}

function normalizeLocationId(value: string | null | undefined) {
  const key = String(value || "cherry-hill").trim();
  return LOCATION_ALIASES[key] || key;
}

function ageMinutes(value: string | null | undefined) {
  if (!value) return null;
  const timestamp = new Date(value).getTime();
  if (Number.isNaN(timestamp)) return null;
  return Math.max(0, Math.round((Date.now() - timestamp) / 60000));
}

function cadenceLabel(minutes: number | null | undefined) {
  if (!minutes) return "On demand";
  return minutes === 1 ? "Every minute" : `Every ${minutes} minutes`;
}

function nextRunFromCadence(lastRunAt: string | null | undefined, cadenceMinutes: number | null | undefined, active: boolean) {
  if (!active || !cadenceMinutes) return null;
  const cadenceMs = cadenceMinutes * 60000;
  const nowMs = Date.now();
  const lastRunMs = lastRunAt ? new Date(lastRunAt).getTime() : NaN;
  const baseMs = Number.isNaN(lastRunMs) ? nowMs : lastRunMs;
  let nextMs = baseMs + cadenceMs;
  if (nextMs <= nowMs) {
    nextMs = baseMs + (Math.floor((nowMs - baseMs) / cadenceMs) + 1) * cadenceMs;
  }
  return new Date(nextMs).toISOString();
}

function etaMinutes(value: string | null | undefined) {
  if (!value) return null;
  const timestamp = new Date(value).getTime();
  if (Number.isNaN(timestamp)) return null;
  return Math.max(0, Math.ceil((timestamp - Date.now()) / 60000));
}

function freshnessStatus(age: number | null, warnMinutes: number, failMinutes: number) {
  if (age == null) return "unknown";
  if (age >= failMinutes) return "critical";
  if (age >= warnMinutes) return "warning";
  return "healthy";
}

function ageSeconds(value: string | null | undefined) {
  if (!value) return null;
  const timestamp = new Date(value).getTime();
  if (Number.isNaN(timestamp)) return null;
  return Math.max(0, Math.round((Date.now() - timestamp) / 1000));
}

const PRESENCE_HEALTH_DEFAULT_CONFIG = {
  normalIntervalSeconds: 5,
  offHoursIntervalSeconds: 30,
  businessHoursEnabled: true,
  businessHoursStart: "06:30",
  businessHoursEnd: "19:30",
  peakEnabled: false,
  peakIntervalSeconds: 3,
  peakWindows: [] as any[],
};

function presenceHealthInterval(configValue: any) {
  const config = configValue && typeof configValue === "object" ? configValue : {};
  const normal = Number(config.normalIntervalSeconds);
  const peak = Number(config.peakIntervalSeconds);
  if (config.peakEnabled === true && Number.isFinite(peak) && peak > 0) return peak;
  return Number.isFinite(normal) && normal > 0 ? normal : PRESENCE_HEALTH_DEFAULT_CONFIG.normalIntervalSeconds;
}

function presenceRunErrorMessage(run: any) {
  const errors = Array.isArray(run?.errors) ? run.errors : [];
  const messages = errors
    .map((entry: any) => entry?.message || entry?.error || (typeof entry === "string" ? entry : null))
    .filter(Boolean);
  return messages.length ? messages.slice(0, 3).join("; ") : null;
}

function severityRank(value: string) {
  if (value === "critical") return 3;
  if (value === "warning") return 2;
  if (value === "unknown") return 1;
  return 0;
}

function worstStatus(values: string[]) {
  return values.reduce((worst, value) => (severityRank(value) > severityRank(worst) ? value : worst), "healthy");
}

function safeJsonParse(value: string | null | undefined) {
  if (!value) return null;
  try {
    return JSON.parse(value);
  } catch {
    return null;
  }
}

function collectPayloadErrors(value: any, prefix = "", output: string[] = []) {
  if (output.length >= 5 || value == null) return output;
  if (Array.isArray(value)) {
    value.forEach((entry, index) => collectPayloadErrors(entry, `${prefix}[${index}]`, output));
    return output;
  }
  if (typeof value !== "object") return output;
  for (const [key, nested] of Object.entries(value)) {
    if (output.length >= 5) break;
    const path = prefix ? `${prefix}.${key}` : key;
    if (key === "error" && typeof nested === "string" && nested.trim()) {
      output.push(`${path}: ${nested.trim()}`);
    } else if (key === "success" && nested === false) {
      output.push(`${prefix || "payload"} reported success=false`);
    } else {
      collectPayloadErrors(nested, path, output);
    }
  }
  return output;
}

function payloadFailureMessages(content: string | null | undefined) {
  const payload = safeJsonParse(content);
  if (!payload) return [];
  return collectPayloadErrors(payload).slice(0, 5);
}

function responseErrorSummary(row: any) {
  if (row?.timed_out) return "Request timed out.";
  if (row?.error_msg) return String(row.error_msg);
  const payload = safeJsonParse(row?.content);
  if (payload?.message) return String(payload.message);
  if (payload?.error) return String(payload.error);
  const nested = payloadFailureMessages(row?.content);
  if (nested.length) return nested.join("; ");
  if (row?.status_code && row.status_code >= 400) return `HTTP ${row.status_code}`;
  return null;
}

function isResponseFailure(row: any) {
  return Boolean(
    row?.timed_out ||
      row?.error_msg ||
      (row?.status_code != null && Number(row.status_code) >= 400) ||
      payloadFailureMessages(row?.content).length,
  );
}

function identifyJobFromContent(content: string | null | undefined) {
  const payload = safeJsonParse(content);
  if (!payload || typeof payload !== "object") return null;
  if (payload.sync_type === "presence-worker") return "gingr-presence-sync";
  if (payload.sync_type === "presence-sync") return "gingr-presence-sync";
  if (payload.sync_type === "tv-poll") return "gingr-tv-poll";
  if (payload.sync_type === "today-sync") return "gingr-today-sync";
  if (payload.sync_type === "incremental") return "gingr-incremental-sync";
  if (payload.computed && payload.date) return "ops-compute-poll";
  if (payload.checking_in_count != null || payload.checking_out_count != null) return "gingr-boh-poll-a";
  if (payload.refreshed_at && payload.requested_location_id) return "gingr-today-notes-refresh";
  if (payload.date_range && payload.rows_upserted != null) return "compute-scheduling-matrix-cherry-hill-current-week";
  return null;
}

function inferJobFromRunTiming(row: any, runs: any[]) {
  const createdAt = new Date(row?.created || "").getTime();
  if (Number.isNaN(createdAt)) return null;
  const candidates = runs
    .map((run) => {
      const startTime = new Date(run.start_time || "").getTime();
      return {
        jobname: run.jobname,
        diffMs: Math.abs(createdAt - startTime),
        startedBeforeResponse: startTime <= createdAt + 50,
      };
    })
    .filter((entry) => entry.startedBeforeResponse && entry.diffMs <= 2000)
    .sort((a, b) => a.diffMs - b.diffMs);
  return candidates[0]?.jobname || null;
}

function deriveReportTotal(key: string, computedItems: any) {
  if (!computedItems || typeof computedItems !== "object") return null;
  if (key === "bathing") return Array.isArray(computedItems.dogs) ? computedItems.dogs.length : null;
  if (key === "room_cleaning") {
    const taskSummary = computedItems.task_summary || {};
    const summaryTotal = Number(taskSummary.total_tasks ?? computedItems.summary?.totalTasks);
    if (Number.isFinite(summaryTotal)) return summaryTotal;
    if (Array.isArray(computedItems.task_instances)) return computedItems.task_instances.length;
    if (Array.isArray(computedItems.rooms)) return computedItems.rooms.length;
  }
  if (key === "room_occupancy") {
    const summaryTotal = Number(computedItems.summary?.totalRooms);
    if (Number.isFinite(summaryTotal)) return summaryTotal;
    if (Array.isArray(computedItems.rooms)) return computedItems.rooms.length;
  }
  return null;
}

function numericValue(value: unknown): number | null {
  if (value == null || value === "") return null;
  const number = Number(value);
  return Number.isFinite(number) ? number : null;
}

function addDaysStr(dateStr: string, days: number) {
  const date = new Date(`${dateStr}T12:00:00`);
  date.setDate(date.getDate() + days);
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
}

function sumMetricValues(values: Array<number | null>) {
  return values.reduce((sum, value) => sum + (value ?? 0), 0);
}

function projectionDisplayIssues(row: any) {
  const projection = row?.detail_json?.projection;
  const display = projection?.display;
  if (projection?.state !== "projected" || !display) return [];

  const currentDisplay = row?.detail_json?.display || {};
  const explanations = projection?.explanations || {};
  const opening = display.opening || {};
  const closing = display.closing || {};
  const daycare = display.daycare || {};
  const support = display.support || {};
  const playYard = display.play_yard || {};
  const issues: any[] = [];

  const directMetrics = [
    {
      field: "projection.opening.total_boarding",
      explanationKey: "opening_total_boarding",
      current: currentDisplay.opening?.total_boarding,
      projected: opening.total_boarding,
    },
    {
      field: "projection.closing.total_boarding",
      explanationKey: "closing_total_boarding",
      current: currentDisplay.closing?.total_boarding,
      projected: closing.total_boarding,
    },
    {
      field: "projection.daycare.total_daycare",
      explanationKey: "daycare_total_daycare",
      current: currentDisplay.daycare?.total_daycare,
      projected: daycare.total_daycare,
    },
    {
      field: "projection.support.departure_baths",
      explanationKey: "support_departure_baths",
      current: currentDisplay.support?.departure_baths,
      projected: support.departure_baths,
    },
    {
      field: "projection.support.total_dog_volume",
      explanationKey: "support_total_dog_volume",
      current: currentDisplay.support?.total_dog_volume,
      projected: support.total_dog_volume,
    },
  ];

  for (const metric of directMetrics) {
    const explanation = explanations[metric.explanationKey] || {};
    const current = numericValue(metric.current);
    const projected = numericValue(metric.projected);
    const explanationCurrent = numericValue(explanation.current_value);
    const explanationProjected = numericValue(explanation.projected_value);

    if (current != null && explanationCurrent != null && explanationCurrent !== current) {
      issues.push({
        date: row.matrix_date,
        field: `${metric.field}.current_value`,
        actual: explanationCurrent,
        expected: current,
      });
    }
    if (projected != null && explanationProjected != null && explanationProjected !== projected) {
      issues.push({
        date: row.matrix_date,
        field: `${metric.field}.projected_value`,
        actual: projected,
        expected: explanationProjected,
      });
    }
    if (current != null && projected != null && projected < current) {
      issues.push({
        date: row.matrix_date,
        field: metric.field,
        actual: projected,
        expected: `>= ${current}`,
      });
    }
  }

  const expectedPlayYard: Record<string, number> = {
    "projection.play_yard.large_play_dogs": Math.max(
      numericValue(opening.large_boarding) ?? 0,
      numericValue(closing.large_boarding) ?? 0,
    ) + (numericValue(daycare.large_daycare) ?? 0),
    "projection.play_yard.small_play_dogs": Math.max(
      numericValue(opening.small_boarding) ?? 0,
      numericValue(closing.small_boarding) ?? 0,
    ) + (numericValue(daycare.small_daycare) ?? 0),
    "projection.play_yard.private_play_dogs": Math.max(
      numericValue(opening.private_play_boarding) ?? 0,
      numericValue(closing.private_play_boarding) ?? 0,
    ) + (numericValue(daycare.private_play_dayboarding) ?? 0),
    "projection.play_yard.split_play_dogs": Math.max(
      numericValue(opening.half_and_half_boarding) ?? 0,
      numericValue(closing.half_and_half_boarding) ?? 0,
    ) + (numericValue(daycare.half_and_half_daytime) ?? 0),
  };

  const actualPlayYard: Record<string, number | null> = {
    "projection.play_yard.large_play_dogs": numericValue(playYard.large_play_dogs),
    "projection.play_yard.small_play_dogs": numericValue(playYard.small_play_dogs),
    "projection.play_yard.private_play_dogs": numericValue(playYard.private_play_dogs),
    "projection.play_yard.split_play_dogs": numericValue(playYard.split_play_dogs),
  };

  for (const [field, expected] of Object.entries(expectedPlayYard)) {
    const actual = actualPlayYard[field];
    if (actual != null && actual !== expected) {
      issues.push({
        date: row.matrix_date,
        field,
        actual,
        expected,
      });
    }
  }

  return issues;
}

async function execSql(sb: any, query: string, params: string[] = []) {
  const { data, error } = await sb.rpc("exec_sql", { query, params });
  if (error) throw error;
  return Array.isArray(data) ? data : [];
}

async function fetchLatestAndCount(
  sb: any,
  table: string,
  locationId: string,
  columns: string,
  orderColumn: string,
) {
  const [{ data: latestRow, error: latestError }, { count, error: countError }] = await Promise.all([
    sb.from(table).select(columns).eq("location_id", locationId).order(orderColumn, { ascending: false }).limit(1).maybeSingle(),
    sb.from(table).select("id", { count: "exact", head: true }).eq("location_id", locationId),
  ]);

  if (latestError) throw latestError;
  if (countError) throw countError;

  return {
    latest: latestRow || null,
    count: count ?? 0,
  };
}

async function fetchPresenceSyncHealth(sb: any, locationId: string) {
  const [{ data: latestRun, error: latestError }, { data: latestEvent, error: eventError }, { data: configRow, error: configError }] = await Promise.all([
    sb
      .from("facility_presence_sync_runs")
      .select("id, status, started_at, completed_at, duration_ms, current_count, arrivals_count, departures_count, duplicate_animals_count, errors")
      .eq("location_id", locationId)
      .order("started_at", { ascending: false })
      .limit(1)
      .maybeSingle(),
    sb
      .from("facility_presence_events")
      .select("event_key, event_type, computed_at, animal_name, animal_gingr_id")
      .eq("location_id", locationId)
      .order("computed_at", { ascending: false })
      .limit(1)
      .maybeSingle(),
    sb
      .from("lite_settings")
      .select("setting_value")
      .eq("location_id", locationId)
      .eq("setting_key", "presence_sync_config_v1")
      .maybeSingle(),
  ]);

  if (latestError) throw latestError;
  if (eventError) throw eventError;
  if (configError) throw configError;

  const intervalSeconds = presenceHealthInterval(configRow?.setting_value);
  const completedAge = ageSeconds(latestRun?.completed_at || null);
  const warnSeconds = (intervalSeconds * 3) + 5;
  const failSeconds = (intervalSeconds * 6) + 10;
  let status = freshnessStatus(completedAge == null ? null : completedAge / 60, warnSeconds / 60, failSeconds / 60);
  let message = latestRun?.completed_at
    ? `Last presence sync completed ${completedAge}s ago.`
    : "No completed presence sync run found.";

  if (latestRun?.status === "failed") {
    status = "critical";
    message = presenceRunErrorMessage(latestRun) || "Latest presence sync run failed.";
  } else if (latestRun?.status === "running" && ageSeconds(latestRun.started_at) != null && ageSeconds(latestRun.started_at)! > 120) {
    status = "critical";
    message = "Presence sync has been running for more than 2 minutes.";
  }

  return {
    status,
    message,
    interval_seconds: intervalSeconds,
    warn_seconds: warnSeconds,
    fail_seconds: failSeconds,
    latest_run: latestRun || null,
    latest_event: latestEvent || null,
    latest_completed_age_seconds: completedAge,
    config: configRow?.setting_value || null,
  };
}

async function fetchCountReconciliationHealth(sb: any, locationId: string, date: string) {
  const [matrixRes, rollCallRes] = await Promise.all([
    sb
      .from("scheduling_matrix_daily")
      .select("detail_json, computed_at")
      .eq("location_id", locationId)
      .eq("matrix_date", date)
      .maybeSingle(),
    sb
      .from("lite_daily_ops")
      .select("id, computed_items, computed_at, updated_at")
      .eq("location_id", locationId)
      .in("id", [
        `ops_roll_call_opening_${date}`,
        `ops_roll_call_closing_${date}`,
      ]),
  ]);

  if (matrixRes.error) throw matrixRes.error;
  if (rollCallRes.error) throw rollCallRes.error;

  const matrixDisplay = matrixRes.data?.detail_json?.display || {};
  const rollCallById = new Map((rollCallRes.data || []).map((row: any) => [row.id, row]));
  const openingRow: any = rollCallById.get(`ops_roll_call_opening_${date}`) || null;
  const closingRow: any = rollCallById.get(`ops_roll_call_closing_${date}`) || null;
  const openingMatrix = numericValue(matrixDisplay.opening?.total_boarding);
  const closingMatrix = numericValue(matrixDisplay.closing?.total_boarding);
  const openingRollCall = numericValue(openingRow?.computed_items?.summary?.totalDogs);
  const closingRollCall = numericValue(closingRow?.computed_items?.summary?.totalDogs);

  const checks = [
    {
      key: "opening_boarding",
      label: "Opening boarding",
      matrix_total: openingMatrix,
      roll_call_total: openingRollCall,
      status: openingMatrix == null || openingRollCall == null
        ? "warning"
        : openingMatrix === openingRollCall
          ? "healthy"
          : "critical",
    },
    {
      key: "closing_boarding",
      label: "Closing boarding",
      matrix_total: closingMatrix,
      roll_call_total: closingRollCall,
      status: closingMatrix == null || closingRollCall == null
        ? "warning"
        : closingMatrix === closingRollCall
          ? "healthy"
          : "critical",
    },
  ];

  const missingLabels = checks
    .filter((check) => check.matrix_total == null || check.roll_call_total == null)
    .map((check) => check.label);
  const mismatches = checks
    .filter((check) => check.status === "critical")
    .map((check) => `${check.label}: matrix ${check.matrix_total}, roll call ${check.roll_call_total}`);
  const status = worstStatus(checks.map((check) => check.status));
  const summary = mismatches.length
    ? mismatches.join("; ")
    : missingLabels.length
      ? `Missing count source for ${missingLabels.join(", ")}`
      : "Scheduling matrix and roll-call dog totals agree.";

  return {
    status,
    summary,
    date,
    matrix_computed_at: matrixRes.data?.computed_at || null,
    opening_roll_call_computed_at: openingRow?.computed_at || openingRow?.updated_at || null,
    closing_roll_call_computed_at: closingRow?.computed_at || closingRow?.updated_at || null,
    checks,
  };
}

async function fetchSchedulingMatrixHealth(sb: any, locationId: string, date: string) {
  const endDate = addDaysStr(date, 13);
  const { data, error } = await sb
    .from("scheduling_matrix_daily")
    .select("matrix_date, detail_json, computed_at")
    .eq("location_id", locationId)
    .gte("matrix_date", date)
    .lte("matrix_date", endDate)
    .order("matrix_date", { ascending: true });

  if (error) throw error;

  const rows = data || [];
  const projectionIssues = rows.flatMap(projectionDisplayIssues);
  const minimumExpectedDays = 7;
  const status = projectionIssues.length
    ? "critical"
    : rows.length < minimumExpectedDays
      ? "warning"
      : "healthy";
  const affectedDates = [...new Set(projectionIssues.map((issue: any) => issue.date))];
  const summary = projectionIssues.length
    ? `${projectionIssues.length} projected derived-total issue${projectionIssues.length === 1 ? "" : "s"} across ${affectedDates.join(", ")}`
    : rows.length < minimumExpectedDays
      ? `Only ${rows.length}/${minimumExpectedDays} upcoming scheduling matrix days found.`
      : `${rows.length} upcoming scheduling matrix day${rows.length === 1 ? "" : "s"} have internally consistent projected totals.`;

  return {
    status,
    summary,
    date_range: [date, endDate],
    row_count: rows.length,
    issues: projectionIssues,
    latest_computed_at: rows
      .map((row: any) => row.computed_at)
      .filter(Boolean)
      .sort()
      .at(-1) || null,
  };
}

async function fetchReportHealth(sb: any, locationId: string, date: string) {
  const ids = REPORT_CHECKS.map((check) => `${check.idPrefix}_${date}`);
  const { data, error } = await sb
    .from("lite_daily_ops")
    .select("id, type_sub, date, updated_at, computed_at, computed_items")
    .eq("location_id", locationId)
    .in("id", ids);

  if (error) throw error;

  const byId = new Map((data || []).map((row: any) => [row.id, row]));
  const reports = REPORT_CHECKS.map((check) => {
    const id = `${check.idPrefix}_${date}`;
    const row: any = byId.get(id) || null;
    const computedAt = row?.computed_at || null;
    const updatedAt = row?.updated_at || null;
    const freshestAt = computedAt || updatedAt;
    const age = ageMinutes(freshestAt);
    const status = row ? freshnessStatus(age, check.warnMinutes, check.failMinutes) : "critical";
    return {
      key: check.key,
      id,
      label: check.label,
      description: check.description,
      used_for: check.usedFor,
      status,
      age_minutes: age,
      updated_at: updatedAt,
      computed_at: computedAt,
      total: deriveReportTotal(check.key, row?.computed_items),
    };
  });

  return {
    status: worstStatus(reports.map((report) => report.status)),
    reports,
  };
}

async function fetchBohCacheHealth(sb: any, locationId: string) {
  const { data, error } = await sb
    .from("gingr_back_of_house")
    .select("synced_at")
    .eq("location_id", locationId)
    .order("synced_at", { ascending: false })
    .limit(100);

  if (error) throw error;

  const latestSyncedAt = data?.[0]?.synced_at || null;
  const age = ageMinutes(latestSyncedAt);
  return {
    rows: data?.length || 0,
    latest_synced_at: latestSyncedAt,
    age_minutes: age,
    freshness_status: latestSyncedAt ? freshnessStatus(age, 3, 8) : "unknown",
  };
}

async function fetchCronHealth(sb: any) {
  const [liveJobs, recentRuns, recentResponses] = await Promise.all([
    execSql(
      sb,
      "select jobid::text, jobname, schedule, active, command from cron.job order by jobname",
    ),
    execSql(
      sb,
      [
        "select j.jobname, r.status, r.start_time::text, r.end_time::text, r.return_message",
        "from cron.job_run_details r",
        "join cron.job j on j.jobid = r.jobid",
        "where r.start_time >= now() - interval '45 minutes'",
        "order by r.start_time desc",
        "limit 200",
      ].join(" "),
    ),
    execSql(
      sb,
      [
        "select id::text, status_code, created::text, timed_out, error_msg, coalesce(content, '') as content",
        "from net._http_response",
        "where created >= now() - interval '45 minutes'",
        "order by id desc",
        "limit 250",
      ].join(" "),
    ),
  ]);

  const liveByName = new Map(liveJobs.map((job: any) => [job.jobname, job]));
  const runsByName = new Map<string, any[]>();
  for (const run of recentRuns) {
    if (!runsByName.has(run.jobname)) runsByName.set(run.jobname, []);
    runsByName.get(run.jobname)!.push(run);
  }

  const matchedResponses = recentResponses.map((row: any) => ({
    ...row,
    jobname: identifyJobFromContent(row.content) || inferJobFromRunTiming(row, recentRuns),
    error_summary: responseErrorSummary(row),
    payload_errors: payloadFailureMessages(row.content),
  }));

  const responsesByName = new Map<string, any[]>();
  for (const response of matchedResponses) {
    if (!response.jobname) continue;
    if (!responsesByName.has(response.jobname)) responsesByName.set(response.jobname, []);
    responsesByName.get(response.jobname)!.push(response);
  }

  const jobs = CRON_CHECKS.map((check) => {
    const live = liveByName.get(check.jobname);
    const runs = runsByName.get(check.jobname) || [];
    const responses = responsesByName.get(check.jobname) || [];
    const successes = responses.filter((row) => !isResponseFailure(row) && row.status_code >= 200 && row.status_code < 300);
    const failures = responses.filter((row) => isResponseFailure(row));
    const lastRun = runs[0] || null;
    const lastSuccess = successes[0] || null;
    const lastFailure = failures[0] || null;
    const lastSuccessAge = ageMinutes(lastSuccess?.created || null);
    const lastFailureAge = ageMinutes(lastFailure?.created || null);
    const lastSuccessTime = lastSuccess ? new Date(lastSuccess.created).getTime() : 0;
    const lastFailureTime = lastFailure ? new Date(lastFailure.created).getTime() : 0;
    const latestObservedFailure = lastFailure && (!lastSuccess || lastFailureTime > lastSuccessTime);
    const active = live?.active ?? false;
    const nextRunAt = nextRunFromCadence(lastRun?.start_time || lastSuccess?.created || null, check.cadenceMinutes, Boolean(live && active));

    let status = "healthy";
    let message = "Recent scheduled responses are healthy.";

    if (!live) {
      status = "critical";
      message = "Expected cron job is missing.";
    } else if (!live.active) {
      status = "critical";
      message = "Expected cron job is inactive.";
    } else if (lastRun && lastRun.status !== "succeeded") {
      status = "critical";
      message = `Cron run status is ${lastRun.status}.`;
    } else if (latestObservedFailure && lastFailureAge != null && lastFailureAge <= Math.max(check.cadenceMinutes * 3, 6)) {
      status = check.criticality;
      message = lastFailure.error_summary || `Recent HTTP ${lastFailure.status_code} response.`;
    } else if (!lastSuccess || lastSuccessAge == null || lastSuccessAge >= check.failMinutes) {
      status = check.criticality;
      message = lastSuccess
        ? `No successful HTTP response in ${lastSuccessAge} minutes.`
        : "No successful HTTP response found in the recent response window.";
    }

    return {
      jobname: check.jobname,
      label: check.label,
      function_name: check.functionName,
      sync_type: "syncType" in check ? check.syncType : null,
      description: check.description,
      used_for: check.usedFor,
      cadence_minutes: check.cadenceMinutes,
      cadence_label: cadenceLabel(check.cadenceMinutes),
      criticality: check.criticality,
      affects: check.affects,
      status,
      message,
      schedule: live?.schedule || null,
      active,
      next_run_at: nextRunAt,
      next_run_eta_minutes: etaMinutes(nextRunAt),
      last_run_at: lastRun?.start_time || null,
      last_run_status: lastRun?.status || null,
      last_success_at: lastSuccess?.created || null,
      last_success_age_minutes: lastSuccessAge,
      last_failure_at: lastFailure?.created || null,
      last_failure_status_code: lastFailure?.status_code ?? null,
      last_failure_message: lastFailure?.error_summary || null,
      recent_failure_count: failures.length,
    };
  });

  const unmatchedFailures = matchedResponses
    .filter((row: any) => !row.jobname && isResponseFailure(row))
    .slice(0, 5)
    .map((row: any) => ({
      id: row.id,
      created: row.created,
      status_code: row.status_code,
      message: row.error_summary || "Unmatched scheduled HTTP failure.",
    }));

  return {
    status: worstStatus(jobs.map((job: any) => job.status).concat(unmatchedFailures.length ? ["warning"] : [])),
    jobs,
    recent_unmatched_failures: unmatchedFailures,
    response_window_minutes: 45,
  };
}

async function fetchSupabaseStatus() {
  try {
    const response = await fetch("https://status.supabase.com/api/v2/status.json");
    if (!response.ok) {
      throw new Error(`Status page returned ${response.status}`);
    }
    const payload = await response.json();
    return {
      indicator: payload?.status?.indicator || "unknown",
      description: payload?.status?.description || "Unknown",
      page_url: "https://status.supabase.com/",
    };
  } catch (error: any) {
    return {
      indicator: "unknown",
      description: error?.message || "Unable to reach Supabase status page.",
      page_url: "https://status.supabase.com/",
    };
  }
}

function supabaseStatusHealth(indicator: string | null | undefined) {
  return ["none", "minor"].includes(String(indicator || "")) ? "healthy" : "warning";
}

function buildHealthFactors({
  cronHealth,
  reportHealth,
  countReconciliation,
  schedulingMatrix,
  freshness,
  syncState,
  bohCache,
  presenceHealth,
  supabaseStatus,
}: {
  cronHealth: any;
  reportHealth: any;
  countReconciliation: any;
  schedulingMatrix: any;
  freshness: any;
  syncState: any[];
  bohCache: any;
  presenceHealth: any;
  supabaseStatus: any;
}) {
  const jobs = cronHealth?.jobs || [];
  const reports = reportHealth?.reports || [];
  const erroredSync = (syncState || []).filter((row) => row.status === "error" && ALERT_SYNC_ERROR_ENTITIES.has(row.entity_type));
  const syncStatuses = (syncState || [])
    .filter((row) => ALERT_SYNC_ERROR_ENTITIES.has(row.entity_type))
    .map((row) => row.freshness_status || "unknown");
  const sourceSyncStatus = erroredSync.length ? "critical" : worstStatus(syncStatuses.length ? syncStatuses : ["healthy"]);
  const freshReports = reports.filter((report: any) => report.status === "healthy").length;
  const healthyJobs = jobs.filter((job: any) => job.status === "healthy").length;

  return [
    {
      key: "scheduled_edge_functions",
      label: "Scheduled Edge Functions",
      status: cronHealth?.status || "unknown",
      summary: `${healthyJobs}/${jobs.length} scheduled jobs healthy`,
      description: "Checks the pg_cron jobs that call Edge Functions and matches them to recent HTTP responses.",
      healthy_criteria: "Every expected job is active and has a recent successful HTTP response inside its freshness window.",
    },
    {
      key: "canonical_reports",
      label: "Canonical Report Freshness",
      status: reportHealth?.status || "unknown",
      summary: `${freshReports}/${reports.length} critical reports fresh`,
      description: "Checks today's lite_daily_ops report outputs for bathing, room cleaning and setups, and room occupancy.",
      healthy_criteria: "Each report has a current computed_at or updated_at timestamp and has not exceeded its warning/failure age.",
    },
    {
      key: "operational_count_reconciliation",
      label: "Roll Call / Matrix Counts",
      status: countReconciliation?.status || "unknown",
      summary: countReconciliation?.summary || "Roll-call and scheduling-matrix reconciliation unavailable.",
      description: "Compares Scheduling Matrix opening/closing boarding totals with the matching Opening and Closing Roll Call dog totals.",
      healthy_criteria: "Opening and closing boarding dog counts match across Scheduling Matrix and Roll Call for the same service date.",
    },
    {
      key: "scheduling_matrix_integrity",
      label: "Scheduling Matrix Integrity",
      status: schedulingMatrix?.status || "unknown",
      summary: schedulingMatrix?.summary || "Scheduling matrix integrity unavailable.",
      description: "Checks upcoming scheduling matrix rows for internally consistent projected totals before they are shown in Scheduling.",
      healthy_criteria: "Projected boarding totals, daycare totals, feeding counts, and total dog volume equal their component counts.",
    },
    {
      key: "source_sync_state",
      label: "Gingr Source Sync State",
      status: sourceSyncStatus,
      summary: erroredSync.length ? `${erroredSync.length} sync errors` : "No critical source sync errors",
      description: "Checks Gingr sync-state rows that feed same-day reservations, services, notes, and operational reports.",
      healthy_criteria: "Required sync entities are not in error and have a recent last_sync_at timestamp.",
    },
    {
      key: "boh_cache",
      label: "Back-of-House Cache",
      status: bohCache?.freshness_status || "unknown",
      summary: bohCache?.latest_synced_at ? `Latest BOH sync ${ageMinutes(bohCache.latest_synced_at) ?? "unknown"}m ago` : "No BOH cache timestamp",
      description: "Checks the freshness of the live back-of-house check-in/check-out cache.",
      healthy_criteria: "The cache has recent synced rows and has not exceeded its stale-data threshold.",
    },
    {
      key: "facility_presence",
      label: "Facility Presence",
      status: presenceHealth?.status || "unknown",
      summary: presenceHealth?.message || "Facility presence freshness unavailable.",
      description: "Checks the canonical current-presence reconciliation used by Checkout TV and live facility counts.",
      healthy_criteria: "A server-owned presence sync run has completed inside the cadence-specific freshness window.",
    },
    {
      key: "supabase_status",
      label: "Supabase Platform Status",
      status: supabaseStatusHealth(supabaseStatus?.indicator),
      summary: supabaseStatus?.description || "Supabase public status unavailable",
      description: "Checks Supabase's public status page for platform incidents that could affect database or Edge Function access.",
      healthy_criteria: "Supabase public status is none or minor.",
    },
  ];
}

async function requireAuthenticatedRequest(req: Request, sb: any, serviceRoleKey: string) {
  const authHeader = req.headers.get("Authorization") || "";
  const token = authHeader.replace(/^Bearer\s+/i, "").trim();

  if (!token) {
    return new Response(JSON.stringify({
      error: "Missing Authorization header.",
      generated_at: new Date().toISOString(),
      function_name: "ops-platform-health",
      overall_status: "critical",
      alerts: [{
        severity: "critical",
        kind: "auth",
        label: "Platform Health",
        function_name: "ops-platform-health",
        affects: ["Platform health details"],
        message: "ops-platform-health was called without an Authorization header.",
        action: "Sign in again before trusting platform-health freshness.",
      }],
    }), {
      status: 401,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  if (token === serviceRoleKey) return null;

  const { data, error } = await sb.auth.getUser(token);
  if (
    error?.message?.includes("missing sub claim")
    && hasServiceRoleJwtRole(token)
  ) {
    return null;
  }
  if (error || !data?.user) {
    return new Response(JSON.stringify({
      error: "Authentication required.",
      generated_at: new Date().toISOString(),
      function_name: "ops-platform-health",
      overall_status: "critical",
      alerts: [{
        severity: "critical",
        kind: "auth",
        label: "Platform Health",
        function_name: "ops-platform-health",
        affects: ["Platform health details"],
        message: `ops-platform-health could not validate the signed-in user: ${error?.message || "No user returned."}`,
        action: "Sign in again before trusting platform-health freshness.",
      }],
    }), {
      status: 401,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  return null;
}

function hasServiceRoleJwtRole(token: string) {
  const payloadSegment = token.split(".")[1];
  if (!payloadSegment) return false;
  try {
    const paddedPayload = payloadSegment
      .replace(/-/g, "+")
      .replace(/_/g, "/")
      .padEnd(Math.ceil(payloadSegment.length / 4) * 4, "=");
    const payload = JSON.parse(atob(paddedPayload));
    return payload?.role === "service_role";
  } catch {
    return false;
  }
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { location_id = "cherry-hill", date = nowEtDate() } = await req.json().catch(() => ({}));
    const requestedLocationId = String(location_id || "cherry-hill");
    const locationId = normalizeLocationId(requestedLocationId);
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const sb = createClient(
      Deno.env.get("SUPABASE_URL")!,
      serviceRoleKey,
    );
    const authFailure = await requireAuthenticatedRequest(req, sb, serviceRoleKey);
    if (authFailure) return authFailure;

    const todayNotesId = `ops_gingr_notes_${date}`;
    const [
      syncStateRes,
      ownersMetric,
      animalsMetric,
      reservationsMetric,
      latestOpsMetric,
      todayNotesMetric,
      reportHealth,
      countReconciliation,
      schedulingMatrix,
      bohCache,
      presenceHealth,
      cronHealthResult,
      supabaseStatus,
    ] = await Promise.all([
      sb.from("gingr_sync_state").select("*").eq("location_id", locationId).order("entity_type", { ascending: true }),
      fetchLatestAndCount(sb, "gingr_owners", locationId, "updated_at, synced_at, first_name, last_name", "updated_at"),
      fetchLatestAndCount(sb, "gingr_animals", locationId, "updated_at, synced_at, name", "updated_at"),
      fetchLatestAndCount(sb, "gingr_reservations", locationId, "updated_at, synced_at, animal_name, start_date, end_date", "updated_at"),
      sb.from("lite_daily_ops").select("id, type_sub, updated_at, computed_at, date").eq("location_id", locationId).order("updated_at", { ascending: false }).limit(1).maybeSingle(),
      sb.from("lite_daily_ops").select("id, updated_at, computed_at, date").eq("location_id", locationId).eq("id", todayNotesId).maybeSingle(),
      fetchReportHealth(sb, locationId, date),
      fetchCountReconciliationHealth(sb, locationId, date),
      fetchSchedulingMatrixHealth(sb, locationId, date),
      fetchBohCacheHealth(sb, locationId),
      fetchPresenceSyncHealth(sb, locationId),
      fetchCronHealth(sb).then((cronHealth) => ({ cronHealth })).catch((error: any) => ({ cronError: error?.message || "Failed to load cron health." })),
      fetchSupabaseStatus(),
    ]);

    if (syncStateRes.error) throw syncStateRes.error;
    if (latestOpsMetric.error) throw latestOpsMetric.error;
    if (todayNotesMetric.error) throw todayNotesMetric.error;

    const syncState = (syncStateRes.data || []).map((row: any) => {
      const age = ageMinutes(row.last_sync_at);
      return {
        entity_type: row.entity_type,
        status: row.status || "idle",
        records_synced: row.records_synced ?? 0,
        last_sync_at: row.last_sync_at || null,
        last_full_sync_at: row.last_full_sync_at || null,
        sync_duration_ms: row.sync_duration_ms ?? null,
        error_message: row.error_message || null,
        age_minutes: age,
        freshness_status: row.status === "error" ? "critical" : freshnessStatus(age, 45, 120),
      };
    });

    const latestDailyOpsAt = latestOpsMetric.data?.computed_at || latestOpsMetric.data?.updated_at || null;
    const todayNotesAt = todayNotesMetric.data?.computed_at || todayNotesMetric.data?.updated_at || null;
    const freshness = {
      owners: {
        count: ownersMetric.count,
        updated_at: ownersMetric.latest?.updated_at || null,
        synced_at: ownersMetric.latest?.synced_at || null,
        age_minutes: ageMinutes(ownersMetric.latest?.updated_at || ownersMetric.latest?.synced_at || null),
        freshness_status: freshnessStatus(ageMinutes(ownersMetric.latest?.updated_at || ownersMetric.latest?.synced_at || null), 60, 180),
      },
      animals: {
        count: animalsMetric.count,
        updated_at: animalsMetric.latest?.updated_at || null,
        synced_at: animalsMetric.latest?.synced_at || null,
        age_minutes: ageMinutes(animalsMetric.latest?.updated_at || animalsMetric.latest?.synced_at || null),
        freshness_status: freshnessStatus(ageMinutes(animalsMetric.latest?.updated_at || animalsMetric.latest?.synced_at || null), 60, 180),
      },
      reservations: {
        count: reservationsMetric.count,
        updated_at: reservationsMetric.latest?.updated_at || null,
        synced_at: reservationsMetric.latest?.synced_at || null,
        age_minutes: ageMinutes(reservationsMetric.latest?.updated_at || reservationsMetric.latest?.synced_at || null),
        freshness_status: freshnessStatus(ageMinutes(reservationsMetric.latest?.updated_at || reservationsMetric.latest?.synced_at || null), 20, 60),
      },
      daily_ops: {
        latest_id: latestOpsMetric.data?.id || null,
        latest_type_sub: latestOpsMetric.data?.type_sub || null,
        updated_at: latestOpsMetric.data?.updated_at || null,
        computed_at: latestOpsMetric.data?.computed_at || null,
        date: latestOpsMetric.data?.date || null,
        age_minutes: ageMinutes(latestDailyOpsAt),
        freshness_status: freshnessStatus(ageMinutes(latestDailyOpsAt), 45, 180),
      },
      gingr_notes_today: {
        id: todayNotesMetric.data?.id || null,
        updated_at: todayNotesMetric.data?.updated_at || null,
        computed_at: todayNotesMetric.data?.computed_at || null,
        date: todayNotesMetric.data?.date || date,
        age_minutes: ageMinutes(todayNotesAt),
        freshness_status: freshnessStatus(ageMinutes(todayNotesAt), 90, 240),
      },
    };

    const cronHealth = "cronHealth" in cronHealthResult
      ? cronHealthResult.cronHealth
      : {
          status: "warning",
          jobs: [],
          recent_unmatched_failures: [],
          response_window_minutes: 45,
          error: cronHealthResult.cronError,
        };

    const alerts: HealthAlert[] = [];
    for (const job of cronHealth.jobs || []) {
      if (job.status === "critical" || job.status === "warning") {
        alerts.push({
          severity: job.status,
          kind: "cron_job",
          label: job.label,
          jobname: job.jobname,
          function_name: job.function_name,
          affects: job.affects || [],
          last_run_at: job.last_run_at || null,
          last_run_status: job.last_run_status || null,
          last_success_at: job.last_success_at || null,
          last_failure_at: job.last_failure_at || null,
          last_failure_status_code: job.last_failure_status_code ?? null,
          age_minutes: job.last_success_age_minutes ?? null,
          message: `${job.label} (${job.function_name}) is ${job.status}: ${job.message}`,
          action: `Affected: ${(job.affects || []).join(", ") || "Unknown operational surfaces"}.`,
        });
      }
    }
    if (cronHealth.error) {
      alerts.push({
        severity: "warning",
        kind: "cron_health",
        label: "Cron health check",
        function_name: "ops-platform-health",
        affects: ["Platform health details"],
        message: `Cron HTTP health could not be checked: ${cronHealth.error}`,
        action: "Open Test Health for the raw cron-health payload.",
      });
    }
    if (presenceHealth.status === "critical" || presenceHealth.status === "warning") {
      alerts.push({
        severity: presenceHealth.status,
        kind: "presence_sync_freshness",
        label: "Facility Presence",
        function_name: "gingr-sync",
        affects: ["Checkout TV transitions", "Live checked-in dogs", "Dashboard facility status"],
        last_run_at: presenceHealth.latest_run?.started_at || null,
        last_success_at: presenceHealth.latest_run?.completed_at || null,
        age_minutes: presenceHealth.latest_completed_age_seconds == null ? null : Math.round(presenceHealth.latest_completed_age_seconds / 60),
        message: `Facility presence is ${presenceHealth.status}: ${presenceHealth.message}`,
        action: "Verify the Gingr Presence Worker cron, the sync lock state, and the latest facility_presence_sync_runs rows before trusting live dog counts.",
      });
    }
    for (const row of syncState) {
      if (row.status === "error" && ALERT_SYNC_ERROR_ENTITIES.has(row.entity_type)) {
        alerts.push({
          severity: "critical",
          kind: "sync_state",
          label: row.entity_type,
          key: row.entity_type,
          affects: SYNC_ENTITY_AFFECTS[row.entity_type] || ["Gingr-backed reports"],
          last_run_at: row.last_sync_at || null,
          age_minutes: row.age_minutes ?? null,
          message: `${row.entity_type} sync is in error: ${row.error_message || "No error text returned."}`,
          action: "Data depending on this sync may be incomplete until the sync succeeds.",
        });
      }
    }

    for (const report of reportHealth.reports) {
      if (report.status === "critical") {
        alerts.push({
          severity: "critical",
          kind: "report_freshness",
          label: report.label,
          key: report.key,
          report_id: report.id,
          affects: [report.label],
          age_minutes: report.age_minutes,
          computed_at: report.computed_at,
          updated_at: report.updated_at,
          message: `${report.label} is missing or stale for ${date}.`,
          action: "The listed report may be incomplete or stale until ops-compute refreshes it.",
        });
      } else if (report.status === "warning") {
        alerts.push({
          severity: "warning",
          kind: "report_freshness",
          label: report.label,
          key: report.key,
          report_id: report.id,
          affects: [report.label],
          age_minutes: report.age_minutes,
          computed_at: report.computed_at,
          updated_at: report.updated_at,
          message: `${report.label} has not refreshed in ${report.age_minutes} minutes.`,
          action: "Use the last refreshed timestamp before trusting today's count.",
        });
      }
    }

    if (countReconciliation?.status && countReconciliation.status !== "healthy") {
      alerts.push({
        severity: countReconciliation.status === "critical" ? "critical" : "warning",
        kind: "count_reconciliation",
        label: "Roll Call / Matrix Counts",
        key: "roll_call_matrix_counts",
        affects: ["Opening Roll Call", "Closing Roll Call", "Scheduling matrix"],
        message: countReconciliation.summary || "Roll-call and scheduling-matrix counts could not be reconciled.",
        action: "Audit Gingr reservation check-in/check-out state, room assignment coverage, and recompute roll call plus scheduling matrix before trusting staffing counts.",
      });
    }

    if (schedulingMatrix?.status && schedulingMatrix.status !== "healthy") {
      alerts.push({
        severity: schedulingMatrix.status === "critical" ? "critical" : "warning",
        kind: "scheduling_matrix_integrity",
        label: "Scheduling Matrix Integrity",
        key: "scheduling_matrix_integrity",
        affects: ["Scheduling matrix", "Projected staffing demand"],
        computed_at: schedulingMatrix.latest_computed_at,
        message: schedulingMatrix.summary || "Scheduling matrix projected totals could not be validated.",
        action: "Recompute the scheduling matrix before trusting projected staffing counts.",
      });
    }

    if (freshness.gingr_notes_today.freshness_status === "critical") {
      alerts.push({
        severity: "warning",
        kind: "report_freshness",
        label: "Gingr Notes",
        key: "gingr_notes_today",
        report_id: freshness.gingr_notes_today.id,
        affects: ["Checkout notes"],
        age_minutes: freshness.gingr_notes_today.age_minutes,
        computed_at: freshness.gingr_notes_today.computed_at,
        updated_at: freshness.gingr_notes_today.updated_at,
        message: `Today's Gingr notes have not refreshed recently for ${date}.`,
        action: "Checkout notes may be stale until the notes refresh succeeds.",
      });
    }

    if (!["none", "minor"].includes(supabaseStatus.indicator)) {
      alerts.push({
        severity: "warning",
        kind: "supabase_status",
        label: "Supabase status",
        affects: ["Supabase-backed app features"],
        message: `Supabase status page is reporting ${supabaseStatus.description}.`,
        action: "Check the Supabase public status page for platform incidents.",
      });
    }

    const overall_status = alerts.some((alert) => alert.severity === "critical")
      ? "critical"
      : alerts.length > 0
        ? "warning"
        : "healthy";
    const generatedAt = new Date().toISOString();

    return new Response(JSON.stringify({
      generated_at: generatedAt,
      location_id: locationId,
      requested_location_id: requestedLocationId,
      today: date,
      overall_status,
      alerts,
      health_factors: buildHealthFactors({
        cronHealth,
        reportHealth,
        countReconciliation,
        schedulingMatrix,
        freshness,
        syncState,
        bohCache,
        presenceHealth,
        supabaseStatus,
      }),
      self_check: {
        function_name: "ops-platform-health",
        label: "Platform Health",
        description: "Builds this health payload for the dashboard health button and health detail views.",
        used_for: ["Dashboard health button", "Platform health modal", "Test Health"],
        cadence_label: "Dashboard load and every 60 seconds while the dashboard is open",
        last_run_at: generatedAt,
        next_run_at: null,
        status: overall_status,
      },
      supabase_status: supabaseStatus,
      sync_state: syncState,
      freshness,
      reports: reportHealth,
      count_reconciliation: countReconciliation,
      scheduling_matrix: schedulingMatrix,
      cron_health: cronHealth,
      boh_cache: bohCache,
      presence_sync: presenceHealth,
      pitr: {
        status: "manual-check-required",
        note: "PITR is configured at the Supabase project level. This app can monitor data freshness and Supabase public status, but it cannot confirm restore points without separate management credentials.",
      },
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error: any) {
    console.error("ops-platform-health error:", error);
    const message = error?.message || "Failed to load platform health.";
    return new Response(JSON.stringify({
      error: message,
      generated_at: new Date().toISOString(),
      function_name: "ops-platform-health",
      overall_status: "critical",
      alerts: [{
        severity: "critical",
        kind: "edge_function",
        label: "Platform Health",
        function_name: "ops-platform-health",
        affects: ["Platform health details", "Data freshness visibility"],
        message: `ops-platform-health failed: ${message}`,
        action: "The app cannot verify report freshness until this function succeeds.",
      }],
    }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
