#!/usr/bin/env bash
#
# Purge sensitive data from the FULL git history while PRESERVING every commit and
# the commit graph (git filter-repo rewrites blobs/paths in place — your "N commits"
# stay N commits; only the sensitive content is stripped).
#
# It (1) deletes sensitive FILES from all history and (2) redacts PII strings inside
# files we keep. By DEFAULT it runs as a DRY RUN on a throwaway mirror clone (no push).
# Pass --push to force-push the rewritten history to origin.
#
#   Dry run (safe, verifies):   bash scripts/purge-git-history.sh
#   Publish (DESTRUCTIVE):      bash scripts/purge-git-history.sh --push
#
# ⚠️  --push REWRITES ALL COMMIT SHAs and force-pushes every branch/tag. Open PRs are
#     affected, anyone with a clone must re-clone, and you should ROTATE any credential
#     that was ever committed (none were per docs/SECURITY_AUDIT.md, but rotate defensively).
set -euo pipefail

PUSH=0
[ "${1:-}" = "--push" ] && PUSH=1

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO_URL="$(git -C "$REPO_ROOT" remote get-url origin)"

run_fr() {
  if command -v git-filter-repo >/dev/null 2>&1; then git filter-repo "$@";
  elif [ -x "$HOME/.local/bin/git-filter-repo" ]; then "$HOME/.local/bin/git-filter-repo" "$@";
  else python3 -m git_filter_repo "$@"; fi
}

WORK="$(mktemp -d)"
MIRROR="$WORK/repo.git"
echo "→ Mirror-cloning (all branches/tags) into a throwaway dir…"
git clone --quiet --mirror "$REPO_URL" "$MIRROR"

# 1) Files/dirs to remove from ALL history (per docs/SECURITY_AUDIT.md §1).
cat > "$WORK/paths.txt" <<'EOF'
CherryHillReservations.json
inventory_items.json
src/ignite/samples/phone_call_real.html
src/ignite/samples/appointment_real.html
dist-temp
dist-old
supabase/.temp
audit
EOF

# 2) PII strings to redact inside files we KEEP (migration, legal copy, vendor note).
cat > "$WORK/replace.txt" <<'EOF'
zacknisbet@gmail.com==>zack.nisbet@k9operations.com
mike.williams@k9resorts.com==>facilities@example.com
Mike Williams==>Facilities Vendor
(623) 261-3294==>(555) 000-0000
regex:/Users/[A-Za-z0-9._-]+==>/<path>
regex:/home/[A-Za-z0-9._-]+==>/<path>
EOF
# Append the directory-migration real→fake map if present (gitignored; generated by
# scripts/redact-directory-pii.mjs). Without it, emails/phones below are still scrubbed.
if [ -f "$REPO_ROOT/scripts/.pii-redactions.txt" ]; then
  cat "$REPO_ROOT/scripts/.pii-redactions.txt" >> "$WORK/replace.txt"
  echo "→ Loaded $(wc -l < "$REPO_ROOT/scripts/.pii-redactions.txt") directory-migration redaction rules."
else
  echo "⚠  scripts/.pii-redactions.txt not found — run 'node scripts/redact-directory-pii.mjs' against the"
  echo "   original migration first to also scrub the directory names/slugs from history."
fi

BEFORE="$(git -C "$MIRROR" rev-list --all --count)"
echo "→ Commits before: $BEFORE"

git -C "$MIRROR" filter-repo --version >/dev/null 2>&1 || true
# --prune-empty=never keeps every commit (even ones emptied by the purge) so the
# commit count / graph is preserved exactly.
( cd "$MIRROR" && run_fr --force --prune-empty=never --invert-paths --paths-from-file "$WORK/paths.txt" --replace-text "$WORK/replace.txt" )

AFTER="$(git -C "$MIRROR" rev-list --all --count)"
echo "→ Commits after:  $AFTER   (preserved: $([ "$BEFORE" = "$AFTER" ] && echo yes || echo "NO — investigate"))"

echo "→ Verifying sensitive files are gone from history:"
for p in CherryHillReservations.json src/ignite/samples/phone_call_real.html inventory_items.json; do
  if git -C "$MIRROR" log --all --oneline -- "$p" 2>/dev/null | grep -q .; then
    echo "   ✗ STILL PRESENT: $p"
  else
    echo "   ✓ removed: $p"
  fi
done

if [ "$PUSH" = "1" ]; then
  echo "→ Force-pushing rewritten history to origin (ALL refs)…"
  git -C "$MIRROR" push --force --mirror "$REPO_URL"
  echo "✅ History rewritten + pushed. Tell collaborators to re-clone. Rotate credentials defensively."
else
  echo
  echo "✅ DRY RUN complete (nothing pushed). Rewritten mirror: $MIRROR"
  echo "   Re-run with --push to publish, or inspect the mirror first."
fi
