// © 2026 K9 Operations LLC. All Rights Reserved.
// Proprietary and Confidential.

import React, { useState, useEffect, useRef, useMemo } from 'react';

// ─── Light Theme Colors ────────────────────────────────────────────────────────
const C = {
  bg: '#FAFBFC',
  bgAlt: '#F0F2F5',
  surface: '#FFFFFF',
  surfaceAlt: '#F7F8FA',
  border: '#E2E6ED',
  borderLight: '#EEF0F4',
  text: '#1A1F2E',
  textSec: '#5A6478',
  textMut: '#8B95A8',
  gold: '#AF8D54',
  goldLight: '#C4A46A',
  goldDark: '#8B6F3C',
  navy: '#003462',
  navyLight: '#0A4D8A',
  navyDeep: '#001D3D',
  accent: '#0EA5E9',
  accentLight: '#E0F2FE',
  success: '#10B981',
  successLight: '#D1FAE5',
};

// ─── Legal Data ───────────────────────────────────────────────────────────────
const TOS_SECTIONS = [
  { t: "1. Definitions", b: "\"Company\" refers to K9 Operations LLC, a New Jersey limited liability company. \"Service\" refers to the K9 Operations cloud-based software platform. \"Customer\" refers to the pet care facility or business entity that subscribes. \"User\" refers to any individual who accesses the Service. \"Customer Data\" refers to all data uploaded or generated by Users through the Service." },
  { t: "2. Description of Service", b: "K9 Operations provides a cloud-based SaaS platform for pet care facility management, including pet profile management, booking and scheduling, feeding and medication tracking, report cards, employee scheduling, and invoicing." },
  { t: "3. Account Registration and Security", b: "Customers must create an account and designate at least one administrator. You are responsible for providing accurate registration information, managing user accounts and access levels, maintaining the confidentiality of login credentials, and all activities that occur under your account." },
  { t: "4. Permitted Use and Restrictions", b: "You receive a limited, non-exclusive, non-transferable right to use the Service for your pet care facility operations. You may not copy, modify, distribute, sell, reverse engineer, scrape, or attempt unauthorized access to the Service." },
  { t: "5. Intellectual Property", b: "The Service is the exclusive property of K9 Operations LLC, protected by U.S. copyright and trademark laws. Copyright Registration filed February 9, 2026. All rights not expressly granted are reserved." },
  { t: "6. Customer Data", b: "You retain ownership of your Customer Data. You grant K9 Operations a limited license to host, store, and process your data solely to provide the Service. We will not access or disclose your data except as necessary to provide the Service or as required by law." },
  { t: "7. Service Availability", b: "We target 99.9% monthly uptime, excluding scheduled maintenance. Scheduled maintenance will be communicated at least 48 hours in advance when practicable." },
  { t: "8. Fees and Payment", b: "Access requires a paid subscription. Pricing and terms are established in your SaaS License Agreement. We may modify pricing with at least 60 days written notice." },
  { t: "9. Term and Termination", b: "Upon termination, you have 30 days to request a data export (CSV or JSON). After 30 days, Customer Data may be deleted. Outstanding fees remain due." },
  { t: "10. Disclaimers and Limitation of Liability", b: "THE SERVICE IS PROVIDED \"AS IS\" WITHOUT WARRANTIES. We make no representations regarding pet health outcomes. Our total aggregate liability shall not exceed fees paid in the preceding 12 months." },
  { t: "11. Indemnification", b: "You agree to indemnify K9 Operations LLC against claims arising from your use of the Service, violation of these Terms, or your operation of a pet care facility." },
  { t: "12. Governing Law", b: "These Terms are governed by New Jersey law. Disputes shall be resolved in Burlington County, NJ courts." },
  { t: "13. Changes to Terms", b: "We will provide at least 30 days notice for material changes. Continued use constitutes acceptance of modified Terms." },
  { t: "14. Contact", b: "Questions? Contact us at zacknisbet@gmail.com" },
];

const PRIVACY_SECTIONS = [
  { t: "1. Information We Collect", b: "We collect account information (business name, contact details, employee info), pet and client data (pet profiles, vaccination records, medical notes, emergency contacts), booking and service data (reservations, feeding logs, report cards, invoices), employee data (names, roles, schedules), usage data (IP address, browser type, pages viewed), and session cookies for authentication." },
  { t: "2. How We Use Your Information", b: "We use your information to provide and operate the Service, communicate with you, improve the platform, ensure security, and comply with legal obligations. We do not use Customer Data to train machine learning models." },
  { t: "3. How We Share Your Information", b: "We do not sell, rent, or trade your personal information. We share data only with service providers (Supabase for database hosting, Vercel for application hosting, payment processors), when required by law, or in connection with a business transfer." },
  { t: "4. Data Security", b: "All data is encrypted at rest (AES-256) and in transit (TLS 1.2+). We use role-based access controls and hashed passwords. We do not store credit card numbers or sensitive payment credentials." },
  { t: "5. Data Retention", b: "We retain data while your account is active. After termination, you have 30 days to export your data. Customer Data is deleted within 90 days of the export period, unless retention is required by law." },
  { t: "6. Your Rights", b: "You may request access to, correction of, or deletion of your personal information. You may request data export in CSV or JSON format. You may opt out of marketing communications at any time. Contact zacknisbet@gmail.com to exercise these rights." },
  { t: "7. Children's Privacy", b: "The Service is not directed to children under 13. We do not knowingly collect personal information from children under 13." },
  { t: "8. Changes to This Policy", b: "We will notify you of material changes via email or in-app notification. Changes become effective 30 days after posting unless stated otherwise." },
  { t: "9. Contact", b: "For privacy inquiries: zacknisbet@gmail.com" },
];

// ─── SVG Icons (inline) ───────────────────────────────────────────────────────
const Icon = ({ name, size = 24, color = 'currentColor' }) => {
  const icons = {
    lifecycle: <><circle cx="12" cy="12" r="9" fill="none" stroke={color} strokeWidth="1.5"/><path d="M12 3c5 0 9 4 9 9" fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round"/><path d="M21 12c0 5-4 9-9 9" fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round" strokeDasharray="3 2"/><circle cx="12" cy="12" r="3" fill={color} opacity="0.2"/><circle cx="12" cy="12" r="1.5" fill={color}/></>,
    ops: <><rect x="3" y="3" width="18" height="18" rx="3" fill="none" stroke={color} strokeWidth="1.5"/><path d="M8 9.5h8M8 12.5h6M8 15.5h4" stroke={color} strokeWidth="1.5" strokeLinecap="round"/><circle cx="5.5" cy="9.5" r="0.75" fill={color}/><circle cx="5.5" cy="12.5" r="0.75" fill={color}/><circle cx="5.5" cy="15.5" r="0.75" fill={color}/></>,
    tv: <><rect x="2" y="4" width="20" height="14" rx="2" fill="none" stroke={color} strokeWidth="1.5"/><path d="M8 21h8M12 18v3" stroke={color} strokeWidth="1.5" strokeLinecap="round"/><circle cx="8" cy="11" r="2" fill={color} opacity="0.15"/><circle cx="12" cy="11" r="2" fill={color} opacity="0.15"/><circle cx="16" cy="11" r="2" fill={color} opacity="0.15"/></>,
    reports: <><rect x="3" y="3" width="18" height="18" rx="2" fill="none" stroke={color} strokeWidth="1.5"/><path d="M7 14v3M11 10v7M15 12v5M19 8v9" stroke={color} strokeWidth="2" strokeLinecap="round"/></>,
    funnel: <><path d="M3 4h18l-6 7v5l-6 3V11L3 4z" fill={color} opacity="0.1" stroke={color} strokeWidth="1.5" strokeLinejoin="round"/></>,
    shield: <><path d="M12 2l8 4v5c0 5.25-3.5 9.74-8 11-4.5-1.26-8-5.75-8-11V6l8-4z" fill={color} opacity="0.1" stroke={color} strokeWidth="1.5"/><path d="M9 12l2 2 4-4" fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
    arrow: <><path d="M5 12h14M13 6l6 6-6 6" fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
    check: <><path d="M5 12l5 5L20 7" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></>,
    star: <><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" fill={color} opacity="0.15" stroke={color} strokeWidth="1.5" strokeLinejoin="round"/></>,
    sync: <><path d="M4 12a8 8 0 0114.93-4M20 12a8 8 0 01-14.93 4" fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round"/><path d="M20 4v4h-4M4 20v-4h4" fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
    menu: <><path d="M4 6h16M4 12h16M4 18h16" stroke={color} strokeWidth="1.5" strokeLinecap="round"/></>,
    close: <><path d="M6 6l12 12M18 6L6 18" stroke={color} strokeWidth="1.5" strokeLinecap="round"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none">{icons[name]}</svg>;
};

// ─── K9 Logo (real dog silhouette from brand assets) ─────────────────────────
const K9Logo = ({ size = 36 }) => (
  <img src="/k9-logo.png" alt="K9 Operations" style={{ width: size, height: 'auto', objectFit: 'contain' }} />
);


// ═══════════════════════════════════════════════════════════════════════════════
// DATA FLOW ANIMATION — The Centerpiece
// Gingr (top) → K9 Operations (middle) → Old / Conversion / Retention (bottom)
// ═══════════════════════════════════════════════════════════════════════════════
function DataFlowAnimation() {
  const canvasRef = useRef(null);
  const animRef = useRef(null);
  const [isVisible, setIsVisible] = useState(false);
  const sectionRef = useRef(null);

  useEffect(() => {
    const obs = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) { setIsVisible(true); obs.disconnect(); }},
      { threshold: 0.2 }
    );
    if (sectionRef.current) obs.observe(sectionRef.current);
    return () => obs.disconnect();
  }, []);

  useEffect(() => {
    if (!isVisible || !canvasRef.current) return;
    const canvas = canvasRef.current;
    const ctx = canvas.getContext('2d');
    const dpr = window.devicePixelRatio || 1;

    const resize = () => {
      const rect = canvas.getBoundingClientRect();
      canvas.width = rect.width * dpr;
      canvas.height = rect.height * dpr;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    };
    resize();
    window.addEventListener('resize', resize);

    // Node positions (responsive)
    const getLayout = () => {
      const w = canvas.getBoundingClientRect().width;
      const h = canvas.getBoundingClientRect().height;
      const cx = w / 2;

      const gingrNode = { x: cx, y: 60, label: 'Gingr', sub: 'PMS Data Source', color: '#6366F1', radius: 44 };
      const k9Node = { x: cx, y: h * 0.42, label: 'K9 Ops', sub: 'Intelligence Layer', color: C.navy, radius: 50 };

      const spacing = Math.min(w * 0.28, 180);
      const bottomY = h * 0.82;
      const oldNode = { x: cx - spacing, y: bottomY, label: 'Cold', sub: 'Re-engagement', color: '#64748B', radius: 36 };
      const convNode = { x: cx, y: bottomY, label: 'Conversion', sub: 'New Leads', color: '#10B981', radius: 36 };
      const retNode = { x: cx + spacing, y: bottomY, label: 'Retention', sub: 'Lapsed Clients', color: '#F59E0B', radius: 36 };

      return { gingrNode, k9Node, oldNode, convNode, retNode, w, h };
    };

    // Orbs
    const orbs = [];
    let orbIdCounter = 0;

    const spawnOrb = (from, to, color, delay = 0) => {
      orbs.push({
        id: orbIdCounter++,
        fromX: from.x, fromY: from.y,
        toX: to.x, toY: to.y,
        progress: -delay,
        speed: 0.008 + Math.random() * 0.004,
        color,
        radius: 4 + Math.random() * 3,
        trail: [],
      });
    };

    let lastSpawnTime = 0;

    const draw = (time) => {
      const layout = getLayout();
      const { gingrNode, k9Node, oldNode, convNode, retNode, w, h } = layout;
      ctx.clearRect(0, 0, w, h);

      // Draw connection lines
      const drawLine = (from, to, alpha = 0.12) => {
        ctx.beginPath();
        const midY = (from.y + to.y) / 2;
        ctx.moveTo(from.x, from.y + from.radius);
        ctx.bezierCurveTo(from.x, midY, to.x, midY, to.x, to.y - to.radius);
        ctx.strokeStyle = `rgba(0,52,98,${alpha})`;
        ctx.lineWidth = 2;
        ctx.setLineDash([6, 4]);
        ctx.stroke();
        ctx.setLineDash([]);
      };

      drawLine(gingrNode, k9Node, 0.15);
      drawLine(k9Node, oldNode, 0.1);
      drawLine(k9Node, convNode, 0.1);
      drawLine(k9Node, retNode, 0.1);

      // Draw nodes
      const drawNode = (node) => {
        // Glow
        const grad = ctx.createRadialGradient(node.x, node.y, 0, node.x, node.y, node.radius * 2);
        grad.addColorStop(0, node.color + '18');
        grad.addColorStop(1, node.color + '00');
        ctx.beginPath();
        ctx.arc(node.x, node.y, node.radius * 2, 0, Math.PI * 2);
        ctx.fillStyle = grad;
        ctx.fill();

        // Circle
        ctx.beginPath();
        ctx.arc(node.x, node.y, node.radius, 0, Math.PI * 2);
        ctx.fillStyle = '#fff';
        ctx.fill();
        ctx.strokeStyle = node.color + '40';
        ctx.lineWidth = 2;
        ctx.stroke();

        // Inner circle
        ctx.beginPath();
        ctx.arc(node.x, node.y, node.radius * 0.6, 0, Math.PI * 2);
        ctx.fillStyle = node.color + '12';
        ctx.fill();

        // Label
        ctx.fillStyle = node.color;
        ctx.font = `700 ${node.radius > 40 ? 14 : 11}px 'GT Eesti', system-ui, sans-serif`;
        ctx.textAlign = 'center';
        ctx.fillText(node.label, node.x, node.y + (node.radius > 40 ? 5 : 4));

        // Sub-label
        ctx.fillStyle = C.textMut;
        ctx.font = `500 ${node.radius > 40 ? 11 : 9}px 'GT Eesti', system-ui, sans-serif`;
        ctx.fillText(node.sub, node.x, node.y + node.radius + 16);
      };

      drawNode(gingrNode);
      drawNode(k9Node);
      drawNode(oldNode);
      drawNode(convNode);
      drawNode(retNode);

      // Spawn orbs periodically
      if (time - lastSpawnTime > 1200) {
        lastSpawnTime = time;
        // Gingr → K9
        spawnOrb(gingrNode, k9Node, '#6366F1', 0);
        // K9 → bottom nodes (staggered)
        spawnOrb(k9Node, convNode, '#10B981', 0.35);
        spawnOrb(k9Node, retNode, '#F59E0B', 0.5);
        spawnOrb(k9Node, oldNode, '#64748B', 0.65);
      }

      // Update and draw orbs
      for (let i = orbs.length - 1; i >= 0; i--) {
        const orb = orbs[i];
        orb.progress += orb.speed;

        if (orb.progress < 0) continue;
        if (orb.progress > 1) { orbs.splice(i, 1); continue; }

        const t = orb.progress;
        const midY = (orb.fromY + orb.toY) / 2;
        // Bezier interpolation
        const mt = 1 - t;
        const x = mt*mt*mt*orb.fromX + 3*mt*mt*t*orb.fromX + 3*mt*t*t*orb.toX + t*t*t*orb.toX;
        const y = mt*mt*mt*orb.fromY + 3*mt*mt*t*midY + 3*mt*t*t*midY + t*t*t*orb.toY;

        // Trail
        orb.trail.push({ x, y, alpha: 1 });
        if (orb.trail.length > 12) orb.trail.shift();

        // Draw trail
        orb.trail.forEach((pt, idx) => {
          const a = (idx / orb.trail.length) * 0.4;
          ctx.beginPath();
          ctx.arc(pt.x, pt.y, orb.radius * (idx / orb.trail.length) * 0.7, 0, Math.PI * 2);
          ctx.fillStyle = orb.color + Math.round(a * 255).toString(16).padStart(2, '0');
          ctx.fill();
        });

        // Draw orb with glow
        const orbGrad = ctx.createRadialGradient(x, y, 0, x, y, orb.radius * 3);
        orbGrad.addColorStop(0, orb.color + '60');
        orbGrad.addColorStop(1, orb.color + '00');
        ctx.beginPath();
        ctx.arc(x, y, orb.radius * 3, 0, Math.PI * 2);
        ctx.fillStyle = orbGrad;
        ctx.fill();

        ctx.beginPath();
        ctx.arc(x, y, orb.radius, 0, Math.PI * 2);
        ctx.fillStyle = orb.color;
        ctx.fill();

        // White core
        ctx.beginPath();
        ctx.arc(x, y, orb.radius * 0.4, 0, Math.PI * 2);
        ctx.fillStyle = '#fff';
        ctx.fill();
      }

      animRef.current = requestAnimationFrame(draw);
    };

    animRef.current = requestAnimationFrame(draw);

    return () => {
      cancelAnimationFrame(animRef.current);
      window.removeEventListener('resize', resize);
    };
  }, [isVisible]);

  return (
    <div ref={sectionRef} style={{ position: 'relative', width: '100%', maxWidth: 600, margin: '0 auto' }}>
      <canvas
        ref={canvasRef}
        style={{ width: '100%', height: 420, display: 'block' }}
      />
    </div>
  );
}


// ═══════════════════════════════════════════════════════════════════════════════
// FEATURE SECTIONS
// ═══════════════════════════════════════════════════════════════════════════════

function FeatureSection({ icon, title, subtitle, description, bullets, reversed, accentColor }) {
  return (
    <div style={{
      display: 'flex', flexDirection: reversed ? 'row-reverse' : 'row',
      gap: 64, alignItems: 'center', padding: '80px 0',
      flexWrap: 'wrap',
    }}>
      {/* Text side */}
      <div style={{ flex: 1, minWidth: 320 }}>
        <div style={{
          display: 'inline-flex', alignItems: 'center', gap: 8,
          padding: '6px 14px', borderRadius: 100,
          background: accentColor + '10', marginBottom: 16,
        }}>
          <Icon name={icon} size={16} color={accentColor} />
          <span style={{ fontSize: 12, fontWeight: 700, color: accentColor, letterSpacing: '0.06em', textTransform: 'uppercase' }}>{subtitle}</span>
        </div>
        <h3 style={{ fontSize: 32, fontWeight: 800, color: C.text, lineHeight: 1.2, margin: '0 0 16px' }}>{title}</h3>
        <p style={{ fontSize: 17, color: C.textSec, lineHeight: 1.7, margin: '0 0 24px' }}>{description}</p>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {bullets.map((b, i) => (
            <div key={i} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
              <div style={{
                width: 22, height: 22, borderRadius: 6, flexShrink: 0, marginTop: 1,
                background: accentColor + '12',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}>
                <Icon name="check" size={13} color={accentColor} />
              </div>
              <span style={{ fontSize: 15, color: C.textSec, lineHeight: 1.5 }}>{b}</span>
            </div>
          ))}
        </div>
      </div>
      {/* Visual side — abstract graphic */}
      <div style={{
        flex: 1, minWidth: 320, minHeight: 340,
        background: `linear-gradient(135deg, ${accentColor}08 0%, ${accentColor}03 100%)`,
        borderRadius: 24, border: `1px solid ${accentColor}15`,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        position: 'relative', overflow: 'hidden',
      }}>
        <FeatureGraphic type={icon} color={accentColor} />
      </div>
    </div>
  );
}

// Abstract feature graphics (no fake screenshots)
function FeatureGraphic({ type, color }) {
  if (type === 'lifecycle') {
    // Triangle layout: Gingr feeds into K9 Ops (center of triangle)
    // Triangle vertices: Conversion (top), Active (bottom-right), Retention (bottom-left)
    // Flow: Gingr → K9 Ops → Conversion → Active ↔ Retention (no backflow to Conversion)
    return (
      <svg width="300" height="300" viewBox="0 0 300 300" fill="none">
        {/* Gingr node — outside triangle, top-left */}
        <g>
          <circle cx="60" cy="35" r="24" fill="#fff" stroke="#6366F1" strokeWidth="2"/>
          <circle cx="60" cy="35" r="16" fill="#6366F130"/>
          <text x="60" y="39" textAnchor="middle" fontSize="10" fontWeight="800" fill="#6366F1">Gingr</text>
        </g>

        {/* Arrow from Gingr to K9 Ops center */}
        <path d="M80 52 L135 108" stroke="#6366F1" strokeWidth="2" strokeDasharray="5 3" opacity="0.5" markerEnd="url(#arrowGingr)"/>
        <defs>
          <marker id="arrowGingr" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#6366F180"/>
          </marker>
          <marker id="arrowNav" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse">
            <path d="M 0 0 L 10 5 L 0 10 z" fill={color + '60'}/>
          </marker>
          <marker id="arrowBi" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="#F59E0B80"/>
          </marker>
        </defs>

        {/* Triangle outline (subtle) */}
        <path d="M150 80 L250 240 L50 240 Z" fill={color + '04'} stroke={color + '15'} strokeWidth="1.5" strokeDasharray="6 4"/>

        {/* K9 Ops center hub */}
        <circle cx="150" cy="175" r="32" fill="#fff" stroke={color} strokeWidth="2.5"/>
        <circle cx="150" cy="175" r="22" fill={color + '08'}/>
        <text x="150" y="172" textAnchor="middle" fontSize="10" fontWeight="800" fill={color}>K9 Ops</text>
        <text x="150" y="184" textAnchor="middle" fontSize="7" fontWeight="500" fill={color + '70'}>Intelligence</text>

        {/* Triangle vertex: Conversion (top) */}
        <g>
          <circle cx="150" cy="80" r="22" fill="#fff" stroke="#10B981" strokeWidth="2"/>
          <circle cx="150" cy="80" r="14" fill="#10B98115"/>
          <text x="150" y="77" textAnchor="middle" fontSize="7" fontWeight="700" fill="#10B981">CONVER-</text>
          <text x="150" y="87" textAnchor="middle" fontSize="7" fontWeight="700" fill="#10B981">SION</text>
        </g>

        {/* Triangle vertex: Active (bottom-right) */}
        <g>
          <circle cx="248" cy="240" r="22" fill="#fff" stroke={color} strokeWidth="2"/>
          <circle cx="248" cy="240" r="14" fill={color + '12'}/>
          <text x="248" y="244" textAnchor="middle" fontSize="8" fontWeight="700" fill={color}>ACTIVE</text>
        </g>

        {/* Triangle vertex: Retention (bottom-left) */}
        <g>
          <circle cx="52" cy="240" r="22" fill="#fff" stroke="#F59E0B" strokeWidth="2"/>
          <circle cx="52" cy="240" r="14" fill="#F59E0B15"/>
          <text x="52" y="237" textAnchor="middle" fontSize="7" fontWeight="700" fill="#F59E0B">RETEN-</text>
          <text x="52" y="247" textAnchor="middle" fontSize="7" fontWeight="700" fill="#F59E0B">TION</text>
        </g>

        {/* Flow arrows: K9 Ops → Conversion */}
        <line x1="150" y1="143" x2="150" y2="103" stroke={color + '40'} strokeWidth="1.5" markerEnd="url(#arrowNav)"/>

        {/* Conversion → Active (one-way down-right) */}
        <line x1="170" y1="92" x2="230" y2="224" stroke="#10B98150" strokeWidth="1.5" markerEnd="url(#arrowNav)"/>

        {/* Active ↔ Retention (bidirectional bottom) */}
        <line x1="226" y1="237" x2="78" y2="237" stroke={color + '40'} strokeWidth="1.5" markerEnd="url(#arrowBi)"/>
        <line x1="74" y1="245" x2="226" y2="245" stroke="#F59E0B50" strokeWidth="1.5" markerEnd="url(#arrowNav)"/>

        {/* Animated pulse on K9 Ops center */}
        <circle cx="150" cy="175" r="32" fill="none" stroke={color} strokeWidth="1" opacity="0.3">
          <animate attributeName="r" values="32;44;32" dur="3s" repeatCount="indefinite"/>
          <animate attributeName="opacity" values="0.3;0;0.3" dur="3s" repeatCount="indefinite"/>
        </circle>

        {/* Flow labels */}
        <text x="255" y="158" textAnchor="middle" fontSize="7" fontWeight="600" fill={color + '50'} transform="rotate(55 240 160)">one way</text>
        <text x="150" y="268" textAnchor="middle" fontSize="7" fontWeight="600" fill="#F59E0B80">← back &amp; forth →</text>
      </svg>
    );
  }

  if (type === 'ops') {
    return (
      <svg width="280" height="280" viewBox="0 0 280 280" fill="none">
        {/* Grid of checklist cards */}
        {[
          { x: 20, y: 20, w: 120, h: 70, label: 'Opening', pct: 100, c: '#10B981' },
          { x: 150, y: 20, w: 110, h: 70, label: 'Front-End', pct: 80, c: color },
          { x: 20, y: 100, w: 110, h: 70, label: 'Room Cleaning', pct: 60, c: '#F59E0B' },
          { x: 140, y: 100, w: 120, h: 70, label: 'Bathing', pct: 45, c: '#0EA5E9' },
          { x: 20, y: 180, w: 120, h: 70, label: 'Private Play', pct: 33, c: '#8B5CF6' },
          { x: 150, y: 180, w: 110, h: 70, label: 'Closing', pct: 0, c: '#64748B' },
        ].map((card, i) => (
          <g key={i}>
            <rect x={card.x} y={card.y} width={card.w} height={card.h} rx="12" fill="#fff" stroke={card.c + '30'} strokeWidth="1.5"/>
            <text x={card.x + 12} y={card.y + 24} fontSize="10" fontWeight="700" fill={C.text}>{card.label}</text>
            {/* Progress bar */}
            <rect x={card.x + 12} y={card.y + 36} width={card.w - 24} height="6" rx="3" fill={card.c + '15'}/>
            <rect x={card.x + 12} y={card.y + 36} width={(card.w - 24) * card.pct / 100} height="6" rx="3" fill={card.c}>
              <animate attributeName="width" from="0" to={(card.w - 24) * card.pct / 100} dur="1.5s" begin={`${i * 0.2}s`} fill="freeze"/>
            </rect>
            <text x={card.x + card.w - 12} y={card.y + 58} textAnchor="end" fontSize="9" fontWeight="600" fill={card.c}>{card.pct}%</text>
          </g>
        ))}
        {/* Daily Progress indicator */}
        <rect x="60" y="258" width="160" height="18" rx="9" fill={color + '10'}/>
        <text x="140" y="271" textAnchor="middle" fontSize="9" fontWeight="700" fill={color}>Daily Progress: 53%</text>
      </svg>
    );
  }

  if (type === 'tv') {
    return (
      <svg width="300" height="260" viewBox="0 0 300 260" fill="none">
        {/* Monitor frame */}
        <rect x="20" y="10" width="260" height="180" rx="12" fill="#001A33" stroke="#1E2A42" strokeWidth="2"/>
        <rect x="120" y="195" width="60" height="12" rx="2" fill="#1E2A42"/>
        <rect x="90" y="207" width="120" height="6" rx="3" fill="#1E2A42"/>

        {/* Header */}
        <text x="40" y="38" fontSize="11" fontWeight="800" fill="#fff">K9 Cherry Hill</text>
        <text x="40" y="50" fontSize="7" fontWeight="600" fill="#AF8D54" letterSpacing="1">CHECKOUT BOARD</text>
        <text x="260" y="38" textAnchor="end" fontSize="14" fontWeight="900" fill="#fff">2:45 PM</text>

        {/* Dog cards */}
        {['Luna','Max','Bella','Rocky','Daisy','Cooper','Sadie','Duke'].map((name, i) => {
          const col = i % 4;
          const row = Math.floor(i / 4);
          const x = 35 + col * 58;
          const y = 65 + row * 62;
          const colors = ['#0EA5E9', '#AF8D54', '#10B981', '#F59E0B', '#8B5CF6', '#EC4899', '#6366F1', '#14B8A6'];
          return (
            <g key={i}>
              <rect x={x} y={y} width="50" height="52" rx="8" fill="rgba(255,255,255,0.06)" stroke="rgba(255,255,255,0.08)" strokeWidth="1"/>
              <circle cx={x + 25} cy={y + 18} r="10" fill={colors[i] + '30'}/>
              <text x={x + 25} y={y + 22} textAnchor="middle" fontSize="10" fontWeight="800" fill={colors[i]}>{name[0]}</text>
              <text x={x + 25} y={y + 38} textAnchor="middle" fontSize="7" fontWeight="700" fill="#fff">{name}</text>
              <text x={x + 25} y={y + 47} textAnchor="middle" fontSize="5.5" fill="rgba(255,255,255,0.4)">Rm {i + 1}</text>
            </g>
          );
        })}
      </svg>
    );
  }

  if (type === 'reports') {
    return (
      <svg width="280" height="260" viewBox="0 0 280 260" fill="none">
        {/* NLP query bar */}
        <rect x="20" y="15" width="240" height="36" rx="18" fill="#fff" stroke={color + '30'} strokeWidth="1.5"/>
        <text x="40" y="37" fontSize="10" fill={C.textMut}>"Revenue by suite type"</text>
        <circle cx="240" cy="33" r="12" fill={color + '15'}/>
        <path d="M236 30l4 3-4 3" fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round"/>

        {/* Chart area */}
        <rect x="20" y="65" width="240" height="140" rx="12" fill="#fff" stroke="#E2E6ED" strokeWidth="1"/>
        {/* Bars */}
        {[
          { x: 50, h: 90, label: 'Standard', c: '#0EA5E9' },
          { x: 100, h: 110, label: 'Deluxe', c: color },
          { x: 150, h: 70, label: 'Luxury', c: '#AF8D54' },
          { x: 200, h: 50, label: 'VIP', c: '#8B5CF6' },
        ].map((bar, i) => (
          <g key={i}>
            <rect x={bar.x} y={195 - bar.h} width="30" height={bar.h} rx="4" fill={bar.c + '20'} stroke={bar.c} strokeWidth="1">
              <animate attributeName="height" from="0" to={bar.h} dur="1s" begin={`${i * 0.15}s`} fill="freeze"/>
              <animate attributeName="y" from="195" to={195 - bar.h} dur="1s" begin={`${i * 0.15}s`} fill="freeze"/>
            </rect>
            <text x={bar.x + 15} y="210" textAnchor="middle" fontSize="8" fontWeight="600" fill={C.textSec}>{bar.label}</text>
          </g>
        ))}

        {/* Suggestion chips */}
        {['Top 10 clients', 'MoM growth', 'RevPAR'].map((chip, i) => (
          <g key={i}>
            <rect x={20 + i * 85} y="225" width="78" height="24" rx="12" fill={color + '08'} stroke={color + '20'} strokeWidth="1"/>
            <text x={59 + i * 85} y="241" textAnchor="middle" fontSize="8" fontWeight="600" fill={color}>{chip}</text>
          </g>
        ))}
      </svg>
    );
  }

  return null;
}


// ═══════════════════════════════════════════════════════════════════════════════
// MAIN LANDING PAGE
// ═══════════════════════════════════════════════════════════════════════════════
export default function LandingPage() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [legalModal, setLegalModal] = useState(null); // 'tos' | 'privacy'
  const [scrollY, setScrollY] = useState(0);

  useEffect(() => {
    const handler = () => setScrollY(window.scrollY);
    window.addEventListener('scroll', handler, { passive: true });
    return () => window.removeEventListener('scroll', handler);
  }, []);

  const navStyle = {
    position: 'fixed', top: 0, left: 0, right: 0, zIndex: 100,
    background: scrollY > 20 ? 'rgba(255,255,255,0.95)' : 'transparent',
    backdropFilter: scrollY > 20 ? 'blur(20px)' : 'none',
    borderBottom: scrollY > 20 ? `1px solid ${C.border}` : '1px solid transparent',
    transition: 'all 0.3s ease',
  };

  const scrollTo = (id) => {
    setMobileMenuOpen(false);
    document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <div style={{ background: C.bg, color: C.text, fontFamily: "'GT Eesti', -apple-system, system-ui, sans-serif", minHeight: '100vh', overflowX: 'hidden' }}>

      {/* ─── NAVIGATION ─── */}
      <nav style={navStyle}>
        <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: 64 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <K9Logo size={32} />
            <div>
              <div style={{ fontSize: 15, fontWeight: 800, color: C.navy, lineHeight: 1.1, letterSpacing: '-0.02em' }}>K9 Operations</div>
              <div style={{ fontSize: 9, fontWeight: 600, color: C.textMut, letterSpacing: '0.08em', textTransform: 'uppercase' }}>Lite · KOL</div>
            </div>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 32 }} className="nav-links">
            {['Features', 'How It Works', 'Roadmap'].map(item => (
              <button key={item} onClick={() => scrollTo(item.toLowerCase().replace(/ /g, '-'))} style={{
                background: 'none', border: 'none', cursor: 'pointer', fontSize: 14, fontWeight: 600, color: C.textSec,
                padding: '4px 0', transition: 'color 0.2s',
              }} onMouseEnter={e => e.target.style.color = C.navy} onMouseLeave={e => e.target.style.color = C.textSec}>
                {item}
              </button>
            ))}
            <a href="/login" style={{
              padding: '8px 20px', borderRadius: 8, background: C.navy, color: '#fff',
              fontSize: 13, fontWeight: 700, textDecoration: 'none', transition: 'all 0.2s',
              border: 'none', cursor: 'pointer',
            }}>Sign In</a>
          </div>
          {/* Mobile menu button */}
          <button onClick={() => setMobileMenuOpen(!mobileMenuOpen)} style={{
            display: 'none', background: 'none', border: 'none', cursor: 'pointer', color: C.text, padding: 4,
          }} className="mobile-menu-btn">
            <Icon name={mobileMenuOpen ? 'close' : 'menu'} size={24} />
          </button>
        </div>
        {/* Mobile menu */}
        {mobileMenuOpen && (
          <div style={{ padding: '16px 24px', background: '#fff', borderTop: `1px solid ${C.border}` }} className="mobile-menu">
            {['Features', 'How It Works', 'Roadmap'].map(item => (
              <button key={item} onClick={() => scrollTo(item.toLowerCase().replace(/ /g, '-'))} style={{
                display: 'block', width: '100%', textAlign: 'left', background: 'none', border: 'none',
                padding: '12px 0', fontSize: 15, fontWeight: 600, color: C.text, cursor: 'pointer',
                borderBottom: `1px solid ${C.borderLight}`,
              }}>{item}</button>
            ))}
            <a href="/login" style={{
              display: 'block', textAlign: 'center', marginTop: 12, padding: '12px', borderRadius: 8,
              background: C.navy, color: '#fff', fontSize: 14, fontWeight: 700, textDecoration: 'none',
            }}>Sign In</a>
          </div>
        )}
      </nav>

      {/* ─── HERO ─── */}
      <section style={{
        paddingTop: 140, paddingBottom: 80,
        textAlign: 'center',
        background: `linear-gradient(180deg, #FAFBFC 0%, #F0F2F5 100%)`,
        position: 'relative',
      }}>
        {/* Subtle background dots */}
        <div style={{
          position: 'absolute', inset: 0, opacity: 0.4,
          backgroundImage: 'radial-gradient(circle, #003462 0.5px, transparent 0.5px)',
          backgroundSize: '32px 32px',
          maskImage: 'radial-gradient(ellipse at center, black 20%, transparent 70%)',
          WebkitMaskImage: 'radial-gradient(ellipse at center, black 20%, transparent 70%)',
        }} />

        <div style={{ position: 'relative', maxWidth: 800, margin: '0 auto', padding: '0 24px' }}>
          <h1 style={{
            fontSize: 'clamp(36px, 5.5vw, 64px)', fontWeight: 900, lineHeight: 1.08,
            color: C.navy, margin: '0 0 20px', letterSpacing: '-0.03em',
          }}>
            Gingr data,<br />
            <span style={{ color: C.gold }}>transformed</span> into<br />
            operational intelligence
          </h1>

          {/* Tagline — key brand statement */}
          <div style={{
            fontSize: 'clamp(18px, 2.5vw, 24px)', fontWeight: 700, color: C.navy,
            letterSpacing: '0.12em', textTransform: 'uppercase',
            margin: '0 0 24px', opacity: 0.7,
          }}>
            The operating system for pet care facilities
          </div>

          <p style={{
            fontSize: 'clamp(16px, 2vw, 19px)', color: C.textSec, lineHeight: 1.6,
            maxWidth: 560, margin: '0 auto 36px',
          }}>
            K9 Operations syncs with your Gingr PMS and turns raw reservation
            and client data into automated checklists, lifecycle management,
            and real-time facility oversight.
          </p>

          <div style={{ display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' }}>
            <a href="/login" style={{
              padding: '14px 32px', borderRadius: 10, background: C.navy, color: '#fff',
              fontSize: 15, fontWeight: 700, textDecoration: 'none',
              boxShadow: '0 4px 14px rgba(0,52,98,0.25)',
              transition: 'all 0.2s',
            }}>Get Started</a>
            <a href="/public-roadmap" style={{
              padding: '14px 32px', borderRadius: 10, background: '#fff', color: C.navy,
              fontSize: 15, fontWeight: 700, textDecoration: 'none',
              border: `1.5px solid ${C.border}`,
              transition: 'all 0.2s',
            }}>View Roadmap</a>
          </div>
        </div>
      </section>

      {/* ─── TRUST BAR ─── */}
      <section style={{ padding: '40px 24px', background: '#fff', borderBottom: `1px solid ${C.borderLight}` }}>
        <div style={{ maxWidth: 900, margin: '0 auto', display: 'flex', justifyContent: 'center', gap: 48, flexWrap: 'wrap', alignItems: 'center' }}>
          {[
            { label: 'Gingr Integration', icon: 'sync' },
            { label: 'Real-Time Sync', icon: 'sync' },
            { label: 'Role-Based Access', icon: 'shield' },
            { label: 'AES-256 Encryption', icon: 'shield' },
          ].map((item, i) => (
            <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <Icon name={item.icon} size={18} color={C.textMut} />
              <span style={{ fontSize: 13, fontWeight: 600, color: C.textMut }}>{item.label}</span>
            </div>
          ))}
        </div>
      </section>


      {/* ─── DATA FLOW ANIMATION ─── */}
      <section id="how-it-works" style={{ padding: '80px 24px', background: '#fff' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto', textAlign: 'center' }}>
          <div style={{
            display: 'inline-flex', alignItems: 'center', gap: 8,
            padding: '6px 14px', borderRadius: 100,
            background: C.navy + '08', marginBottom: 16,
          }}>
            <span style={{ fontSize: 12, fontWeight: 700, color: C.navy, letterSpacing: '0.06em', textTransform: 'uppercase' }}>How It Works</span>
          </div>
          <h2 style={{ fontSize: 'clamp(28px, 4vw, 44px)', fontWeight: 800, color: C.text, margin: '0 0 12px', letterSpacing: '-0.02em' }}>
            Your data, intelligently distributed
          </h2>
          <p style={{ fontSize: 17, color: C.textSec, maxWidth: 600, margin: '0 auto 48px', lineHeight: 1.6 }}>
            Gingr feeds owner, animal, and reservation data into K9 Operations.
            The system processes and routes each client into the right lifecycle bucket automatically.
          </p>
          <DataFlowAnimation />

          <div style={{ display: 'flex', justifyContent: 'center', gap: 32, marginTop: 48, flexWrap: 'wrap' }}>
            {[
              { label: 'Cold', desc: 'Inactive 14+ days from sync — needs re-engagement', color: '#64748B' },
              { label: 'Conversion', desc: 'New leads from tours & evals — no booking yet', color: '#10B981' },
              { label: 'Retention', desc: 'Lapsed clients past configurable threshold', color: '#F59E0B' },
            ].map((item, i) => (
              <div key={i} style={{ textAlign: 'center', maxWidth: 200 }}>
                <div style={{
                  width: 40, height: 40, borderRadius: 12, margin: '0 auto 12px',
                  background: item.color + '12', display: 'flex', alignItems: 'center', justifyContent: 'center',
                  border: `1.5px solid ${item.color}30`,
                }}>
                  <div style={{ width: 12, height: 12, borderRadius: '50%', background: item.color }} />
                </div>
                <div style={{ fontSize: 15, fontWeight: 700, color: C.text }}>{item.label}</div>
                <div style={{ fontSize: 13, color: C.textSec, marginTop: 4, lineHeight: 1.4 }}>{item.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>


      {/* ─── FEATURES ─── */}
      <section id="features" style={{ padding: '40px 24px 0', background: C.bg }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>

          {/* Customer Lifecycle CRM */}
          <FeatureSection
            icon="lifecycle"
            title="Customer Lifecycle CRM"
            subtitle="Relationship Management"
            accentColor={C.navy}
            description="Every client automatically flows through four stages — Conversion, Active, Retention, and Cold — based on their real booking behavior. No manual tagging required."
            bullets={[
              'Conversion stage auto-captures leads from tours & evaluations with follow-up tracking',
              'Active stage includes all clients with recent bookings — daycare, boarding, or both',
              'Retention triggers when configurable lapse thresholds are exceeded (90 days daycare, 180 days boarding)',
              'Cold stage for manually flagged leads with one-click Revive to re-engage',
              'Advanced filtering: 17+ filter fields across client info, activity, services, and lifecycle stage',
              'Full contact management with outreach logging, follow-up dates, and custom notes',
            ]}
            reversed={false}
          />

          {/* Operations Hub */}
          <FeatureSection
            icon="ops"
            title="Operations Hub"
            subtitle="Daily Facility Management"
            accentColor="#0EA5E9"
            description="A centralized command center for every daily task your facility needs to run. Six configurable checklists plus automated service reports derived from real reservation data."
            bullets={[
              'Opening, Front-End, Back-End, and Closing checklists with completion tracking',
              'Room Cleaning with intelligent room assignment — clean, disinfect, and awaiting-checkout states',
              'Bathing Report auto-generated from in-house reservations with "Bath" in services',
              'Pamper Package Plus for Luxury Suite dogs and add-on purchasers',
              'Private Play scheduling — 3 sessions per dog with time tracking',
              'EOD Report with daily notes, incidents, and summary analytics (weekly + MTD trends)',
            ]}
            reversed={true}
          />

          {/* Checkout TV */}
          <FeatureSection
            icon="tv"
            title="Checkout TV"
            subtitle="Real-Time Facility Display"
            accentColor="#AF8D54"
            description="A dark, fullscreen display designed for lobby monitors. Shows every checked-in dog with their photo, breed, owner name, and room number — updating in real time."
            bullets={[
              'Auto-populates from checked-in daycare and boarding reservations',
              'Dog photos, breed info, and owner last name displayed per card',
              'Room numbers from intelligent assignment algorithm',
              'Daycare and boarding sections with live count stats',
              'Real-time clock and auto-refresh — no manual interaction needed',
              'One-click exit back to Operations Hub',
            ]}
            reversed={false}
          />

          {/* Reports */}
          <FeatureSection
            icon="reports"
            title="Natural Language Reports"
            subtitle="Ask Anything About Your Data"
            accentColor="#8B5CF6"
            description='Type a question like "Revenue by suite type" or "Top 10 clients by spend" and get instant charts and tables. No SQL, no spreadsheets — just answers.'
            bullets={[
              '14 pre-built query suggestions across Revenue, Clients, Operations, and Analysis',
              'Custom date ranges: week, month, quarter, year, and custom',
              'Compare mode for period-over-period analysis',
              'Cash and accrual revenue views with sortable transaction tables',
              'RevPAR, occupancy rates, average length of stay, and add-on attach rates',
            ]}
            reversed={true}
          />
        </div>
      </section>


      {/* ─── WHAT SETS US APART ─── */}
      <section style={{ padding: '80px 24px', background: '#fff' }}>
        <div style={{ maxWidth: 1000, margin: '0 auto', textAlign: 'center' }}>
          <h2 style={{ fontSize: 'clamp(28px, 4vw, 40px)', fontWeight: 800, color: C.text, margin: '0 0 12px', letterSpacing: '-0.02em' }}>
            Built different
          </h2>
          <p style={{ fontSize: 17, color: C.textSec, maxWidth: 520, margin: '0 auto 48px', lineHeight: 1.6 }}>
            K9 Operations isn't a generic CRM bolted onto a pet app. It's purpose-built
            infrastructure that sits on top of your existing Gingr PMS.
          </p>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 20 }}>
            {[
              {
                icon: 'sync', title: 'Gingr-Native',
                desc: 'Direct API integration syncs owners, animals, reservations, and transactions. No CSV imports, no duplicate entry.',
              },
              {
                icon: 'lifecycle', title: 'Automatic Lifecycle Staging',
                desc: 'Clients move between Conversion → Active → Retention → Cold based on real booking behavior, not manual tagging.',
              },
              {
                icon: 'ops', title: 'Reservation-Driven Operations',
                desc: 'Bathing reports, pamper lists, and room assignments generate automatically from today\'s checked-in reservations.',
              },
              {
                icon: 'shield', title: 'Role-Based Permissions',
                desc: 'Admin, manager, and staff roles with granular feature-level access control. Sensitive data stays protected.',
              },
              {
                icon: 'funnel', title: 'Sales Funnel Tracking',
                desc: 'Tour-to-booking and eval-to-booking conversion funnels with automated follow-up scheduling.',
              },
              {
                icon: 'star', title: 'Multi-Location Ready',
                desc: 'Enterprise tier supports operations matrix, cross-location attendance, and centralized user management.',
              },
            ].map((card, i) => (
              <div key={i} style={{
                padding: 28, borderRadius: 16, background: C.surfaceAlt, border: `1px solid ${C.borderLight}`,
                textAlign: 'left', transition: 'all 0.2s',
              }}>
                <div style={{
                  width: 40, height: 40, borderRadius: 10, background: C.navy + '08',
                  display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 16,
                }}>
                  <Icon name={card.icon} size={20} color={C.navy} />
                </div>
                <div style={{ fontSize: 16, fontWeight: 700, color: C.text, marginBottom: 8 }}>{card.title}</div>
                <div style={{ fontSize: 14, color: C.textSec, lineHeight: 1.6 }}>{card.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>


      {/* ─── PRODUCT TIERS ─── */}
      <section style={{ padding: '80px 24px', background: C.bg }}>
        <div style={{ maxWidth: 900, margin: '0 auto', textAlign: 'center' }}>
          <h2 style={{ fontSize: 'clamp(28px, 4vw, 40px)', fontWeight: 800, color: C.text, margin: '0 0 12px', letterSpacing: '-0.02em' }}>
            Two tiers. One mission.
          </h2>
          <p style={{ fontSize: 17, color: C.textSec, maxWidth: 500, margin: '0 auto 48px' }}>
            Choose the product that matches your facility's needs.
          </p>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))', gap: 24 }}>
            {/* KOL */}
            <div style={{
              padding: 36, borderRadius: 20, background: '#fff', border: `2px solid ${C.navy}`,
              textAlign: 'left', position: 'relative',
            }}>
              <div style={{
                position: 'absolute', top: -12, left: 24, padding: '4px 14px', borderRadius: 100,
                background: C.navy, color: '#fff', fontSize: 11, fontWeight: 700, letterSpacing: '0.04em',
              }}>CURRENT</div>
              <div style={{ fontSize: 13, fontWeight: 700, color: C.textMut, letterSpacing: '0.06em', textTransform: 'uppercase', marginBottom: 4, marginTop: 4 }}>K9 Operations Lite</div>
              <div style={{ fontSize: 28, fontWeight: 900, color: C.navy, marginBottom: 4 }}>KOL</div>
              <div style={{ fontSize: 14, color: C.textSec, marginBottom: 24, lineHeight: 1.5 }}>Full CRM, operations hub, reports, and facility management tools.</div>
              {['Customer Lifecycle CRM', 'Operations Hub (6 checklists)', 'Checkout TV', 'NLP Reports', 'Sales Funnel', 'Multi-location support'].map((f, i) => (
                <div key={i} style={{ display: 'flex', gap: 10, alignItems: 'center', padding: '6px 0' }}>
                  <Icon name="check" size={15} color={C.success} />
                  <span style={{ fontSize: 14, color: C.text }}>{f}</span>
                </div>
              ))}
            </div>

            {/* KOP */}
            <div style={{
              padding: 36, borderRadius: 20, background: '#fff', border: `1px solid ${C.border}`,
              textAlign: 'left', position: 'relative', opacity: 0.75,
            }}>
              <div style={{
                position: 'absolute', top: -12, left: 24, padding: '4px 14px', borderRadius: 100,
                background: C.textMut, color: '#fff', fontSize: 11, fontWeight: 700, letterSpacing: '0.04em',
              }}>COMING SOON</div>
              <div style={{ fontSize: 13, fontWeight: 700, color: C.textMut, letterSpacing: '0.06em', textTransform: 'uppercase', marginBottom: 4, marginTop: 4 }}>K9 Operations POS</div>
              <div style={{ fontSize: 28, fontWeight: 900, color: C.text, marginBottom: 4 }}>KOP</div>
              <div style={{ fontSize: 14, color: C.textSec, marginBottom: 24, lineHeight: 1.5 }}>Point-of-sale tier with booking, payments, and full Gingr replacement.</div>
              {['Everything in KOL', 'Online Booking Engine', 'Payment Processing', 'Digital Report Cards', 'Automated Invoicing', 'Customer Portal'].map((f, i) => (
                <div key={i} style={{ display: 'flex', gap: 10, alignItems: 'center', padding: '6px 0' }}>
                  <Icon name="check" size={15} color={C.textMut} />
                  <span style={{ fontSize: 14, color: C.textSec }}>{f}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>


      {/* ─── ROADMAP CTA ─── */}
      <section id="roadmap" style={{ padding: '80px 24px', background: '#fff' }}>
        <div style={{
          maxWidth: 800, margin: '0 auto', textAlign: 'center',
          padding: '60px 40px', borderRadius: 24,
          background: `linear-gradient(135deg, ${C.navy}06 0%, ${C.gold}06 100%)`,
          border: `1px solid ${C.border}`,
        }}>
          <h2 style={{ fontSize: 32, fontWeight: 800, color: C.text, margin: '0 0 12px' }}>See what's next</h2>
          <p style={{ fontSize: 17, color: C.textSec, margin: '0 0 28px', lineHeight: 1.6 }}>
            Our public roadmap tracks every feature in development — from planned to shipped.
          </p>
          <a href="/public-roadmap" style={{
            display: 'inline-flex', alignItems: 'center', gap: 8,
            padding: '14px 32px', borderRadius: 10, background: C.navy, color: '#fff',
            fontSize: 15, fontWeight: 700, textDecoration: 'none',
            boxShadow: '0 4px 14px rgba(0,52,98,0.25)',
          }}>
            View Public Roadmap <Icon name="arrow" size={16} color="#fff" />
          </a>
        </div>
      </section>


      {/* ─── FOOTER ─── */}
      <footer style={{ padding: '48px 24px 32px', background: C.bg, borderTop: `1px solid ${C.border}` }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 32, marginBottom: 32 }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
                <K9Logo size={28} />
                <span style={{ fontSize: 15, fontWeight: 800, color: C.navy }}>K9 Operations</span>
              </div>
              <div style={{ fontSize: 13, color: C.textMut, lineHeight: 1.5 }}>
                The operating system for<br />pet care facilities.
              </div>
            </div>
            <div style={{ display: 'flex', gap: 48, flexWrap: 'wrap' }}>
              <div>
                <div style={{ fontSize: 12, fontWeight: 700, color: C.textMut, letterSpacing: '0.06em', textTransform: 'uppercase', marginBottom: 12 }}>Product</div>
                {['Features', 'Roadmap', 'Sign In'].map((l, i) => (
                  <div key={i} style={{ marginBottom: 8 }}>
                    <a href={l === 'Sign In' ? '/login' : l === 'Roadmap' ? '/public-roadmap' : '#features'} style={{
                      fontSize: 14, color: C.textSec, textDecoration: 'none',
                    }}>{l}</a>
                  </div>
                ))}
              </div>
              <div>
                <div style={{ fontSize: 12, fontWeight: 700, color: C.textMut, letterSpacing: '0.06em', textTransform: 'uppercase', marginBottom: 12 }}>Legal</div>
                <div style={{ marginBottom: 8 }}>
                  <button onClick={() => setLegalModal('tos')} style={{
                    background: 'none', border: 'none', cursor: 'pointer', fontSize: 14, color: C.textSec, padding: 0,
                  }}>Terms of Service</button>
                </div>
                <div style={{ marginBottom: 8 }}>
                  <button onClick={() => setLegalModal('privacy')} style={{
                    background: 'none', border: 'none', cursor: 'pointer', fontSize: 14, color: C.textSec, padding: 0,
                  }}>Privacy Policy</button>
                </div>
              </div>
              <div>
                <div style={{ fontSize: 12, fontWeight: 700, color: C.textMut, letterSpacing: '0.06em', textTransform: 'uppercase', marginBottom: 12 }}>Contact</div>
                <div style={{ fontSize: 14, color: C.textSec }}>zacknisbet@gmail.com</div>
              </div>
            </div>
          </div>
          <div style={{ borderTop: `1px solid ${C.borderLight}`, paddingTop: 20, display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 8 }}>
            <div style={{ fontSize: 12, color: C.textMut }}>© 2026 K9 Operations LLC. All rights reserved.</div>
            <div style={{ fontSize: 12, color: C.textMut }}>Built in New Jersey 🐾</div>
          </div>
        </div>
      </footer>


      {/* ─── LEGAL MODAL ─── */}
      {legalModal && (
        <div style={{
          position: 'fixed', inset: 0, zIndex: 200, background: 'rgba(0,0,0,0.5)',
          display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24,
        }} onClick={() => setLegalModal(null)}>
          <div style={{
            background: '#fff', borderRadius: 20, maxWidth: 640, width: '100%',
            maxHeight: '80vh', overflow: 'auto', padding: 36,
          }} onClick={e => e.stopPropagation()}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
              <h2 style={{ fontSize: 22, fontWeight: 800, color: C.text, margin: 0 }}>
                {legalModal === 'tos' ? 'Terms of Service' : 'Privacy Policy'}
              </h2>
              <button onClick={() => setLegalModal(null)} style={{
                background: C.surfaceAlt, border: 'none', cursor: 'pointer', width: 32, height: 32, borderRadius: 8,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}>
                <Icon name="close" size={16} color={C.text} />
              </button>
            </div>
            <div style={{ fontSize: 12, color: C.textMut, marginBottom: 24 }}>
              Effective: January 1, 2026 · K9 Operations LLC · Burlington County, NJ
            </div>
            {(legalModal === 'tos' ? TOS_SECTIONS : PRIVACY_SECTIONS).map((s, i) => (
              <div key={i} style={{ marginBottom: 20 }}>
                <div style={{ fontSize: 14, fontWeight: 700, color: C.text, marginBottom: 6 }}>{s.t}</div>
                <div style={{ fontSize: 13, color: C.textSec, lineHeight: 1.7 }}>{s.b}</div>
              </div>
            ))}
          </div>
        </div>
      )}


      {/* ─── GLOBAL STYLES ─── */}
      <style>{`
        @media (max-width: 768px) {
          .nav-links { display: none !important; }
          .mobile-menu-btn { display: flex !important; }
        }
        @media (min-width: 769px) {
          .mobile-menu { display: none !important; }
        }
      `}</style>
    </div>
  );
}
