// © 2026 K9 Operations LLC. All Rights Reserved.
// Proprietary and Confidential.

import React, { useState, useEffect, useRef } from 'react';

const D = {
  bg: '#0A0F1C',
  bgAlt: '#0D1425',
  surface: '#141B2D',
  surfaceHover: '#1A2340',
  border: '#1E2A42',
  borderLight: '#2A3A5C',
  text: '#F0F2F5',
  textSec: '#8B95A8',
  textMut: '#5A647A',
  gold: '#AF8D54',
  goldLight: '#C4A46A',
  goldDark: '#8B6F3C',
  goldGlow: 'rgba(175,141,84,0.15)',
  navy: '#003462',
  navyLight: '#0A4D8A',
};

// ─── Legal Data ───────────────────────────────────────────────────────────────

const TOS_SECTIONS = [
  { t: "1. Definitions", b: "\"Company\" refers to K9 Operations LLC, a New Jersey limited liability company. \"Service\" refers to the K9 Operations cloud-based software platform. \"Customer\" refers to the pet care facility or business entity that subscribes. \"User\" refers to any individual who accesses the Service. \"Customer Data\" refers to all data uploaded or generated by Users through the Service." },
  { t: "2. Description of Service", b: "K9 Operations provides a cloud-based SaaS platform for pet care facility management, including pet profile management, booking and scheduling, feeding and medication tracking, report cards, employee scheduling, and invoicing." },
  { t: "3. Account Registration and Security", b: "Customers must create an account and designate at least one administrator. You are responsible for providing accurate registration information, managing user accounts and access levels, maintaining the confidentiality of login credentials, and all activities that occur under your account." },
  { t: "4. Permitted Use and Restrictions", b: "You receive a limited, non-exclusive, non-transferable right to use the Service for your pet care facility operations. You may not copy, modify, distribute, sell, reverse engineer, scrape, or attempt unauthorized access to the Service." },
  { t: "5. Intellectual Property", b: "The Service is the exclusive property of K9 Operations LLC, protected by U.S. copyright and trademark laws. Copyright Registration filed February 9, 2026. All rights not expressly granted are reserved." },
  { t: "6. Customer Data", b: "You retain ownership of your Customer Data. You grant K9 Operations a limited license to host, store, and process your data solely to provide the Service. We will not access or disclose your data except as necessary to provide the Service or as required by law." },
  { t: "7. Service Availability", b: "We target 99.9% monthly uptime, excluding scheduled maintenance. Scheduled maintenance will be communicated at least 48 hours in advance when practicable." },
  { t: "8. Fees and Payment", b: "Access requires a paid subscription. Pricing and terms are established in your SaaS License Agreement. We may modify pricing with at least 60 days written notice." },
  { t: "9. Term and Termination", b: "Upon termination, you have 30 days to request a data export (CSV or JSON). After 30 days, Customer Data may be deleted. Outstanding fees remain due." },
  { t: "10. Disclaimers and Limitation of Liability", b: "THE SERVICE IS PROVIDED \"AS IS\" WITHOUT WARRANTIES. We make no representations regarding pet health outcomes. Our total aggregate liability shall not exceed fees paid in the preceding 12 months." },
  { t: "11. Indemnification", b: "You agree to indemnify K9 Operations LLC against claims arising from your use of the Service, violation of these Terms, or your operation of a pet care facility." },
  { t: "12. Governing Law", b: "These Terms are governed by New Jersey law. Disputes shall be resolved in Burlington County, NJ courts." },
  { t: "13. Changes to Terms", b: "We will provide at least 30 days notice for material changes. Continued use constitutes acceptance of modified Terms." },
  { t: "14. Contact", b: "Questions? Contact us at zacknisbet@gmail.com" },
];

const PRIVACY_SECTIONS = [
  { t: "1. Information We Collect", b: "We collect account information (business name, contact details, employee info), pet and client data (pet profiles, vaccination records, medical notes, emergency contacts), booking and service data (reservations, feeding logs, report cards, invoices), employee data (names, roles, schedules), usage data (IP address, browser type, pages viewed), and session cookies for authentication." },
  { t: "2. How We Use Your Information", b: "We use your information to provide and operate the Service, communicate with you, improve the platform, ensure security, and comply with legal obligations. We do not use Customer Data to train machine learning models." },
  { t: "3. How We Share Your Information", b: "We do not sell, rent, or trade your personal information. We share data only with service providers (Supabase for database hosting, Vercel for application hosting, payment processors), when required by law, or in connection with a business transfer." },
  { t: "4. Data Security", b: "All data is encrypted at rest (AES-256) and in transit (TLS 1.2+). We use role-based access controls and hashed passwords. We do not store credit card numbers or sensitive payment credentials." },
  { t: "5. Data Retention", b: "We retain data while your account is active. After termination, you have 30 days to export your data. Customer Data is deleted within 90 days of the export period, unless retention is required by law." },
  { t: "6. Your Rights", b: "You may request access to, correction of, or deletion of your personal information. You may request data export in CSV or JSON format. You may opt out of marketing communications at any time. Contact zacknisbet@gmail.com to exercise these rights." },
  { t: "7. Children's Privacy", b: "The Service is not directed to children under 13. We do not knowingly collect personal information from children under 13." },
  { t: "8. Third-Party Services", b: "This Privacy Policy does not apply to third-party services accessed through the platform. We encourage you to review their privacy policies." },
  { t: "9. State-Specific Disclosures", b: "California residents may have additional rights under CCPA/CPRA, including the right to know, delete, and opt out of data sales (we do not sell data). New Jersey residents have the right to access and correct their information and receive breach notifications." },
  { t: "10. Changes to This Policy", b: "We provide at least 30 days notice for material changes. Continued use constitutes acceptance." },
  { t: "11. Contact", b: "Questions about privacy? Email zacknisbet@gmail.com with \"Privacy\" in the subject line." },
];

// ─── Legal Modal ──────────────────────────────────────────────────────────────

function LegalModal({ type, onClose }) {
  const isTos = type === 'tos';
  const title = isTos ? 'Terms of Service' : 'Privacy Policy';
  const intro = isTos
    ? 'Welcome to K9 Operations. These Terms of Service govern your access to and use of the K9 Operations platform, including any related applications, features, and services. By accessing or using the Service, you agree to be bound by these Terms.'
    : 'K9 Operations LLC is committed to protecting the privacy and security of information collected through the K9 Operations platform. This Privacy Policy describes what information we collect, how we use it, how we share it, and your choices.';
  const sections = isTos ? TOS_SECTIONS : PRIVACY_SECTIONS;

  useEffect(() => {
    document.body.style.overflow = 'hidden';
    return () => { document.body.style.overflow = ''; };
  }, []);

  return (
    <div
      onClick={onClose}
      style={{
        position: 'fixed', inset: 0, zIndex: 9999,
        background: 'rgba(0,0,0,0.75)', backdropFilter: 'blur(6px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20,
      }}
    >
      <div
        onClick={e => e.stopPropagation()}
        style={{
          width: '100%', maxWidth: 640, maxHeight: '80vh',
          background: D.surface, borderRadius: 16, overflow: 'hidden',
          display: 'flex', flexDirection: 'column',
          boxShadow: '0 24px 80px rgba(0,0,0,0.6)',
          border: `1px solid ${D.border}`,
        }}
      >
        <div style={{
          padding: '20px 28px', borderBottom: `1px solid ${D.border}`,
          display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexShrink: 0,
        }}>
          <div>
            <div style={{ fontSize: 18, fontWeight: 700, color: D.text, fontFamily: "'Playfair Display', Georgia, serif" }}>{title}</div>
            <div style={{ fontSize: 11, color: D.textMut, marginTop: 3, letterSpacing: '0.04em' }}>Effective February 10, 2026</div>
          </div>
          <button
            onClick={onClose}
            style={{
              width: 32, height: 32, borderRadius: 8, border: `1px solid ${D.border}`,
              background: D.bgAlt, cursor: 'pointer', display: 'flex', alignItems: 'center',
              justifyContent: 'center', color: D.textSec, fontSize: 20, fontFamily: 'inherit',
              lineHeight: 1, transition: 'border-color 0.2s',
            }}
          >×</button>
        </div>
        <div style={{ flex: 1, overflow: 'auto', padding: '24px 28px' }}>
          <p style={{ fontSize: 13, color: D.textSec, lineHeight: 1.75, marginTop: 0, marginBottom: 24 }}>{intro}</p>
          {sections.map((s, i) => (
            <div key={i} style={{ marginBottom: 18 }}>
              <div style={{ fontSize: 13, fontWeight: 700, color: D.gold, marginBottom: 5, letterSpacing: '0.01em' }}>{s.t}</div>
              <div style={{ fontSize: 13, color: D.textSec, lineHeight: 1.75 }}>{s.b}</div>
            </div>
          ))}
          <div style={{
            textAlign: 'center', fontSize: 11, color: D.textMut,
            marginTop: 28, paddingTop: 16, borderTop: `1px solid ${D.border}`,
          }}>© 2026 K9 Operations LLC. All Rights Reserved.</div>
        </div>
      </div>
    </div>
  );
}

// ─── Logo SVG ─────────────────────────────────────────────────────────────────

function ConstellationLogo({ size = 36 }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 100 100"
      width={size}
      height={size}
      style={{ display: 'block' }}
      aria-label="K9 Operations logo"
    >
      <defs>
        <linearGradient id="logoGrad" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stopColor={D.goldLight} />
          <stop offset="100%" stopColor={D.gold} />
        </linearGradient>
        <linearGradient id="logoGradLg" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stopColor={D.goldLight} />
          <stop offset="100%" stopColor={D.gold} />
        </linearGradient>
      </defs>
      <g transform="translate(50,50)">
        <line x1="0" y1="0" x2="-22" y2="-24" stroke={D.gold} strokeWidth="1.5" opacity="0.4" />
        <line x1="0" y1="0" x2="26" y2="-16" stroke={D.gold} strokeWidth="1.5" opacity="0.4" />
        <line x1="0" y1="0" x2="2" y2="28" stroke={D.gold} strokeWidth="1.5" opacity="0.4" />
        <circle cx="0" cy="0" r="13" fill="url(#logoGrad)" />
        <circle cx="0" cy="0" r="5" fill={D.goldDark} opacity="0.5" />
        <circle cx="-22" cy="-24" r="7" fill={D.surface} stroke={D.gold} strokeWidth="1.5" />
        <circle cx="26" cy="-16" r="7" fill={D.surface} stroke={D.gold} strokeWidth="1.5" />
        <circle cx="2" cy="28" r="7" fill={D.surface} stroke={D.gold} strokeWidth="1.5" />
      </g>
    </svg>
  );
}

// ─── Hook: Intersection Observer ──────────────────────────────────────────────

function useFadeIn() {
  const ref = useRef(null);
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) { setVisible(true); observer.disconnect(); } },
      { threshold: 0.12 }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  return [ref, visible];
}

// ─── Nav Bar ──────────────────────────────────────────────────────────────────

function Nav() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [hoveredLink, setHoveredLink] = useState(null);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  const scrollTo = (id) => {
    setMobileOpen(false);
    const el = document.getElementById(id);
    if (el) el.scrollIntoView({ behavior: 'smooth' });
  };

  const navLinks = [
    { label: 'Features', action: () => scrollTo('features') },
    { label: 'Products', action: () => scrollTo('products') },
    { label: 'Roadmap', action: () => { window.location.href = '/public-roadmap'; } },
  ];

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&display=swap');

        *, *::before, *::after { box-sizing: border-box; }

        html { scroll-behavior: smooth; }

        body {
          margin: 0;
          background: ${D.bg};
          color: ${D.text};
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Inter', sans-serif;
          -webkit-font-smoothing: antialiased;
        }

        @keyframes heroGlow {
          0%, 100% { opacity: 0.05; }
          50% { opacity: 0.12; }
        }

        @keyframes fadeInUp {
          from { opacity: 0; transform: translateY(28px); }
          to   { opacity: 1; transform: translateY(0); }
        }

        @keyframes pulse {
          0%, 100% { transform: scale(1); opacity: 1; }
          50% { transform: scale(1.04); opacity: 0.85; }
        }

        .fade-in-up {
          opacity: 0;
          transform: translateY(28px);
          transition: opacity 0.65s cubic-bezier(0.22,1,0.36,1), transform 0.65s cubic-bezier(0.22,1,0.36,1);
        }
        .fade-in-up.visible {
          opacity: 1;
          transform: translateY(0);
        }
        .fade-in-up.delay-1 { transition-delay: 0.1s; }
        .fade-in-up.delay-2 { transition-delay: 0.2s; }
        .fade-in-up.delay-3 { transition-delay: 0.3s; }

        .btn-gold {
          background: ${D.gold};
          color: #0A0F1C;
          border: none;
          padding: 14px 32px;
          border-radius: 10px;
          font-size: 16px;
          font-weight: 700;
          cursor: pointer;
          font-family: inherit;
          transition: background 0.2s, transform 0.15s, box-shadow 0.2s;
          letter-spacing: -0.01em;
          text-decoration: none;
          display: inline-flex;
          align-items: center;
          gap: 8px;
        }
        .btn-gold:hover {
          background: ${D.goldLight};
          transform: translateY(-1px);
          box-shadow: 0 8px 24px rgba(175,141,84,0.3);
        }
        .btn-gold:active { transform: translateY(0); }

        .btn-outline {
          background: transparent;
          color: ${D.textSec};
          border: 1.5px solid ${D.border};
          padding: 14px 32px;
          border-radius: 10px;
          font-size: 16px;
          font-weight: 600;
          cursor: pointer;
          font-family: inherit;
          transition: border-color 0.2s, color 0.2s, transform 0.15s;
          letter-spacing: -0.01em;
          text-decoration: none;
          display: inline-flex;
          align-items: center;
          gap: 8px;
        }
        .btn-outline:hover {
          border-color: ${D.gold};
          color: ${D.goldLight};
          transform: translateY(-1px);
        }

        .product-card {
          background: ${D.surface};
          border: 1px solid ${D.border};
          border-radius: 16px;
          padding: 40px;
          transition: transform 0.25s cubic-bezier(0.22,1,0.36,1), box-shadow 0.25s, border-color 0.25s;
          cursor: default;
        }
        .product-card:hover {
          transform: translateY(-4px);
          box-shadow: 0 24px 60px rgba(0,0,0,0.4);
          border-color: ${D.borderLight};
        }

        .feature-card {
          padding: 36px 28px;
          border-radius: 14px;
          border: 1px solid ${D.border};
          background: ${D.surface};
          transition: border-color 0.25s, transform 0.25s;
        }
        .feature-card:hover {
          border-color: ${D.borderLight};
          transform: translateY(-3px);
        }

        .roadmap-card {
          background: ${D.surface};
          border: 1px solid ${D.border};
          border-radius: 14px;
          padding: 28px;
          transition: transform 0.2s, border-color 0.2s;
        }
        .roadmap-card:hover {
          transform: translateY(-3px);
          border-color: ${D.borderLight};
        }

        .nav-link {
          background: none;
          border: none;
          color: ${D.textSec};
          font-size: 15px;
          font-family: inherit;
          font-weight: 500;
          cursor: pointer;
          padding: 6px 0;
          letter-spacing: -0.01em;
          transition: color 0.2s;
          position: relative;
        }
        .nav-link::after {
          content: '';
          position: absolute;
          bottom: 0;
          left: 0;
          width: 0;
          height: 1px;
          background: ${D.gold};
          transition: width 0.25s cubic-bezier(0.22,1,0.36,1);
        }
        .nav-link:hover { color: ${D.text}; }
        .nav-link:hover::after { width: 100%; }

        .gold-text { color: ${D.gold}; }

        ::-webkit-scrollbar { width: 6px; }
        ::-webkit-scrollbar-track { background: ${D.bg}; }
        ::-webkit-scrollbar-thumb { background: ${D.border}; border-radius: 3px; }

        @media (max-width: 768px) {
          .nav-center-links { display: none !important; }
          .nav-right-desktop { display: none !important; }
          .nav-hamburger { display: flex !important; }
          .hero-headline { font-size: 38px !important; }
          .hero-sub { font-size: 16px !important; }
          .hero-buttons { flex-direction: column; align-items: stretch !important; }
          .hero-buttons .btn-gold,
          .hero-buttons .btn-outline { text-align: center; justify-content: center; }
          .products-grid { grid-template-columns: 1fr !important; }
          .features-grid { grid-template-columns: 1fr !important; }
          .roadmap-grid { grid-template-columns: 1fr !important; }
          .footer-grid { flex-direction: column; align-items: center; text-align: center; gap: 20px !important; }
          .footer-links { justify-content: center; }
          .section-pad { padding: 80px 20px !important; }
          .hero-pad { padding: 120px 20px 80px !important; }
          .app-window { display: none; }
          .two-col-footer { flex-direction: column !important; align-items: center !important; gap: 12px !important; }
        }
      `}</style>

      <nav style={{
        position: 'fixed', top: 0, left: 0, right: 0, zIndex: 1000,
        background: scrolled ? 'rgba(10,15,28,0.92)' : 'rgba(10,15,28,0.85)',
        backdropFilter: 'blur(20px)',
        borderBottom: `1px solid ${D.border}`,
        transition: 'background 0.3s',
        height: 64,
      }}>
        <div style={{
          maxWidth: 1200, margin: '0 auto', height: '100%',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          padding: '0 24px',
        }}>
          {/* Logo */}
          <button
            onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
            style={{
              background: 'none', border: 'none', cursor: 'pointer', padding: 0,
              display: 'flex', alignItems: 'center', gap: 12,
            }}
          >
            <ConstellationLogo size={32} />
            <span style={{
              fontFamily: "'Playfair Display', Georgia, serif",
              fontSize: 18, fontWeight: 700, color: D.text,
              letterSpacing: '-0.01em',
            }}>
              K9 Operations
            </span>
          </button>

          {/* Center links */}
          <div className="nav-center-links" style={{ display: 'flex', gap: 36, alignItems: 'center' }}>
            {navLinks.map(link => (
              <button key={link.label} className="nav-link" onClick={link.action}>{link.label}</button>
            ))}
          </div>

          {/* Right CTAs */}
          <div className="nav-right-desktop" style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <button
              onClick={() => { window.location.href = '/login'; }}
              style={{
                background: 'none', border: 'none', color: D.textSec,
                fontSize: 15, fontWeight: 500, cursor: 'pointer',
                fontFamily: 'inherit', padding: '6px 14px',
                transition: 'color 0.2s', letterSpacing: '-0.01em',
              }}
              onMouseEnter={e => e.target.style.color = D.text}
              onMouseLeave={e => e.target.style.color = D.textSec}
            >
              Log In
            </button>
            <button
              className="btn-gold"
              style={{ padding: '10px 22px', fontSize: 14 }}
              onClick={() => { window.location.href = 'mailto:zacknisbet@gmail.com?subject=K9%20Operations%20Demo%20Request'; }}
            >
              Request Demo
            </button>
          </div>

          {/* Mobile hamburger */}
          <button
            className="nav-hamburger"
            style={{
              display: 'none', background: 'none', border: `1px solid ${D.border}`,
              cursor: 'pointer', padding: '8px 10px', borderRadius: 8,
              flexDirection: 'column', gap: 4, alignItems: 'center',
            }}
            onClick={() => setMobileOpen(!mobileOpen)}
            aria-label="Toggle menu"
          >
            {[0,1,2].map(i => (
              <span key={i} style={{ display: 'block', width: 20, height: 1.5, background: D.textSec }} />
            ))}
          </button>
        </div>

        {/* Mobile menu */}
        {mobileOpen && (
          <div style={{
            background: D.surface, borderBottom: `1px solid ${D.border}`,
            padding: '16px 24px 24px',
          }}>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
              {navLinks.map(link => (
                <button
                  key={link.label}
                  onClick={link.action}
                  style={{
                    background: 'none', border: 'none', color: D.textSec, fontSize: 16,
                    fontFamily: 'inherit', fontWeight: 500, cursor: 'pointer',
                    padding: '12px 0', textAlign: 'left', borderBottom: `1px solid ${D.border}`,
                    transition: 'color 0.2s',
                  }}
                >
                  {link.label}
                </button>
              ))}
              <div style={{ display: 'flex', gap: 12, marginTop: 16 }}>
                <button
                  onClick={() => { window.location.href = '/login'; }}
                  style={{
                    flex: 1, padding: '12px', background: 'none', border: `1px solid ${D.border}`,
                    color: D.textSec, borderRadius: 8, fontSize: 15, fontFamily: 'inherit',
                    fontWeight: 500, cursor: 'pointer',
                  }}
                >Log In</button>
                <button
                  className="btn-gold"
                  style={{ flex: 1, justifyContent: 'center', padding: '12px 0', fontSize: 15 }}
                  onClick={() => { window.location.href = 'mailto:zacknisbet@gmail.com?subject=K9%20Operations%20Demo%20Request'; }}
                >Request Demo</button>
              </div>
            </div>
          </div>
        )}
      </nav>
    </>
  );
}

// ─── Hero Section ─────────────────────────────────────────────────────────────

function Hero() {
  return (
    <section style={{
      minHeight: '90vh',
      display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
      background: D.bg,
      position: 'relative', overflow: 'hidden',
      padding: '140px 24px 100px',
      textAlign: 'center',
    }}>
      {/* Animated glow background */}
      <div style={{
        position: 'absolute', inset: 0, pointerEvents: 'none',
        background: 'radial-gradient(ellipse 80% 50% at 50% -5%, rgba(175,141,84,0.1) 0%, transparent 70%)',
        animation: 'heroGlow 6s ease-in-out infinite',
      }} />

      {/* Subtle grid lines */}
      <div style={{
        position: 'absolute', inset: 0, pointerEvents: 'none',
        backgroundImage: `linear-gradient(${D.border}22 1px, transparent 1px), linear-gradient(90deg, ${D.border}22 1px, transparent 1px)`,
        backgroundSize: '80px 80px',
        maskImage: 'radial-gradient(ellipse 80% 60% at 50% 0%, black 0%, transparent 80%)',
        WebkitMaskImage: 'radial-gradient(ellipse 80% 60% at 50% 0%, black 0%, transparent 80%)',
      }} />

      <div style={{ position: 'relative', zIndex: 1, maxWidth: 800, width: '100%' }}>
        {/* Eyebrow */}
        <div style={{
          display: 'inline-flex', alignItems: 'center', gap: 8,
          background: D.goldGlow, border: `1px solid rgba(175,141,84,0.25)`,
          borderRadius: 40, padding: '6px 16px', marginBottom: 32,
        }}>
          <span style={{
            width: 6, height: 6, borderRadius: '50%', background: D.gold,
            animation: 'pulse 2s ease-in-out infinite', display: 'inline-block',
          }} />
          <span style={{ fontSize: 12, color: D.gold, fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase' }}>
            Now Available — Cherry Hill, NJ
          </span>
        </div>

        <h1
          className="hero-headline"
          style={{
            fontFamily: "'Playfair Display', Georgia, serif",
            fontSize: 56, fontWeight: 700, color: D.text,
            letterSpacing: '-0.03em', lineHeight: 1.1,
            margin: '0 0 24px',
          }}
        >
          The Operating System for<br />
          <span style={{ color: D.goldLight }}>Luxury Pet Resorts</span>
        </h1>

        <p
          className="hero-sub"
          style={{
            fontSize: 18, color: D.textSec, maxWidth: 580, margin: '0 auto 40px',
            lineHeight: 1.75, fontWeight: 400,
          }}
        >
          K9 Operations brings intelligence to every touchpoint — from first inquiry to checkout.
          Purpose-built for resorts that refuse to compromise.
        </p>

        <div
          className="hero-buttons"
          style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 14, flexWrap: 'wrap' }}
        >
          <button
            className="btn-gold"
            onClick={() => { window.location.href = 'mailto:zacknisbet@gmail.com?subject=K9%20Operations%20Demo%20Request'; }}
          >
            Request a Demo
          </button>
          <button
            className="btn-outline"
            onClick={() => { window.location.href = '/public-roadmap'; }}
          >
            View Roadmap →
          </button>
        </div>

        <p style={{ fontSize: 13, color: D.textMut, marginTop: 24, letterSpacing: '0.01em' }}>
          Currently powering Cherry Hill's premier luxury pet resort
        </p>

        {/* App window mockup */}
        <div
          className="app-window"
          style={{
            marginTop: 64,
            background: D.surface,
            borderRadius: 16,
            border: `1px solid ${D.border}`,
            boxShadow: '0 40px 80px rgba(0,0,0,0.5), 0 0 0 1px rgba(255,255,255,0.03)',
            maxWidth: 900,
            width: '100%',
            marginLeft: 'auto',
            marginRight: 'auto',
            overflow: 'hidden',
          }}
        >
          {/* Window chrome */}
          <div style={{
            display: 'flex', alignItems: 'center', gap: 8,
            padding: '14px 18px',
            background: D.bgAlt,
            borderBottom: `1px solid ${D.border}`,
          }}>
            <span style={{ width: 12, height: 12, borderRadius: '50%', background: '#FF5F57' }} />
            <span style={{ width: 12, height: 12, borderRadius: '50%', background: '#FFBD2E' }} />
            <span style={{ width: 12, height: 12, borderRadius: '50%', background: '#28CA41' }} />
            <div style={{
              flex: 1, marginLeft: 12, background: D.surface, borderRadius: 6,
              height: 26, display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <span style={{ fontSize: 11, color: D.textMut, letterSpacing: '0.02em' }}>app.k9operations.com</span>
            </div>
          </div>

          {/* App body */}
          <div style={{ display: 'flex', height: 360 }}>
            {/* Sidebar */}
            <div style={{
              width: 200, background: D.bgAlt, borderRight: `1px solid ${D.border}`,
              padding: '20px 0', flexShrink: 0,
            }}>
              <div style={{ padding: '0 16px', marginBottom: 20 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <ConstellationLogo size={22} />
                  <span style={{ fontSize: 12, fontWeight: 700, color: D.textSec, fontFamily: "'Playfair Display', serif" }}>K9 Ops</span>
                </div>
              </div>
              {[
                { label: 'Dashboard', active: true },
                { label: 'Customers', active: false },
                { label: 'Operations', active: false },
                { label: 'Rooms', active: false },
                { label: 'Reports', active: false },
                { label: 'Schedule', active: false },
              ].map(item => (
                <div key={item.label} style={{
                  padding: '8px 16px',
                  background: item.active ? D.goldGlow : 'transparent',
                  borderLeft: item.active ? `2px solid ${D.gold}` : '2px solid transparent',
                  marginBottom: 2,
                }}>
                  <span style={{ fontSize: 12, color: item.active ? D.gold : D.textMut, fontWeight: item.active ? 600 : 400 }}>
                    {item.label}
                  </span>
                </div>
              ))}
            </div>

            {/* Main content area */}
            <div style={{ flex: 1, padding: '20px 24px', overflow: 'hidden' }}>
              {/* Stats row */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 12, marginBottom: 20 }}>
                {[
                  { label: 'Guests In', val: '24', color: D.gold },
                  { label: 'Checkouts', val: '8', color: '#4E9E6B' },
                  { label: 'New Bookings', val: '12', color: D.navyLight },
                  { label: 'Staff On', val: '6', color: D.textSec },
                ].map(s => (
                  <div key={s.label} style={{
                    background: D.bg, borderRadius: 10, padding: '12px 14px',
                    border: `1px solid ${D.border}`,
                  }}>
                    <div style={{ fontSize: 18, fontWeight: 700, color: s.color, fontFamily: "'Playfair Display', serif" }}>{s.val}</div>
                    <div style={{ fontSize: 10, color: D.textMut, marginTop: 2 }}>{s.label}</div>
                  </div>
                ))}
              </div>

              {/* Chart area */}
              <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: 12 }}>
                {/* Bar chart mock */}
                <div style={{ background: D.bg, borderRadius: 10, padding: '16px', border: `1px solid ${D.border}` }}>
                  <div style={{ fontSize: 11, color: D.textMut, marginBottom: 12, fontWeight: 600 }}>Daily Occupancy</div>
                  <div style={{ display: 'flex', alignItems: 'flex-end', gap: 6, height: 80 }}>
                    {[55, 70, 45, 90, 65, 80, 95].map((h, i) => (
                      <div key={i} style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4 }}>
                        <div style={{
                          width: '100%', borderRadius: '3px 3px 0 0',
                          height: `${h}%`,
                          background: i === 6 ? D.gold : `${D.gold}40`,
                          transition: 'height 0.3s',
                        }} />
                        <span style={{ fontSize: 8, color: D.textMut }}>
                          {['M','T','W','T','F','S','S'][i]}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Activity feed mock */}
                <div style={{ background: D.bg, borderRadius: 10, padding: '16px', border: `1px solid ${D.border}` }}>
                  <div style={{ fontSize: 11, color: D.textMut, marginBottom: 12, fontWeight: 600 }}>Live Activity</div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                    {[
                      { dot: '#4E9E6B', text: 'Buddy checked in' },
                      { dot: D.gold, text: 'Room 4 cleaned' },
                      { dot: D.navyLight, text: 'Invoice #1042 sent' },
                      { dot: D.textMut, text: 'Max report card sent' },
                    ].map((item, i) => (
                      <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                        <span style={{ width: 6, height: 6, borderRadius: '50%', background: item.dot, flexShrink: 0 }} />
                        <span style={{ fontSize: 10, color: D.textSec }}>{item.text}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// ─── Products Section ─────────────────────────────────────────────────────────

function Products() {
  const [ref, visible] = useFadeIn();

  const kolFeatures = [
    'Customer Lifecycle Management',
    'Operations Hub & Daily Checklists',
    'Smart Room Management',
    'Checkout TV Display',
    'EOD Reports',
    'Attendance Tracking',
  ];

  const kopFeatures = [
    'Point of Sale & Invoicing',
    'Scheduling & Online Booking',
    'Digital Contracts & Signatures',
    'Branded Pet Report Cards',
    'Multi-Location Enterprise Dashboard',
  ];

  return (
    <section id="products" style={{ padding: '120px 24px', background: D.bgAlt }}>
      <div style={{ maxWidth: 1200, margin: '0 auto' }}>
        <div
          ref={ref}
          className={`fade-in-up${visible ? ' visible' : ''}`}
          style={{ textAlign: 'center', marginBottom: 72 }}
        >
          <div style={{
            display: 'inline-block', fontSize: 11, color: D.gold, fontWeight: 600,
            letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: 16,
          }}>Products</div>
          <h2 style={{
            fontFamily: "'Playfair Display', Georgia, serif",
            fontSize: 40, fontWeight: 700, color: D.text,
            letterSpacing: '-0.02em', margin: '0 0 16px',
          }}>Two Products. One Vision.</h2>
          <p style={{
            fontSize: 17, color: D.textSec, maxWidth: 560, margin: '0 auto',
            lineHeight: 1.7,
          }}>
            Whether you need lean operations tooling or a full business management suite,
            K9 Operations scales with you.
          </p>
        </div>

        <div className="products-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24 }}>
          {/* KOL Card */}
          <div className="product-card fade-in-up delay-1">
            <div style={{ marginBottom: 28 }}>
              <div style={{ fontSize: 11, color: D.gold, fontWeight: 700, letterSpacing: '0.14em', textTransform: 'uppercase', marginBottom: 8 }}>KOL</div>
              <h3 style={{
                fontFamily: "'Playfair Display', Georgia, serif",
                fontSize: 24, fontWeight: 700, color: D.text,
                margin: '0 0 10px', letterSpacing: '-0.02em',
              }}>K9 Operations Lite</h3>
              <p style={{ fontSize: 15, color: D.textSec, margin: 0, lineHeight: 1.6 }}>
                Operations Intelligence for Modern Pet Resorts
              </p>
            </div>

            <div style={{ height: 1, background: D.border, marginBottom: 28 }} />

            <ul style={{ listStyle: 'none', padding: 0, margin: '0 0 32px' }}>
              {kolFeatures.map((f, i) => (
                <li key={i} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '9px 0', borderBottom: i < kolFeatures.length - 1 ? `1px solid ${D.border}22` : 'none' }}>
                  <span style={{ width: 6, height: 6, borderRadius: '50%', background: D.gold, flexShrink: 0 }} />
                  <span style={{ fontSize: 14, color: D.textSec, lineHeight: 1.4 }}>{f}</span>
                </li>
              ))}
            </ul>

            <button
              style={{
                background: 'none', border: 'none', color: D.gold,
                fontSize: 14, fontWeight: 600, cursor: 'pointer', padding: 0,
                fontFamily: 'inherit', letterSpacing: '0.01em',
                display: 'flex', alignItems: 'center', gap: 6,
                transition: 'gap 0.2s, opacity 0.2s',
              }}
              onMouseEnter={e => { e.currentTarget.style.gap = '10px'; }}
              onMouseLeave={e => { e.currentTarget.style.gap = '6px'; }}
            >
              Learn More <span style={{ fontSize: 16 }}>→</span>
            </button>
          </div>

          {/* KOP Card */}
          <div className="product-card fade-in-up delay-2" style={{ background: `linear-gradient(145deg, ${D.surface} 0%, rgba(20,27,45,0.95) 100%)`, position: 'relative', overflow: 'hidden' }}>
            {/* Subtle glow top-right */}
            <div style={{
              position: 'absolute', top: -60, right: -60, width: 200, height: 200,
              borderRadius: '50%', background: D.goldGlow, pointerEvents: 'none',
            }} />

            <div style={{ marginBottom: 28, position: 'relative' }}>
              <div style={{ fontSize: 11, color: D.gold, fontWeight: 700, letterSpacing: '0.14em', textTransform: 'uppercase', marginBottom: 8 }}>KOP</div>
              <h3 style={{
                fontFamily: "'Playfair Display', Georgia, serif",
                fontSize: 24, fontWeight: 700, color: D.text,
                margin: '0 0 10px', letterSpacing: '-0.02em',
              }}>K9 Operations POS</h3>
              <p style={{ fontSize: 15, color: D.textSec, margin: 0, lineHeight: 1.6 }}>
                Complete Resort Management, End to End
              </p>
            </div>

            <div style={{ height: 1, background: D.border, marginBottom: 28 }} />

            <div style={{
              display: 'inline-flex', alignItems: 'center', gap: 8,
              background: D.goldGlow, borderRadius: 6, padding: '6px 12px',
              marginBottom: 16,
            }}>
              <span style={{ fontSize: 12, color: D.gold, fontWeight: 600 }}>Everything in KOL, plus:</span>
            </div>

            <ul style={{ listStyle: 'none', padding: 0, margin: '0 0 32px' }}>
              {kopFeatures.map((f, i) => (
                <li key={i} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '9px 0', borderBottom: i < kopFeatures.length - 1 ? `1px solid ${D.border}22` : 'none' }}>
                  <span style={{ width: 6, height: 6, borderRadius: '50%', background: D.gold, flexShrink: 0 }} />
                  <span style={{ fontSize: 14, color: D.textSec, lineHeight: 1.4 }}>{f}</span>
                </li>
              ))}
            </ul>

            <button
              style={{
                background: 'none', border: 'none', color: D.gold,
                fontSize: 14, fontWeight: 600, cursor: 'pointer', padding: 0,
                fontFamily: 'inherit', letterSpacing: '0.01em',
                display: 'flex', alignItems: 'center', gap: 6,
                transition: 'gap 0.2s',
              }}
              onMouseEnter={e => { e.currentTarget.style.gap = '10px'; }}
              onMouseLeave={e => { e.currentTarget.style.gap = '6px'; }}
            >
              Learn More <span style={{ fontSize: 16 }}>→</span>
            </button>
          </div>
        </div>
      </div>
    </section>
  );
}

// ─── Features Section ─────────────────────────────────────────────────────────

function BuildingIcon() {
  return (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke={D.gold} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
      <path d="M3 21h18M5 21V7l7-4 7 4v14M9 21V13h6v8M9 9h1M14 9h1M9 13h1M14 13h1" />
    </svg>
  );
}

function LinkIcon() {
  return (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke={D.gold} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  );
}

function GlobeIcon() {
  return (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke={D.gold} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="M2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
    </svg>
  );
}

function Features() {
  const [ref, visible] = useFadeIn();

  const pillars = [
    {
      icon: <BuildingIcon />,
      title: 'Built by Operators',
      desc: 'We run a luxury pet resort. We built the tool we wished existed. Every feature comes from real operational pain points — not hypotheticals.',
    },
    {
      icon: <LinkIcon />,
      title: 'Gingr-Native Intelligence',
      desc: 'Deep, bidirectional integration with your existing Gingr data. No double entry. No lost records. Your data, supercharged with layer-2 intelligence.',
    },
    {
      icon: <GlobeIcon />,
      title: 'Enterprise-Ready',
      desc: 'Multi-location oversight with single-location precision. Centralized analytics. Distributed control. Built to scale from one resort to twenty.',
    },
  ];

  return (
    <section id="features" style={{ padding: '120px 24px', background: D.bg }}>
      <div style={{ maxWidth: 1200, margin: '0 auto' }}>
        <div
          ref={ref}
          className={`fade-in-up${visible ? ' visible' : ''}`}
          style={{ textAlign: 'center', marginBottom: 72 }}
        >
          <div style={{
            display: 'inline-block', fontSize: 11, color: D.gold, fontWeight: 600,
            letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: 16,
          }}>Why K9 Operations</div>
          <h2 style={{
            fontFamily: "'Playfair Display', Georgia, serif",
            fontSize: 40, fontWeight: 700, color: D.text,
            letterSpacing: '-0.02em', margin: '0 0 16px',
          }}>Built Different. By Design.</h2>
          <p style={{ fontSize: 17, color: D.textSec, maxWidth: 520, margin: '0 auto', lineHeight: 1.7 }}>
            Three principles that define every decision we make.
          </p>
        </div>

        <div className="features-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 24 }}>
          {pillars.map((p, i) => (
            <div
              key={i}
              className={`feature-card fade-in-up delay-${i + 1}`}
            >
              <div style={{
                width: 52, height: 52, borderRadius: '50%',
                background: D.goldGlow,
                border: `1px solid rgba(175,141,84,0.2)`,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                marginBottom: 24,
              }}>
                {p.icon}
              </div>
              <h3 style={{
                fontFamily: "'Playfair Display', Georgia, serif",
                fontSize: 20, fontWeight: 700, color: D.text,
                margin: '0 0 12px', letterSpacing: '-0.01em',
              }}>{p.title}</h3>
              <p style={{ fontSize: 15, color: D.textSec, lineHeight: 1.75, margin: 0 }}>{p.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ─── Roadmap Preview ──────────────────────────────────────────────────────────

function RoadmapPreview() {
  const [ref, visible] = useFadeIn();

  const cards = [
    {
      tag: 'Core Platform',
      title: 'Customer Lifecycle Overhaul',
      desc: '8 features being rebuilt from the ground up for deeper client relationship intelligence.',
    },
    {
      tag: 'Integrations',
      title: 'Gingr Data Expansion',
      desc: 'New sync tables and API integrations to bring more of your Gingr data into K9 Operations.',
    },
    {
      tag: 'CRM',
      title: 'Ignite CRM Integration',
      desc: 'Lead management and follow-up automation connected directly to your operations workflow.',
    },
    {
      tag: 'Enterprise',
      title: 'Enterprise Analytics',
      desc: 'Cross-location performance dashboards with unified reporting and benchmarking.',
    },
  ];

  return (
    <section id="roadmap" style={{ padding: '120px 24px', background: D.bgAlt }}>
      <div style={{ maxWidth: 1200, margin: '0 auto' }}>
        <div
          ref={ref}
          className={`fade-in-up${visible ? ' visible' : ''}`}
          style={{ textAlign: 'center', marginBottom: 72 }}
        >
          <div style={{
            display: 'inline-block', fontSize: 11, color: D.gold, fontWeight: 600,
            letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: 16,
          }}>What's Coming</div>
          <h2 style={{
            fontFamily: "'Playfair Display', Georgia, serif",
            fontSize: 40, fontWeight: 700, color: D.text,
            letterSpacing: '-0.02em', margin: '0 0 16px',
          }}>See What's Coming</h2>
          <p style={{ fontSize: 17, color: D.textSec, maxWidth: 480, margin: '0 auto', lineHeight: 1.7 }}>
            We ship in the open. Here's a preview of what's actively in development.
          </p>
        </div>

        <div className="roadmap-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 20, marginBottom: 48 }}>
          {cards.map((c, i) => (
            <div
              key={i}
              className={`roadmap-card fade-in-up delay-${i % 3 + 1}`}
            >
              <div style={{
                display: 'inline-flex', alignItems: 'center',
                background: D.goldGlow, borderRadius: 5, padding: '4px 10px',
                marginBottom: 16,
              }}>
                <span style={{ fontSize: 10, color: D.gold, fontWeight: 600, letterSpacing: '0.06em', textTransform: 'uppercase' }}>
                  {c.tag}
                </span>
              </div>
              <h4 style={{
                fontFamily: "'Playfair Display', Georgia, serif",
                fontSize: 17, fontWeight: 700, color: D.text,
                margin: '0 0 10px', letterSpacing: '-0.01em', lineHeight: 1.3,
              }}>{c.title}</h4>
              <p style={{ fontSize: 13, color: D.textSec, margin: 0, lineHeight: 1.7 }}>{c.desc}</p>
            </div>
          ))}
        </div>

        <div style={{ textAlign: 'center' }}>
          <button
            className="btn-gold"
            onClick={() => { window.location.href = '/public-roadmap'; }}
          >
            View Full Roadmap →
          </button>
        </div>
      </div>
    </section>
  );
}

// ─── Footer ───────────────────────────────────────────────────────────────────

function Footer({ onLegal }) {
  const year = 2026;

  const footerLinks = [
    { label: 'Features', action: () => { document.getElementById('features')?.scrollIntoView({ behavior: 'smooth' }); } },
    { label: 'Products', action: () => { document.getElementById('products')?.scrollIntoView({ behavior: 'smooth' }); } },
    { label: 'Roadmap', action: () => { window.location.href = '/public-roadmap'; } },
    { label: 'Log In', action: () => { window.location.href = '/login'; } },
  ];

  return (
    <footer style={{ background: D.bgAlt, borderTop: `1px solid ${D.border}` }}>
      {/* Main footer */}
      <div style={{ maxWidth: 1200, margin: '0 auto', padding: '64px 24px 48px' }}>
        <div
          className="footer-grid"
          style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 40 }}
        >
          {/* Logo + tagline */}
          <div style={{ minWidth: 200 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 14 }}>
              <ConstellationLogo size={28} />
              <span style={{
                fontFamily: "'Playfair Display', Georgia, serif",
                fontSize: 17, fontWeight: 700, color: D.text,
              }}>K9 Operations</span>
            </div>
            <p style={{ fontSize: 13, color: D.textMut, lineHeight: 1.7, margin: 0, maxWidth: 220 }}>
              Purpose-built software for luxury pet resorts that refuse to compromise.
            </p>
          </div>

          {/* Center links */}
          <div className="footer-links" style={{ display: 'flex', gap: 32, alignItems: 'flex-start' }}>
            {footerLinks.map(link => (
              <button
                key={link.label}
                onClick={link.action}
                style={{
                  background: 'none', border: 'none', color: D.textSec,
                  fontSize: 14, fontWeight: 500, cursor: 'pointer',
                  fontFamily: 'inherit', padding: 0, transition: 'color 0.2s',
                }}
                onMouseEnter={e => e.target.style.color = D.text}
                onMouseLeave={e => e.target.style.color = D.textSec}
              >
                {link.label}
              </button>
            ))}
          </div>

          {/* Right: location */}
          <div style={{ textAlign: 'right' }}>
            <div style={{ fontSize: 13, color: D.textMut, marginBottom: 8 }}>Made in Cherry Hill, NJ</div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 6, justifyContent: 'flex-end' }}>
              <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#4E9E6B' }} />
              <span style={{ fontSize: 12, color: '#4E9E6B', fontWeight: 500 }}>All systems operational</span>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom bar */}
      <div style={{ borderTop: `1px solid ${D.border}` }}>
        <div
          className="two-col-footer"
          style={{
            maxWidth: 1200, margin: '0 auto', padding: '20px 24px',
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            gap: 16,
          }}
        >
          <span style={{ fontSize: 12, color: D.textMut }}>
            © {year} K9 Operations LLC. All Rights Reserved.
          </span>
          <div style={{ display: 'flex', alignItems: 'center', gap: 20 }}>
            <button
              onClick={() => onLegal('tos')}
              style={{
                background: 'none', border: 'none', color: D.textMut,
                fontSize: 12, cursor: 'pointer', fontFamily: 'inherit',
                padding: 0, transition: 'color 0.2s',
                textDecoration: 'underline', textDecorationColor: `${D.textMut}44`,
              }}
              onMouseEnter={e => e.target.style.color = D.textSec}
              onMouseLeave={e => e.target.style.color = D.textMut}
            >Terms of Service</button>
            <span style={{ color: D.border }}>|</span>
            <button
              onClick={() => onLegal('privacy')}
              style={{
                background: 'none', border: 'none', color: D.textMut,
                fontSize: 12, cursor: 'pointer', fontFamily: 'inherit',
                padding: 0, transition: 'color 0.2s',
                textDecoration: 'underline', textDecorationColor: `${D.textMut}44`,
              }}
              onMouseEnter={e => e.target.style.color = D.textSec}
              onMouseLeave={e => e.target.style.color = D.textMut}
            >Privacy Policy</button>
            <span style={{ color: D.border }}>|</span>
            <a
              href="https://www.perplexity.ai/computer"
              target="_blank"
              rel="noopener noreferrer"
              style={{ fontSize: 12, color: D.textMut, textDecoration: 'none', transition: 'color 0.2s' }}
              onMouseEnter={e => e.target.style.color = D.textSec}
              onMouseLeave={e => e.target.style.color = D.textMut}
            >
              Created with Perplexity Computer
            </a>
          </div>
        </div>
      </div>
    </footer>
  );
}

// ─── Main Export ──────────────────────────────────────────────────────────────

export default function LandingPage() {
  const [legalModal, setLegalModal] = useState(null);

  return (
    <div style={{ background: D.bg, minHeight: '100vh', fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'Inter', sans-serif" }}>
      <Nav />
      <Hero />
      <Products />
      <Features />
      <RoadmapPreview />
      <Footer onLegal={setLegalModal} />
      {legalModal && <LegalModal type={legalModal} onClose={() => setLegalModal(null)} />}
    </div>
  );
}
