// © 2026 K9 Operations LLC. All Rights Reserved.
// Proprietary and Confidential.

import React, { useState, useEffect, useRef } from 'react';

// ─── Light Theme Colors ────────────────────────────────────────────────────────
const C = {
  bg: '#FFFFFF',
  bgAlt: '#F7FEE7',
  surface: '#FFFFFF',
  surfaceAlt: '#F8FAFC',
  border: '#E2E8F0',
  borderLight: '#F1F5F9',
  text: '#0F172A',
  textSec: '#475569',
  textMut: '#64748B',
  pri: '#14532D',
  priL: '#166534',
  acc: '#84CC16',
  accLt: '#D9F99D',
  accDk: '#4D7C0F',
  success: '#16A34A',
  successLight: '#ECFDF5',
};

// ─── Legal Data ───────────────────────────────────────────────────────────────
const TOS_SECTIONS = [
  { t: "1. Definitions", b: "\"Company\" refers to K9 Operations LLC, a New Jersey limited liability company. \"Service\" refers to the K9 Operations cloud-based software platform. \"Customer\" refers to the pet care facility or business entity that subscribes. \"User\" refers to any individual who accesses the Service. \"Customer Data\" refers to all data uploaded or generated by Users through the Service." },
  { t: "2. Description of Service", b: "K9 Operations provides a cloud-based SaaS platform for pet care facility management, including pet profile management, booking and scheduling, feeding and medication tracking, report cards, employee scheduling, and invoicing." },
  { t: "3. Account Registration and Security", b: "Customers must create an account and designate at least one administrator. You are responsible for providing accurate registration information, managing user accounts and access levels, maintaining the confidentiality of login credentials, and all activities that occur under your account." },
  { t: "4. Permitted Use and Restrictions", b: "You receive a limited, non-exclusive, non-transferable right to use the Service for your pet care facility operations. You may not copy, modify, distribute, sell, reverse engineer, scrape, or attempt unauthorized access to the Service." },
  { t: "5. Intellectual Property", b: "The Service is the exclusive property of K9 Operations LLC, protected by U.S. copyright and trademark laws. Copyright Registration filed February 9, 2026. All rights not expressly granted are reserved." },
  { t: "6. Customer Data", b: "You retain ownership of your Customer Data. You grant K9 Operations a limited license to host, store, and process your data solely to provide the Service. We will not access or disclose your data except as necessary to provide the Service or as required by law." },
  { t: "7. Service Availability", b: "We target 99.9% monthly uptime, excluding scheduled maintenance. Scheduled maintenance will be communicated at least 48 hours in advance when practicable." },
  { t: "8. Fees and Payment", b: "Access requires a paid subscription. Pricing and terms are established in your SaaS License Agreement. We may modify pricing with at least 60 days written notice." },
  { t: "9. Term and Termination", b: "Upon termination, you have 30 days to request a data export (CSV or JSON). After 30 days, Customer Data may be deleted. Outstanding fees remain due." },
  { t: "10. Disclaimers and Limitation of Liability", b: "THE SERVICE IS PROVIDED \"AS IS\" WITHOUT WARRANTIES. We make no representations regarding pet health outcomes. Our total aggregate liability shall not exceed fees paid in the preceding 12 months." },
  { t: "11. Indemnification", b: "You agree to indemnify K9 Operations LLC against claims arising from your use of the Service, violation of these Terms, or your operation of a pet care facility." },
  { t: "12. Governing Law", b: "These Terms are governed by New Jersey law. Disputes shall be resolved in Burlington County, NJ courts." },
  { t: "13. Changes to Terms", b: "We will provide at least 30 days notice for material changes. Continued use constitutes acceptance of modified Terms." },
  { t: "14. Contact", b: "Questions? Contact us at zack.nisbet@k9operations.com" },
];

const PRIVACY_SECTIONS = [
  { t: "1. Information We Collect", b: "We collect account information (business name, contact details, employee info), pet and client data (pet profiles, vaccination records, medical notes, emergency contacts), booking and service data (reservations, feeding logs, report cards, invoices), employee data (names, roles, schedules), usage data (IP address, browser type, pages viewed), and session cookies for authentication." },
  { t: "2. How We Use Your Information", b: "We use your information to provide and operate the Service, communicate with you, improve the platform, ensure security, and comply with legal obligations. We do not use Customer Data to train machine learning models." },
  { t: "3. How We Share Your Information", b: "We do not sell, rent, or trade your personal information. We share data only with service providers (Supabase for database hosting, Vercel for application hosting, payment processors), when required by law, or in connection with a business transfer." },
  { t: "4. Data Security", b: "All data is encrypted at rest (AES-256) and in transit (TLS 1.2+). We use role-based access controls and hashed passwords. We do not store credit card numbers or sensitive payment credentials." },
  { t: "5. Data Retention", b: "We retain data while your account is active. After termination, you have 30 days to export your data. Customer Data is deleted within 90 days of the export period, unless retention is required by law." },
  { t: "6. Your Rights", b: "You may request access to, correction of, or deletion of your personal information. You may request data export in CSV or JSON format. You may opt out of marketing communications at any time. Contact zack.nisbet@k9operations.com to exercise these rights." },
  { t: "7. Children's Privacy", b: "The Service is not directed to children under 13. We do not knowingly collect personal information from children under 13." },
  { t: "8. Changes to This Policy", b: "We will notify you of material changes via email or in-app notification. Changes become effective 30 days after posting unless stated otherwise." },
  { t: "9. Contact", b: "For privacy inquiries: zack.nisbet@k9operations.com" },
];

// ─── SVG Icons (inline) ───────────────────────────────────────────────────────
const Icon = ({ name, size = 24, color = 'currentColor' }) => {
  const icons = {
    lifecycle: <><circle cx="12" cy="12" r="9" fill="none" stroke={color} strokeWidth="1.5"/><path d="M12 3c5 0 9 4 9 9" fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round"/><path d="M21 12c0 5-4 9-9 9" fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round" strokeDasharray="3 2"/><circle cx="12" cy="12" r="3" fill={color} opacity="0.2"/><circle cx="12" cy="12" r="1.5" fill={color}/></>,
    ops: <><rect x="3" y="3" width="18" height="18" rx="3" fill="none" stroke={color} strokeWidth="1.5"/><path d="M8 9.5h8M8 12.5h6M8 15.5h4" stroke={color} strokeWidth="1.5" strokeLinecap="round"/><circle cx="5.5" cy="9.5" r="0.75" fill={color}/><circle cx="5.5" cy="12.5" r="0.75" fill={color}/><circle cx="5.5" cy="15.5" r="0.75" fill={color}/></>,
    tv: <><rect x="2" y="4" width="20" height="14" rx="2" fill="none" stroke={color} strokeWidth="1.5"/><path d="M8 21h8M12 18v3" stroke={color} strokeWidth="1.5" strokeLinecap="round"/><circle cx="8" cy="11" r="2" fill={color} opacity="0.15"/><circle cx="12" cy="11" r="2" fill={color} opacity="0.15"/><circle cx="16" cy="11" r="2" fill={color} opacity="0.15"/></>,
    reports: <><rect x="3" y="3" width="18" height="18" rx="2" fill="none" stroke={color} strokeWidth="1.5"/><path d="M7 14v3M11 10v7M15 12v5M19 8v9" stroke={color} strokeWidth="2" strokeLinecap="round"/></>,
    funnel: <><path d="M3 4h18l-6 7v5l-6 3V11L3 4z" fill={color} opacity="0.1" stroke={color} strokeWidth="1.5" strokeLinejoin="round"/></>,
    shield: <><path d="M12 2l8 4v5c0 5.25-3.5 9.74-8 11-4.5-1.26-8-5.75-8-11V6l8-4z" fill={color} opacity="0.1" stroke={color} strokeWidth="1.5"/><path d="M9 12l2 2 4-4" fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
    arrow: <><path d="M5 12h14M13 6l6 6-6 6" fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
    check: <><path d="M5 12l5 5L20 7" fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></>,
    star: <><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" fill={color} opacity="0.15" stroke={color} strokeWidth="1.5" strokeLinejoin="round"/></>,
    sync: <><path d="M4 12a8 8 0 0114.93-4M20 12a8 8 0 01-14.93 4" fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round"/><path d="M20 4v4h-4M4 20v-4h4" fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></>,
    menu: <><path d="M4 6h16M4 12h16M4 18h16" stroke={color} strokeWidth="1.5" strokeLinecap="round"/></>,
    close: <><path d="M6 6l12 12M18 6L6 18" stroke={color} strokeWidth="1.5" strokeLinecap="round"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none">{icons[name]}</svg>;
};

// ─── K9 Operations Logo ──────────────────────────────────────────────────────
const K9Logo = ({ size = 36 }) => (
  <div style={{ display: 'inline-flex', alignItems: 'center', gap: 10 }}>
    <img src="/k9_mark.svg" alt="" aria-hidden="true" style={{ height: size, width: size }} />
    <span style={{
      fontSize: Math.max(14, Math.round(size * 0.46)),
      fontWeight: 800,
      color: C.pri,
      lineHeight: 1,
      letterSpacing: 0,
    }}>
      K9 Operations
    </span>
  </div>
);


// ═══════════════════════════════════════════════════════════════════════════════
// DATA FLOW ANIMATION — The Centerpiece
// Gingr (top) → K9 Operations (middle) → Old / Conversion / Retention (bottom)
// ═══════════════════════════════════════════════════════════════════════════════
function DataFlowAnimation() {
  const canvasRef = useRef(null);
  const animRef = useRef(null);
  const [isVisible, setIsVisible] = useState(false);
  const sectionRef = useRef(null);

  useEffect(() => {
    const obs = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) { setIsVisible(true); obs.disconnect(); }},
      { threshold: 0.2 }
    );
    if (sectionRef.current) obs.observe(sectionRef.current);
    return () => obs.disconnect();
  }, []);

  useEffect(() => {
    if (!isVisible || !canvasRef.current) return;
    const canvas = canvasRef.current;
    const ctx = canvas.getContext('2d');
    const dpr = window.devicePixelRatio || 1;

    const resize = () => {
      const rect = canvas.getBoundingClientRect();
      canvas.width = rect.width * dpr;
      canvas.height = rect.height * dpr;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    };
    resize();
    window.addEventListener('resize', resize);

    // Node positions (responsive)
    const getLayout = () => {
      const w = canvas.getBoundingClientRect().width;
      const h = canvas.getBoundingClientRect().height;
      const cx = w / 2;

      const gingrNode = { x: cx, y: 60, label: 'Gingr', sub: 'PMS Data Source', color: '#6366F1', radius: 44 };
      const k9Node = { x: cx, y: h * 0.42, label: 'K9 Ops', sub: 'Intelligence Layer', color: C.pri, radius: 50 };

      const spacing = Math.min(w * 0.28, 180);
      const bottomY = h * 0.82;
      const oldNode = { x: cx - spacing, y: bottomY, label: 'Cold', sub: 'Re-engagement', color: '#64748B', radius: 36 };
      const convNode = { x: cx, y: bottomY, label: 'Leads', sub: 'New Leads', color: '#10B981', radius: 36 };
      const retNode = { x: cx + spacing, y: bottomY, label: 'Lapsed', sub: 'Lapsed Clients', color: '#F59E0B', radius: 36 };

      return { gingrNode, k9Node, oldNode, convNode, retNode, w, h };
    };

    // Orbs
    const orbs = [];
    let orbIdCounter = 0;

    const spawnOrb = (from, to, color, delay = 0) => {
      orbs.push({
        id: orbIdCounter++,
        fromX: from.x, fromY: from.y,
        toX: to.x, toY: to.y,
        progress: -delay,
        speed: 0.008 + Math.random() * 0.004,
        color,
        radius: 4 + Math.random() * 3,
        trail: [],
      });
    };

    let lastSpawnTime = 0;

    const draw = (time) => {
      const layout = getLayout();
      const { gingrNode, k9Node, oldNode, convNode, retNode, w, h } = layout;
      ctx.clearRect(0, 0, w, h);

      // Draw connection lines
      const drawLine = (from, to, alpha = 0.12) => {
        ctx.beginPath();
        const midY = (from.y + to.y) / 2;
        ctx.moveTo(from.x, from.y + from.radius);
        ctx.bezierCurveTo(from.x, midY, to.x, midY, to.x, to.y - to.radius);
        ctx.strokeStyle = `rgba(20,83,45,${alpha})`;
        ctx.lineWidth = 2;
        ctx.setLineDash([6, 4]);
        ctx.stroke();
        ctx.setLineDash([]);
      };

      drawLine(gingrNode, k9Node, 0.15);
      drawLine(k9Node, oldNode, 0.1);
      drawLine(k9Node, convNode, 0.1);
      drawLine(k9Node, retNode, 0.1);

      // Draw nodes
      const drawNode = (node) => {
        // Glow
        const grad = ctx.createRadialGradient(node.x, node.y, 0, node.x, node.y, node.radius * 2);
        grad.addColorStop(0, node.color + '18');
        grad.addColorStop(1, node.color + '00');
        ctx.beginPath();
        ctx.arc(node.x, node.y, node.radius * 2, 0, Math.PI * 2);
        ctx.fillStyle = grad;
        ctx.fill();

        // Circle
        ctx.beginPath();
        ctx.arc(node.x, node.y, node.radius, 0, Math.PI * 2);
        ctx.fillStyle = '#fff';
        ctx.fill();
        ctx.strokeStyle = node.color + '40';
        ctx.lineWidth = 2;
        ctx.stroke();

        // Inner circle
        ctx.beginPath();
        ctx.arc(node.x, node.y, node.radius * 0.6, 0, Math.PI * 2);
        ctx.fillStyle = node.color + '12';
        ctx.fill();

        // Label
        ctx.fillStyle = node.color;
        ctx.font = `700 ${node.radius > 40 ? 14 : 11}px 'Outfit', system-ui, sans-serif`;
        ctx.textAlign = 'center';
        ctx.fillText(node.label, node.x, node.y + (node.radius > 40 ? 5 : 4));

        // Sub-label
        ctx.fillStyle = C.textMut;
        ctx.font = `500 ${node.radius > 40 ? 11 : 9}px 'Outfit', system-ui, sans-serif`;
        ctx.fillText(node.sub, node.x, node.y + node.radius + 16);
      };

      drawNode(gingrNode);
      drawNode(k9Node);
      drawNode(oldNode);
      drawNode(convNode);
      drawNode(retNode);

      // Spawn orbs periodically
      if (time - lastSpawnTime > 1200) {
        lastSpawnTime = time;
        // Gingr → K9
        spawnOrb(gingrNode, k9Node, '#6366F1', 0);
        // K9 → bottom nodes (staggered)
        spawnOrb(k9Node, convNode, '#10B981', 0.35);
        spawnOrb(k9Node, retNode, '#F59E0B', 0.5);
        spawnOrb(k9Node, oldNode, '#64748B', 0.65);
      }

      // Update and draw orbs
      for (let i = orbs.length - 1; i >= 0; i--) {
        const orb = orbs[i];
        orb.progress += orb.speed;

        if (orb.progress < 0) continue;
        if (orb.progress > 1) { orbs.splice(i, 1); continue; }

        const t = orb.progress;
        const midY = (orb.fromY + orb.toY) / 2;
        // Bezier interpolation
        const mt = 1 - t;
        const x = mt*mt*mt*orb.fromX + 3*mt*mt*t*orb.fromX + 3*mt*t*t*orb.toX + t*t*t*orb.toX;
        const y = mt*mt*mt*orb.fromY + 3*mt*mt*t*midY + 3*mt*t*t*midY + t*t*t*orb.toY;

        // Trail
        orb.trail.push({ x, y, alpha: 1 });
        if (orb.trail.length > 12) orb.trail.shift();

        // Draw trail
        orb.trail.forEach((pt, idx) => {
          const a = (idx / orb.trail.length) * 0.4;
          ctx.beginPath();
          ctx.arc(pt.x, pt.y, orb.radius * (idx / orb.trail.length) * 0.7, 0, Math.PI * 2);
          ctx.fillStyle = orb.color + Math.round(a * 255).toString(16).padStart(2, '0');
          ctx.fill();
        });

        // Draw orb with glow
        const orbGrad = ctx.createRadialGradient(x, y, 0, x, y, orb.radius * 3);
        orbGrad.addColorStop(0, orb.color + '60');
        orbGrad.addColorStop(1, orb.color + '00');
        ctx.beginPath();
        ctx.arc(x, y, orb.radius * 3, 0, Math.PI * 2);
        ctx.fillStyle = orbGrad;
        ctx.fill();

        ctx.beginPath();
        ctx.arc(x, y, orb.radius, 0, Math.PI * 2);
        ctx.fillStyle = orb.color;
        ctx.fill();

        // White core
        ctx.beginPath();
        ctx.arc(x, y, orb.radius * 0.4, 0, Math.PI * 2);
        ctx.fillStyle = '#fff';
        ctx.fill();
      }

      animRef.current = requestAnimationFrame(draw);
    };

    animRef.current = requestAnimationFrame(draw);

    return () => {
      cancelAnimationFrame(animRef.current);
      window.removeEventListener('resize', resize);
    };
  }, [isVisible]);

  return (
    <div ref={sectionRef} style={{ position: 'relative', width: '100%', maxWidth: 600, margin: '0 auto' }}>
      <canvas
        ref={canvasRef}
        style={{ width: '100%', height: 420, display: 'block' }}
      />
    </div>
  );
}


// ═══════════════════════════════════════════════════════════════════════════════
// FEATURE SECTIONS
// ═══════════════════════════════════════════════════════════════════════════════

function FeatureSection({ icon, title, subtitle, description, bullets, reversed, accentColor }) {
  return (
    <div style={{
      display: 'flex', flexDirection: reversed ? 'row-reverse' : 'row',
      gap: 64, alignItems: 'center', padding: '80px 0',
      flexWrap: 'wrap',
    }}>
      {/* Text side */}
      <div style={{ flex: 1, minWidth: 320 }}>
        <div style={{
          display: 'inline-flex', alignItems: 'center', gap: 8,
          padding: '6px 14px', borderRadius: 100,
          background: accentColor + '10', marginBottom: 16,
        }}>
          <Icon name={icon} size={16} color={accentColor} />
          <span style={{ fontSize: 12, fontWeight: 700, color: accentColor, letterSpacing: '0.06em', textTransform: 'uppercase' }}>{subtitle}</span>
        </div>
        <h3 style={{ fontSize: 32, fontWeight: 800, color: C.text, lineHeight: 1.2, margin: '0 0 16px' }}>{title}</h3>
        <p style={{ fontSize: 17, color: C.textSec, lineHeight: 1.7, margin: '0 0 24px' }}>{description}</p>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {bullets.map((b, i) => (
            <div key={i} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
              <div style={{
                width: 22, height: 22, borderRadius: 6, flexShrink: 0, marginTop: 1,
                background: accentColor + '12',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}>
                <Icon name="check" size={13} color={accentColor} />
              </div>
              <span style={{ fontSize: 15, color: C.textSec, lineHeight: 1.5 }}>{b}</span>
            </div>
          ))}
        </div>
      </div>
      {/* Visual side — abstract graphic */}
      <div style={{
        flex: 1, minWidth: 320, minHeight: 340,
        background: `linear-gradient(135deg, ${accentColor}08 0%, ${accentColor}03 100%)`,
        borderRadius: 24, border: `1px solid ${accentColor}15`,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        position: 'relative', overflow: 'hidden',
      }}>
        <FeatureGraphic type={icon} color={accentColor} />
      </div>
    </div>
  );
}

// Abstract feature graphics (no fake screenshots)
function FeatureGraphic({ type, color }) {
  if (type === 'lifecycle') {
    // Premium horizontal pipeline: Gingr → K9 Ops → Conversion → Active ↔ Retention
    // Customer NEVER goes back to New/Conversion. Active ↔ Retention is the ONLY bidirectional flow.
    const navy = '#14532D';
    const gold = '#84CC16';
    const teal = '#0EA5E9';
    const green = '#10B981';

    // Stage definitions for the flow
    const stages = [
      { id: 'gingr', label: 'Gingr', sub: 'Data Source', x: 30, y: 95, color: '#6366F1', icon: 'db' },
      { id: 'k9ops', label: 'K9 Ops', sub: 'Intelligence', x: 120, y: 95, color: navy, icon: 'hub', isHub: true },
      { id: 'conv', label: 'Leads', sub: 'New Leads', x: 210, y: 95, color: green, icon: 'funnel' },
      { id: 'active', label: 'Active', sub: 'Engaged', x: 300, y: 55, color: teal, icon: 'bolt' },
      { id: 'lapsed', label: 'Lapsed', sub: 'Re-engage', x: 300, y: 135, color: gold, icon: 'refresh' },
    ];

    return (
      <svg width="380" height="200" viewBox="0 0 380 200" fill="none" style={{ maxWidth: '100%', height: 'auto' }}>
        <defs>
          {/* Glow filters */}
          <filter id="lcGlow" x="-50%" y="-50%" width="200%" height="200%">
            <feGaussianBlur in="SourceGraphic" stdDeviation="6" result="blur"/>
            <feComposite in="SourceGraphic" in2="blur" operator="over"/>
          </filter>
          <filter id="lcSoftGlow" x="-30%" y="-30%" width="160%" height="160%">
            <feGaussianBlur in="SourceAlpha" stdDeviation="3" result="blur"/>
            <feFlood floodColor={navy} floodOpacity="0.15" result="color"/>
            <feComposite in="color" in2="blur" operator="in" result="shadow"/>
            <feComposite in="SourceGraphic" in2="shadow" operator="over"/>
          </filter>
          {/* Gradient for connection lines */}
          <linearGradient id="lcLineGrad" x1="0%" y1="0%" x2="100%" y2="0%">
            <stop offset="0%" stopColor={navy} stopOpacity="0.15"/>
            <stop offset="50%" stopColor={navy} stopOpacity="0.3"/>
            <stop offset="100%" stopColor={navy} stopOpacity="0.15"/>
          </linearGradient>
          {/* Hub radial gradient */}
          <radialGradient id="lcHubGrad" cx="50%" cy="50%" r="50%">
            <stop offset="0%" stopColor={navy} stopOpacity="0.08"/>
            <stop offset="100%" stopColor={navy} stopOpacity="0.02"/>
          </radialGradient>
          {/* Arrow markers */}
          <marker id="lcArrow" viewBox="0 0 8 6" refX="7" refY="3" markerWidth="8" markerHeight="6" orient="auto">
            <path d="M0 0 L8 3 L0 6Z" fill={navy} opacity="0.35"/>
          </marker>
          <marker id="lcArrowGold" viewBox="0 0 8 6" refX="7" refY="3" markerWidth="8" markerHeight="6" orient="auto">
            <path d="M0 0 L8 3 L0 6Z" fill={gold} opacity="0.45"/>
          </marker>
          <marker id="lcArrowTeal" viewBox="0 0 8 6" refX="7" refY="3" markerWidth="8" markerHeight="6" orient="auto">
            <path d="M0 0 L8 3 L0 6Z" fill={teal} opacity="0.45"/>
          </marker>
        </defs>

        {/* Background decoration — subtle grid dots */}
        {Array.from({ length: 12 }).map((_, i) =>
          Array.from({ length: 6 }).map((_, j) => (
            <circle key={`dot-${i}-${j}`} cx={20 + i * 32} cy={15 + j * 32} r="0.8" fill={navy} opacity="0.06"/>
          ))
        )}

        {/* ── Connection Lines ── */}
        {/* Gingr → K9 Ops */}
        <line x1="62" y1="95" x2="90" y2="95" stroke={navy} strokeWidth="1.5" strokeOpacity="0.2" strokeDasharray="4 3"/>
        <circle r="3" fill="#6366F1" opacity="0.6">
          <animateMotion dur="2s" repeatCount="indefinite" path="M62,95 L90,95"/>
          <animate attributeName="opacity" values="0;0.7;0" dur="2s" repeatCount="indefinite"/>
        </circle>

        {/* K9 Ops → Conversion */}
        <line x1="152" y1="95" x2="182" y2="95" stroke={navy} strokeWidth="1.8" strokeOpacity="0.25" markerEnd="url(#lcArrow)"/>
        <circle r="3" fill={navy} opacity="0.5">
          <animateMotion dur="1.8s" repeatCount="indefinite" path="M152,95 L182,95"/>
          <animate attributeName="opacity" values="0;0.6;0" dur="1.8s" repeatCount="indefinite"/>
        </circle>

        {/* Conversion → Active (curves up) */}
        <path d="M238 82 C260 60, 270 55, 280 55" fill="none" stroke={green} strokeWidth="1.5" strokeOpacity="0.25" markerEnd="url(#lcArrowTeal)"/>
        <circle r="2.5" fill={green} opacity="0.5">
          <animateMotion dur="2.2s" repeatCount="indefinite" path="M238,82 C260,60 270,55 280,55"/>
          <animate attributeName="opacity" values="0;0.6;0" dur="2.2s" repeatCount="indefinite"/>
        </circle>

        {/* Conversion → Retention (curves down) */}
        <path d="M238 108 C260 130, 270 135, 280 135" fill="none" stroke={green} strokeWidth="1.5" strokeOpacity="0.2" markerEnd="url(#lcArrowGold)"/>
        <circle r="2.5" fill={green} opacity="0.4">
          <animateMotion dur="2.5s" repeatCount="indefinite" path="M238,108 C260,130 270,135 280,135"/>
          <animate attributeName="opacity" values="0;0.5;0" dur="2.5s" repeatCount="indefinite"/>
        </circle>

        {/* Active ↔ Retention (bidirectional — the ONLY bidirectional flow) */}
        {/* Active → Retention */}
        <line x1="310" y1="73" x2="310" y2="117" stroke={teal} strokeWidth="1.5" strokeOpacity="0.25" markerEnd="url(#lcArrowGold)"/>
        <circle r="2.5" fill={teal} opacity="0.5">
          <animateMotion dur="2s" repeatCount="indefinite" path="M310,73 L310,117"/>
          <animate attributeName="opacity" values="0;0.6;0" dur="2s" repeatCount="indefinite"/>
        </circle>
        {/* Retention → Active */}
        <line x1="290" y1="117" x2="290" y2="73" stroke={gold} strokeWidth="1.5" strokeOpacity="0.25" markerEnd="url(#lcArrowTeal)"/>
        <circle r="2.5" fill={gold} opacity="0.5">
          <animateMotion dur="2.3s" repeatCount="indefinite" path="M290,117 L290,73" begin="0.8s"/>
          <animate attributeName="opacity" values="0;0.6;0" dur="2.3s" repeatCount="indefinite" begin="0.8s"/>
        </circle>
        {/* Bidirectional label */}
        <text x="340" y="98" fontSize="6.5" fontWeight="600" fill={navy} opacity="0.35" textAnchor="middle">↕</text>

        {/* ── Stage Nodes ── */}
        {stages.map((s) => {
          const isHub = s.isHub;
          const r = isHub ? 30 : 24;
          return (
            <g key={s.id}>
              {/* Card background */}
              <rect
                x={s.x - r} y={s.y - r} width={r * 2} height={r * 2}
                rx={isHub ? 16 : 12}
                fill="#FFFFFF"
                stroke={s.color}
                strokeWidth={isHub ? 2 : 1.5}
                strokeOpacity={isHub ? 0.6 : 0.3}
                filter={isHub ? 'url(#lcSoftGlow)' : undefined}
              />
              {/* Inner accent fill */}
              <rect
                x={s.x - r + 2} y={s.y - r + 2} width={r * 2 - 4} height={r * 2 - 4}
                rx={isHub ? 14 : 10}
                fill={s.color}
                opacity={isHub ? 0.06 : 0.04}
              />
              {/* Icon area */}
              {s.icon === 'db' && (
                <g transform={`translate(${s.x - 6},${s.y - 14})`}>
                  <ellipse cx="6" cy="3" rx="6" ry="3" fill="none" stroke={s.color} strokeWidth="1.2" opacity="0.6"/>
                  <path d="M0 3v6c0 1.7 2.7 3 6 3s6-1.3 6-3V3" fill="none" stroke={s.color} strokeWidth="1.2" opacity="0.6"/>
                  <path d="M0 6c0 1.7 2.7 3 6 3s6-1.3 6-3" fill="none" stroke={s.color} strokeWidth="1" opacity="0.35"/>
                </g>
              )}
              {s.icon === 'hub' && (
                <g transform={`translate(${s.x},${s.y - 12})`}>
                  <circle cx="0" cy="0" r="3" fill={s.color} opacity="0.5"/>
                  <circle cx="-8" cy="6" r="2" fill={s.color} opacity="0.3"/>
                  <circle cx="8" cy="6" r="2" fill={s.color} opacity="0.3"/>
                  <line x1="0" y1="0" x2="-8" y2="6" stroke={s.color} strokeWidth="0.8" opacity="0.3"/>
                  <line x1="0" y1="0" x2="8" y2="6" stroke={s.color} strokeWidth="0.8" opacity="0.3"/>
                  <circle cx="0" cy="0" r="6" fill="none" stroke={s.color} strokeWidth="0.6" opacity="0.15">
                    <animate attributeName="r" values="6;10;6" dur="3s" repeatCount="indefinite"/>
                    <animate attributeName="opacity" values="0.15;0;0.15" dur="3s" repeatCount="indefinite"/>
                  </circle>
                </g>
              )}
              {s.icon === 'funnel' && (
                <g transform={`translate(${s.x - 5},${s.y - 14})`}>
                  <path d="M0 0h10l-3 6v4l-4 0v-4z" fill="none" stroke={s.color} strokeWidth="1.2" opacity="0.5"/>
                </g>
              )}
              {s.icon === 'bolt' && (
                <g transform={`translate(${s.x - 4},${s.y - 14})`}>
                  <path d="M5 0L1 6h3l-1 6 5-7H5z" fill={s.color} opacity="0.4"/>
                </g>
              )}
              {s.icon === 'refresh' && (
                <g transform={`translate(${s.x},${s.y - 12})`}>
                  <path d="M4-1A5 5 0 1 1-3 3" fill="none" stroke={s.color} strokeWidth="1.2" opacity="0.5" strokeLinecap="round"/>
                  <path d="M-3 0v3h3" fill="none" stroke={s.color} strokeWidth="1.2" opacity="0.5" strokeLinecap="round"/>
                </g>
              )}
              {/* Label */}
              <text x={s.x} y={s.y + (isHub ? 8 : 6)} textAnchor="middle" fontSize={isHub ? '8.5' : '7.5'} fontWeight="700" fill={s.color} letterSpacing="0.02em">{s.label}</text>
              {/* Subtitle */}
              <text x={s.x} y={s.y + (isHub ? 18 : 15)} textAnchor="middle" fontSize="6" fontWeight="500" fill={s.color} opacity="0.5">{s.sub}</text>

              {/* Hub pulse ring */}
              {isHub && (
                <>
                  <rect x={s.x - r} y={s.y - r} width={r * 2} height={r * 2} rx="16" fill="none" stroke={s.color} strokeWidth="1" opacity="0.2">
                    <animate attributeName="rx" values="16;20;16" dur="3s" repeatCount="indefinite"/>
                    <animate attributeName="opacity" values="0.2;0;0.2" dur="3s" repeatCount="indefinite"/>
                  </rect>
                </>
              )}
            </g>
          );
        })}

        {/* ── Flow direction indicators ── */}
        <text x="76" y="88" fontSize="6" fontWeight="600" fill="#6366F1" opacity="0.3">DATA</text>
        <text x="167" y="88" fontSize="6" fontWeight="600" fill={navy} opacity="0.3">STAGE</text>

        {/* "One-way" label between Conversion and Active/Retention fork */}
        <text x="258" y="92" fontSize="5.5" fontWeight="600" fill={navy} opacity="0.25" textAnchor="middle">ONE WAY →</text>

        {/* Bottom annotation */}
        <text x="190" y="188" textAnchor="middle" fontSize="7" fontWeight="600" fill={navy} opacity="0.2" letterSpacing="0.15em">CUSTOMER LIFECYCLE FLOW</text>
        <line x1="90" y1="192" x2="290" y2="192" stroke={navy} strokeWidth="0.5" opacity="0.08"/>
      </svg>
    );
  }

  if (type === 'ops') {
    return (
      <svg width="280" height="280" viewBox="0 0 280 280" fill="none">
        {/* Grid of checklist cards */}
        {[
          { x: 20, y: 20, w: 120, h: 70, label: 'Opening', pct: 100, c: '#10B981' },
          { x: 150, y: 20, w: 110, h: 70, label: 'Front-End', pct: 80, c: color },
          { x: 20, y: 100, w: 110, h: 70, label: 'Room Cleaning', pct: 60, c: '#F59E0B' },
          { x: 140, y: 100, w: 120, h: 70, label: 'Bathing', pct: 45, c: '#0EA5E9' },
          { x: 20, y: 180, w: 120, h: 70, label: 'Private Play', pct: 33, c: '#8B5CF6' },
          { x: 150, y: 180, w: 110, h: 70, label: 'Closing', pct: 0, c: '#64748B' },
        ].map((card, i) => (
          <g key={i}>
            <rect x={card.x} y={card.y} width={card.w} height={card.h} rx="12" fill="#fff" stroke={card.c + '30'} strokeWidth="1.5"/>
            <text x={card.x + 12} y={card.y + 24} fontSize="10" fontWeight="700" fill={C.text}>{card.label}</text>
            {/* Progress bar */}
            <rect x={card.x + 12} y={card.y + 36} width={card.w - 24} height="6" rx="3" fill={card.c + '15'}/>
            <rect x={card.x + 12} y={card.y + 36} width={(card.w - 24) * card.pct / 100} height="6" rx="3" fill={card.c}>
              <animate attributeName="width" from="0" to={(card.w - 24) * card.pct / 100} dur="1.5s" begin={`${i * 0.2}s`} fill="freeze"/>
            </rect>
            <text x={card.x + card.w - 12} y={card.y + 58} textAnchor="end" fontSize="9" fontWeight="600" fill={card.c}>{card.pct}%</text>
          </g>
        ))}
        {/* Daily Progress indicator */}
        <rect x="60" y="258" width="160" height="18" rx="9" fill={color + '10'}/>
        <text x="140" y="271" textAnchor="middle" fontSize="9" fontWeight="700" fill={color}>Daily Progress: 53%</text>
      </svg>
    );
  }

  if (type === 'tv') {
    return (
      <svg width="300" height="260" viewBox="0 0 300 260" fill="none">
        {/* Monitor frame */}
        <rect x="20" y="10" width="260" height="180" rx="12" fill="#14532D" stroke="#166534" strokeWidth="2"/>
        <rect x="120" y="195" width="60" height="12" rx="2" fill="#166534"/>
        <rect x="90" y="207" width="120" height="6" rx="3" fill="#166534"/>

        {/* Header */}
        <text x="40" y="38" fontSize="11" fontWeight="800" fill="#fff">K9 Adair Forsythe</text>
        <text x="40" y="50" fontSize="7" fontWeight="600" fill="#84CC16" letterSpacing="1">CHECKOUT BOARD</text>
        <text x="260" y="38" textAnchor="end" fontSize="14" fontWeight="900" fill="#fff">2:45 PM</text>

        {/* Dog cards */}
        {['Luna','Max','Bella','Rocky','Daisy','Cooper','Sadie','Duke'].map((name, i) => {
          const col = i % 4;
          const row = Math.floor(i / 4);
          const x = 35 + col * 58;
          const y = 65 + row * 62;
          const colors = ['#0EA5E9', '#84CC16', '#10B981', '#F59E0B', '#8B5CF6', '#EC4899', '#6366F1', '#14B8A6'];
          return (
            <g key={i}>
              <rect x={x} y={y} width="50" height="52" rx="8" fill="rgba(255,255,255,0.06)" stroke="rgba(255,255,255,0.08)" strokeWidth="1"/>
              <circle cx={x + 25} cy={y + 18} r="10" fill={colors[i] + '30'}/>
              <text x={x + 25} y={y + 22} textAnchor="middle" fontSize="10" fontWeight="800" fill={colors[i]}>{name[0]}</text>
              <text x={x + 25} y={y + 38} textAnchor="middle" fontSize="7" fontWeight="700" fill="#fff">{name}</text>
              <text x={x + 25} y={y + 47} textAnchor="middle" fontSize="5.5" fill="rgba(255,255,255,0.4)">Rm {i + 1}</text>
            </g>
          );
        })}
      </svg>
    );
  }

  if (type === 'reports') {
    return (
      <svg width="280" height="260" viewBox="0 0 280 260" fill="none">
        {/* NLP query bar */}
        <rect x="20" y="15" width="240" height="36" rx="18" fill="#fff" stroke={color + '30'} strokeWidth="1.5"/>
        <text x="40" y="37" fontSize="10" fill={C.textMut}>"Revenue by suite type"</text>
        <circle cx="240" cy="33" r="12" fill={color + '15'}/>
        <path d="M236 30l4 3-4 3" fill="none" stroke={color} strokeWidth="1.5" strokeLinecap="round"/>

        {/* Chart area */}
        <rect x="20" y="65" width="240" height="140" rx="12" fill="#fff" stroke="#E2E6ED" strokeWidth="1"/>
        {/* Bars */}
        {[
          { x: 50, h: 90, label: 'Standard', c: '#0EA5E9' },
          { x: 100, h: 110, label: 'Deluxe', c: color },
          { x: 150, h: 70, label: 'Luxury', c: '#84CC16' },
          { x: 200, h: 50, label: 'VIP', c: '#8B5CF6' },
        ].map((bar, i) => (
          <g key={i}>
            <rect x={bar.x} y={195 - bar.h} width="30" height={bar.h} rx="4" fill={bar.c + '20'} stroke={bar.c} strokeWidth="1">
              <animate attributeName="height" from="0" to={bar.h} dur="1s" begin={`${i * 0.15}s`} fill="freeze"/>
              <animate attributeName="y" from="195" to={195 - bar.h} dur="1s" begin={`${i * 0.15}s`} fill="freeze"/>
            </rect>
            <text x={bar.x + 15} y="210" textAnchor="middle" fontSize="8" fontWeight="600" fill={C.textSec}>{bar.label}</text>
          </g>
        ))}

        {/* Suggestion chips */}
        {['Top 10 clients', 'MoM growth', 'RevPAR'].map((chip, i) => (
          <g key={i}>
            <rect x={20 + i * 85} y="225" width="78" height="24" rx="12" fill={color + '08'} stroke={color + '20'} strokeWidth="1"/>
            <text x={59 + i * 85} y="241" textAnchor="middle" fontSize="8" fontWeight="600" fill={color}>{chip}</text>
          </g>
        ))}
      </svg>
    );
  }

  return null;
}


// ═══════════════════════════════════════════════════════════════════════════════
// MAIN LANDING PAGE
// ═══════════════════════════════════════════════════════════════════════════════
export default function LandingPage() {
  const [legalModal, setLegalModal] = useState(null); // 'tos' | 'privacy'
  const [isSigningIn, setIsSigningIn] = useState(false);

  const handleSignIn = (event) => {
    event.preventDefault();
    if (isSigningIn) return;
    setIsSigningIn(true);
    window.setTimeout(() => {
      window.location.href = '/login';
    }, 1050);
  };

  const navStyle = {
    position: 'fixed', top: 0, left: 0, right: 0, zIndex: 100,
    background: 'rgba(255,255,255,0.82)',
    backdropFilter: 'blur(18px)',
    borderBottom: `1px solid ${C.borderLight}`,
    transition: 'all 0.3s ease',
  };

  return (
    <div style={{ background: C.bg, color: C.text, fontFamily: "'Outfit', -apple-system, system-ui, sans-serif", minHeight: '100vh', overflowX: 'hidden' }}>

      {/* ─── NAVIGATION ─── */}
      <nav style={navStyle}>
        <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: 64 }}>
          <K9Logo size={34} />
        </div>
      </nav>

      {/* ─── HERO ─── */}
      <section style={{
        minHeight: 'calc(100vh - 176px)',
        paddingTop: 148, paddingBottom: 88,
        textAlign: 'center',
        background: `linear-gradient(180deg, #FFFFFF 0%, #F7FEE7 100%)`,
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
      }}>
        {/* Subtle background dots */}
        <div style={{
          position: 'absolute', inset: 0, opacity: 0.4,
          backgroundImage: 'radial-gradient(circle, #14532D 0.5px, transparent 0.5px)',
          backgroundSize: '32px 32px',
          maskImage: 'radial-gradient(ellipse at center, black 20%, transparent 70%)',
          WebkitMaskImage: 'radial-gradient(ellipse at center, black 20%, transparent 70%)',
        }} />

        <div style={{ position: 'relative', maxWidth: 800, margin: '0 auto', padding: '0 24px' }}>

          {/* ─── Hero Brand Mark + Tagline ─── */}
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 16, marginBottom: 34 }}>
            <img
              src="/k9_mark.svg"
              alt="K9 Operations"
              className="hero-mark"
              style={{
                width: 'auto',
                filter: 'drop-shadow(0 4px 24px rgba(20,83,45,0.12))',
              }}
            />
            <div className="hero-tagline" style={{
              fontWeight: 700, color: C.pri,
              letterSpacing: 0, textTransform: 'uppercase',
              opacity: 0.65, lineHeight: 1.3,
            }}>
              The operating system for pet care facilities
            </div>
          </div>

          <h1 className="hero-heading" style={{
            fontWeight: 900, lineHeight: 1.08,
            color: C.pri, margin: '0 0 36px', letterSpacing: 0,
          }}>
            Gingr data,<br />
            <span style={{ color: C.acc }}>transformed</span> into<br />
            operational intelligence
          </h1>

          <div style={{ display: 'flex', justifyContent: 'center' }}>
            <a
              href="/login"
              onClick={handleSignIn}
              className={`signin-button${isSigningIn ? ' is-signing-in' : ''}`}
              aria-label="Sign in to K9 Operations"
            >
              <span>Sign In</span>
              <span className="signin-button-glow" aria-hidden="true" />
            </a>
          </div>
        </div>
      </section>

      {/* ─── FOOTER ─── */}
      <footer style={{ padding: '34px 24px 28px', background: C.bg, borderTop: `1px solid ${C.border}` }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 28, marginBottom: 24 }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 12 }}>
                <K9Logo size={28} />
              </div>
              <div style={{ fontSize: 13, color: C.textMut, lineHeight: 1.5 }}>
                The operating system for<br />pet care facilities.
              </div>
            </div>
            <div style={{ display: 'flex', gap: 48, flexWrap: 'wrap' }}>
              <div>
                <div style={{ fontSize: 12, fontWeight: 700, color: C.textMut, letterSpacing: 0, textTransform: 'uppercase', marginBottom: 12 }}>Legal</div>
                <div style={{ marginBottom: 8 }}>
                  <button onClick={() => setLegalModal('tos')} style={{
                    background: 'none', border: 'none', cursor: 'pointer', fontSize: 14, color: C.textSec, padding: 0,
                  }}>Terms of Service</button>
                </div>
                <div style={{ marginBottom: 8 }}>
                  <button onClick={() => setLegalModal('privacy')} style={{
                    background: 'none', border: 'none', cursor: 'pointer', fontSize: 14, color: C.textSec, padding: 0,
                  }}>Privacy Policy</button>
                </div>
              </div>
              <div>
                <div style={{ fontSize: 12, fontWeight: 700, color: C.textMut, letterSpacing: 0, textTransform: 'uppercase', marginBottom: 12 }}>Contact</div>
                <div style={{ fontSize: 14, color: C.textSec }}>zack.nisbet@k9operations.com</div>
              </div>
            </div>
          </div>
          <div style={{ borderTop: `1px solid ${C.borderLight}`, paddingTop: 20, display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 8 }}>
            <div style={{ fontSize: 12, color: C.textMut }}>© 2026 K9 Operations LLC. All rights reserved.</div>
            <div style={{ fontSize: 12, color: C.textMut }}>Built in New Jersey</div>
          </div>
        </div>
      </footer>

      {isSigningIn && (
        <div className="signin-transition" role="status" aria-live="polite">
          <div className="signin-grid" />
          <div className="signin-ring ring-one" />
          <div className="signin-ring ring-two" />
          <div className="signin-ring ring-three" />
          {[...Array(18)].map((_, i) => (
            <span key={i} className="signin-streak" style={{ '--i': i }} />
          ))}
          <div className="signin-transition-mark">
            <img src="/k9_mark.svg" alt="" aria-hidden="true" />
            <span>Opening secure workspace</span>
          </div>
        </div>
      )}

      {/* ─── LEGAL MODAL ─── */}
      {legalModal && (
        <div style={{
          position: 'fixed', inset: 0, zIndex: 200, background: 'rgba(0,0,0,0.5)',
          display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24,
        }} onClick={() => setLegalModal(null)}>
          <div style={{
            background: '#fff', borderRadius: 20, maxWidth: 640, width: '100%',
            maxHeight: '80vh', overflow: 'auto', padding: 36,
          }} onClick={e => e.stopPropagation()}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
              <h2 style={{ fontSize: 22, fontWeight: 800, color: C.text, margin: 0 }}>
                {legalModal === 'tos' ? 'Terms of Service' : 'Privacy Policy'}
              </h2>
              <button onClick={() => setLegalModal(null)} style={{
                background: C.surfaceAlt, border: 'none', cursor: 'pointer', width: 32, height: 32, borderRadius: 8,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
              }}>
                <Icon name="close" size={16} color={C.text} />
              </button>
            </div>
            <div style={{ fontSize: 12, color: C.textMut, marginBottom: 24 }}>
              Effective: January 1, 2026 · K9 Operations LLC · Burlington County, NJ
            </div>
            {(legalModal === 'tos' ? TOS_SECTIONS : PRIVACY_SECTIONS).map((s, i) => (
              <div key={i} style={{ marginBottom: 20 }}>
                <div style={{ fontSize: 14, fontWeight: 700, color: C.text, marginBottom: 6 }}>{s.t}</div>
                <div style={{ fontSize: 13, color: C.textSec, lineHeight: 1.7 }}>{s.b}</div>
              </div>
            ))}
          </div>
        </div>
      )}


      {/* ─── GLOBAL STYLES ─── */}
      <style>{`
        .signin-button {
          position: relative;
          display: inline-flex;
          align-items: center;
          justify-content: center;
          min-width: 172px;
          height: 54px;
          padding: 0 34px;
          border-radius: 14px;
          overflow: hidden;
          background: #14532D;
          color: #fff;
          font-size: 15px;
          font-weight: 800;
          text-decoration: none;
          box-shadow: 0 14px 32px rgba(20,83,45,0.26);
          transition: transform 0.22s ease, box-shadow 0.22s ease, background 0.22s ease;
        }
        .signin-button:hover {
          transform: translateY(-2px);
          background: #166534;
          box-shadow: 0 18px 42px rgba(20,83,45,0.32);
        }
        .signin-button span:first-child {
          position: relative;
          z-index: 2;
        }
        .signin-button-glow {
          position: absolute;
          inset: -60%;
          background:
            radial-gradient(circle at 20% 30%, rgba(217,249,157,0.9), transparent 20%),
            radial-gradient(circle at 78% 65%, rgba(132,204,22,0.55), transparent 24%),
            linear-gradient(115deg, transparent 30%, rgba(255,255,255,0.38) 48%, transparent 66%);
          opacity: 0.48;
          transform: translateX(-36%);
          animation: signinButtonSweep 4s linear infinite;
        }
        .signin-button.is-signing-in {
          transform: scale(0.98);
          box-shadow: 0 0 0 10px rgba(132,204,22,0.14), 0 18px 42px rgba(20,83,45,0.34);
        }
        .signin-transition {
          position: fixed;
          inset: 0;
          z-index: 500;
          display: flex;
          align-items: center;
          justify-content: center;
          overflow: hidden;
          background:
            radial-gradient(circle at center, rgba(217,249,157,0.28), transparent 30%),
            linear-gradient(135deg, #052E16 0%, #14532D 55%, #0B1F12 100%);
          animation: signinFadeIn 0.18s ease-out both;
        }
        .signin-grid {
          position: absolute;
          inset: -20%;
          background-image:
            linear-gradient(rgba(217,249,157,0.08) 1px, transparent 1px),
            linear-gradient(90deg, rgba(217,249,157,0.08) 1px, transparent 1px);
          background-size: 46px 46px;
          transform: perspective(520px) rotateX(60deg) translateY(18%);
          animation: signinGridMove 1.05s linear infinite;
        }
        .signin-ring {
          position: absolute;
          width: 180px;
          height: 180px;
          border-radius: 50%;
          border: 1px solid rgba(217,249,157,0.48);
          box-shadow: 0 0 40px rgba(132,204,22,0.22), inset 0 0 30px rgba(217,249,157,0.12);
          animation: signinRing 1.05s cubic-bezier(.17,.84,.44,1) both;
        }
        .ring-two {
          animation-delay: 0.12s;
        }
        .ring-three {
          animation-delay: 0.24s;
        }
        .signin-streak {
          position: absolute;
          left: 50%;
          top: 50%;
          width: 2px;
          height: 42vh;
          transform-origin: 50% 0;
          transform: rotate(calc(var(--i) * 20deg)) translateY(-50vh);
          background: linear-gradient(180deg, transparent, rgba(217,249,157,0.84), transparent);
          animation: signinStreak 0.72s ease-out both;
          animation-delay: calc(var(--i) * 0.015s);
        }
        .signin-transition-mark {
          position: relative;
          z-index: 2;
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 18px;
          color: #F7FEE7;
          font-size: 13px;
          font-weight: 800;
          letter-spacing: 0;
          text-transform: uppercase;
          animation: signinMark 0.86s ease-out both;
        }
        .signin-transition-mark img {
          height: 104px;
          width: auto;
          filter: drop-shadow(0 0 28px rgba(217,249,157,0.48));
        }
        @keyframes signinButtonSweep {
          0% { transform: translateX(-42%) rotate(0deg); }
          100% { transform: translateX(42%) rotate(360deg); }
        }
        @keyframes signinFadeIn {
          from { opacity: 0; }
          to { opacity: 1; }
        }
        @keyframes signinGridMove {
          from { background-position: 0 0; }
          to { background-position: 46px 46px; }
        }
        @keyframes signinRing {
          from { opacity: 0.9; transform: scale(0.15); }
          to { opacity: 0; transform: scale(4.8); }
        }
        @keyframes signinStreak {
          from { opacity: 0; transform: rotate(calc(var(--i) * 20deg)) translateY(-54vh) scaleY(0.4); }
          35% { opacity: 1; }
          to { opacity: 0; transform: rotate(calc(var(--i) * 20deg)) translateY(8vh) scaleY(1); }
        }
        @keyframes signinMark {
          from { opacity: 0; transform: scale(0.92); }
          to { opacity: 1; transform: scale(1); }
        }
        .hero-mark {
          height: 140px;
        }
        .hero-tagline {
          font-size: 18px;
        }
        .hero-heading {
          font-size: 64px;
        }
        @media (max-width: 768px) {
          .hero-mark {
            height: 96px;
          }
          .hero-tagline {
            font-size: 14px;
          }
          .hero-heading {
            font-size: 42px;
          }
          .signin-transition-mark span {
            font-size: 11px;
            letter-spacing: 0;
          }
        }
        @media (max-width: 420px) {
          .hero-heading {
            font-size: 36px;
          }
        }
        @media (prefers-reduced-motion: reduce) {
          .signin-button,
          .signin-button-glow,
          .signin-grid,
          .signin-ring,
          .signin-streak,
          .signin-transition-mark {
            animation: none !important;
            transition: none !important;
          }
        }
      `}</style>
    </div>
  );
}
