// © 2026 K9 Operations LLC. All Rights Reserved.
// Proprietary and Confidential.

import { useState } from 'react';
import { useAuth } from './AuthProvider';

// ─── Light Theme Colors ──────────────────────────────────────────────────────
const C = {
  bg: '#FFFFFF',
  bgAlt: '#FAFBFC',
  surface: '#FFFFFF',
  surfaceHover: '#F8FAFC',
  border: '#E2E8F0',
  borderLight: '#F1F5F9',
  text: '#0F172A',
  textSec: '#1E293B',
  textMut: '#475569',
  pri: '#14532D',
  priL: '#166534',
  acc: '#84CC16',
  accLt: '#D9F99D',
  danger: '#EF4444',
};

// ─── Legal Content ────────────────────────────────────────────────────────────
const TOS_SECTIONS = [
  { t: "1. Definitions", b: "\"Company\" refers to K9 Operations LLC, a New Jersey limited liability company. \"Service\" refers to the K9 Operations cloud-based software platform. \"Customer\" refers to the pet care facility or business entity that subscribes. \"User\" refers to any individual who accesses the Service. \"Customer Data\" refers to all data uploaded or generated by Users through the Service." },
  { t: "2. Description of Service", b: "K9 Operations provides a cloud-based SaaS platform for pet care facility management, including pet profile management, booking and scheduling, feeding and medication tracking, report cards, employee scheduling, and invoicing." },
  { t: "3. Account Registration and Security", b: "Customers must create an account and designate at least one administrator. You are responsible for providing accurate registration information, managing user accounts and access levels, maintaining the confidentiality of login credentials, and all activities that occur under your account." },
  { t: "4. Permitted Use and Restrictions", b: "You receive a limited, non-exclusive, non-transferable right to use the Service for your pet care facility operations. You may not copy, modify, distribute, sell, reverse engineer, scrape, or attempt unauthorized access to the Service." },
  { t: "5. Intellectual Property", b: "The Service is the exclusive property of K9 Operations LLC, protected by U.S. copyright and trademark laws. Copyright Registration filed February 9, 2026. All rights not expressly granted are reserved." },
  { t: "6. Customer Data", b: "You retain ownership of your Customer Data. You grant K9 Operations a limited license to host, store, and process your data solely to provide the Service. We will not access or disclose your data except as necessary to provide the Service or as required by law." },
  { t: "7. Service Availability", b: "We target 99.9% monthly uptime, excluding scheduled maintenance. Scheduled maintenance will be communicated at least 48 hours in advance when practicable." },
  { t: "8. Fees and Payment", b: "Access requires a paid subscription. Pricing and terms are established in your SaaS License Agreement. We may modify pricing with at least 60 days written notice." },
  { t: "9. Term and Termination", b: "Upon termination, you have 30 days to request a data export (CSV or JSON). After 30 days, Customer Data may be deleted. Outstanding fees remain due." },
  { t: "10. Disclaimers and Limitation of Liability", b: "THE SERVICE IS PROVIDED \"AS IS\" WITHOUT WARRANTIES. We make no representations regarding pet health outcomes. Our total aggregate liability shall not exceed fees paid in the preceding 12 months." },
  { t: "11. Indemnification", b: "You agree to indemnify K9 Operations LLC against claims arising from your use of the Service, violation of these Terms, or your operation of a pet care facility." },
  { t: "12. Governing Law", b: "These Terms are governed by New Jersey law. Disputes shall be resolved in Burlington County, NJ courts." },
  { t: "13. Changes to Terms", b: "We will provide at least 30 days notice for material changes. Continued use constitutes acceptance of modified Terms." },
  { t: "14. Contact", b: "Questions? Contact us at zack.nisbet@k9operations.com" },
];

const PRIVACY_SECTIONS = [
  { t: "1. Information We Collect", b: "We collect account information (business name, contact details, employee info), pet and client data (pet profiles, vaccination records, medical notes, emergency contacts), booking and service data (reservations, feeding logs, report cards, invoices), employee data (names, roles, schedules), usage data (IP address, browser type, pages viewed), and session cookies for authentication." },
  { t: "2. How We Use Your Information", b: "We use your information to provide and operate the Service, communicate with you, improve the platform, ensure security, and comply with legal obligations. We do not use Customer Data to train machine learning models." },
  { t: "3. How We Share Your Information", b: "We do not sell, rent, or trade your personal information. We share data only with service providers (Supabase for database hosting, Vercel for application hosting, payment processors), when required by law, or in connection with a business transfer." },
  { t: "4. Data Security", b: "All data is encrypted at rest (AES-256) and in transit (TLS 1.2+). We use role-based access controls and hashed passwords. We do not store credit card numbers or sensitive payment credentials." },
  { t: "5. Data Retention", b: "We retain data while your account is active. After termination, you have 30 days to export your data. Customer Data is deleted within 90 days of the export period, unless retention is required by law." },
  { t: "6. Your Rights", b: "You may request access to, correction of, or deletion of your personal information. You may request data export in CSV or JSON format. You may opt out of marketing communications at any time. Contact zack.nisbet@k9operations.com to exercise these rights." },
  { t: "7. Children's Privacy", b: "The Service is not directed to children under 13. We do not knowingly collect personal information from children under 13." },
  { t: "8. Third-Party Services", b: "This Privacy Policy does not apply to third-party services accessed through the platform. We encourage you to review their privacy policies." },
  { t: "9. State-Specific Disclosures", b: "California residents may have additional rights under CCPA/CPRA, including the right to know, delete, and opt out of data sales (we do not sell data). New Jersey residents have the right to access and correct their information and receive breach notifications." },
  { t: "10. Changes to This Policy", b: "We provide at least 30 days notice for material changes. Continued use constitutes acceptance." },
  { t: "11. Contact", b: "Questions about privacy? Email zack.nisbet@k9operations.com with \"Privacy\" in the subject line." },
];

// ─── Legal Modal ──────────────────────────────────────────────────────────────
function LegalModal({ type, onClose }) {
  const isTos = type === 'tos';
  const title = isTos ? 'Terms of Service' : 'Privacy Policy';
  const intro = isTos
    ? 'Welcome to K9 Operations. These Terms of Service govern your access to and use of the K9 Operations platform, including any related applications, features, and services. By accessing or using the Service, you agree to be bound by these Terms.'
    : 'K9 Operations LLC is committed to protecting the privacy and security of information collected through the K9 Operations platform. This Privacy Policy describes what information we collect, how we use it, how we share it, and your choices.';
  const sections = isTos ? TOS_SECTIONS : PRIVACY_SECTIONS;

  return (
    <div onClick={onClose} style={{
      position: 'fixed', inset: 0, zIndex: 9999,
      background: 'rgba(0,0,0,0.3)', backdropFilter: 'blur(8px)',
      display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20,
    }}>
      <div onClick={e => e.stopPropagation()} style={{
        width: '100%', maxWidth: 640, maxHeight: '80vh',
        background: '#fff', border: `1px solid ${C.border}`, borderRadius: 16,
        overflow: 'hidden', display: 'flex', flexDirection: 'column',
        boxShadow: '0 24px 80px rgba(0,0,0,0.15)',
      }}>
        <div style={{
          padding: '20px 28px', borderBottom: `1px solid ${C.border}`,
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          flexShrink: 0, background: C.bgAlt,
        }}>
          <div>
            <div style={{ fontSize: 18, fontWeight: 800, color: C.pri }}>{title}</div>
            <div style={{ fontSize: 11, color: C.textMut, marginTop: 2 }}>Effective February 10, 2026</div>
          </div>
          <button onClick={onClose} style={{
            width: 32, height: 32, borderRadius: 8, border: `1.5px solid ${C.border}`, background: '#fff',
            cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center',
            color: C.textSec, fontSize: 18, fontFamily: 'inherit', lineHeight: 1,
          }}>&times;</button>
        </div>
        <div style={{ flex: 1, overflow: 'auto', padding: '24px 28px' }}>
          <p style={{ fontSize: 13, color: C.textSec, lineHeight: 1.7, marginTop: 0, marginBottom: 20 }}>{intro}</p>
          {sections.map((s, i) => (
            <div key={i} style={{ marginBottom: 16 }}>
              <div style={{ fontSize: 13, fontWeight: 700, color: C.text, marginBottom: 4 }}>{s.t}</div>
              <div style={{ fontSize: 13, color: C.textSec, lineHeight: 1.7 }}>{s.b}</div>
            </div>
          ))}
          <div style={{
            textAlign: 'center', fontSize: 11, color: C.textMut, marginTop: 24,
            paddingTop: 16, borderTop: `1px solid ${C.border}`,
          }}>&copy; 2026 K9 Operations LLC. All Rights Reserved.</div>
        </div>
      </div>
    </div>
  );
}

// ─── Login Component ──────────────────────────────────────────────────────────
export default function Login() {
  const { signIn, resetPassword } = useAuth();
  const [mode, setMode] = useState('login');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [resetSent, setResetSent] = useState(false);
  const [legalModal, setLegalModal] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    if (mode === 'forgot') {
      if (!email.trim()) { setError('Enter your email address'); setLoading(false); return; }
      const { error, timedOut, unavailable } = await resetPassword(email);
      if (error) {
        if (timedOut || unavailable) setError('Password reset is temporarily unavailable. Please try again in a moment.');
        else setError(error.message);
      }
      else setResetSent(true);
      setLoading(false);
      return;
    }
    const { error, timedOut, unavailable } = await signIn(email, password);
    if (error) {
      if (timedOut || unavailable) setError('Authentication service is temporarily unavailable. Please try again in a moment.');
      else setError(error.message);
    }
    setLoading(false);
  };

  const inputStyle = {
    width: '100%', padding: '12px 14px',
    border: `1.5px solid ${C.border}`,
    borderRadius: 10, fontSize: 15, color: C.text,
    background: C.bgAlt,
    outline: 'none', fontFamily: 'inherit',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s, box-shadow 0.2s',
  };

  const linkBtnStyle = {
    background: 'none', border: 'none', color: C.textMut,
    fontSize: 10, cursor: 'pointer', fontFamily: 'inherit',
    textDecoration: 'underline', padding: 0,
  };

  return (
    <>
      <style>{`
        * { box-sizing: border-box; }
        body { margin: 0; }
        input::placeholder { color: ${C.textMut}; }
        input:focus {
          border-color: ${C.pri} !important;
          box-shadow: 0 0 0 3px rgba(20,83,45,0.1) !important;
        }
      `}</style>

      <div style={{
        minHeight: '100vh', background: C.bg,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        fontFamily: "'Outfit', system-ui, -apple-system, sans-serif",
        padding: 20, position: 'relative', overflow: 'hidden',
      }}>
        {/* Subtle radial glow */}
        <div style={{
          position: 'absolute', top: '30%', left: '50%', transform: 'translate(-50%, -50%)',
          width: 600, height: 600, borderRadius: '50%',
          background: 'radial-gradient(circle, rgba(20,83,45,0.04) 0%, transparent 70%)',
          pointerEvents: 'none',
        }} />

        {/* Back to Home */}
        <a href="/" style={{
          position: 'fixed', top: 20, left: 20,
          display: 'inline-flex', alignItems: 'center', gap: 6,
          fontSize: 13, color: C.textSec, textDecoration: 'none',
          padding: '6px 12px', borderRadius: 8,
          border: `1px solid ${C.border}`, background: 'rgba(255,255,255,0.9)',
          backdropFilter: 'blur(8px)', zIndex: 10,
        }}>
          <span style={{ fontSize: 11 }}>&larr;</span>
          <span>Back to Home</span>
        </a>

        {/* Login Card */}
        <div style={{
          width: '100%', maxWidth: 420, background: '#fff', borderRadius: 20,
          padding: '40px 36px', border: `1px solid ${C.border}`,
          boxShadow: '0 20px 60px rgba(0,0,0,0.06), 0 1px 3px rgba(0,0,0,0.04)',
          position: 'relative', zIndex: 1,
        }}>
          {/* Logo — K9 Operations Pit Bull Mark */}
          <div style={{ textAlign: 'center', marginBottom: 32 }}>
            <div style={{ margin: '0 auto 14px', display: 'flex', justifyContent: 'center' }}>
              <img src="/k9-logo-full.svg" alt="K9 Operations" style={{ height: 56 }} />
            </div>
            <div style={{ fontSize: 28, fontWeight: 800, color: C.pri, letterSpacing: '-0.02em' }}>
              K9 Operations
            </div>
            <div style={{
              fontSize: 11, color: C.acc, fontWeight: 700,
              letterSpacing: '0.1em', textTransform: 'uppercase', marginTop: 5,
            }}>
              The Operating System for Pet Care
            </div>
          </div>

          {/* Reset Sent State */}
          {resetSent ? (
            <div style={{ textAlign: 'center', padding: '20px 0' }}>
              <div style={{ fontSize: 48, marginBottom: 16 }}>&#9993;</div>
              <h3 style={{ margin: '0 0 8px', fontSize: 18, fontWeight: 700, color: C.text }}>Reset link sent</h3>
              <p style={{ fontSize: 14, color: C.textSec, lineHeight: 1.6, margin: 0 }}>
                We sent a password reset link to <strong style={{ color: C.text }}>{email}</strong>.
                Click it to set a new password, then come back here to sign in.
              </p>
              <button
                onClick={() => { setMode('login'); setResetSent(false); setError(''); }}
                style={{
                  marginTop: 20, padding: '10px 24px', background: C.pri, color: '#fff',
                  border: 'none', borderRadius: 8, fontSize: 14, fontWeight: 700,
                  cursor: 'pointer', fontFamily: 'inherit',
                }}
              >Back to Sign In</button>
            </div>
          ) : (
            <>
              {mode === 'forgot' && (
                <div style={{ marginBottom: 20 }}>
                  <h3 style={{ margin: '0 0 6px', fontSize: 18, fontWeight: 700, color: C.text }}>Reset your password</h3>
                  <p style={{ margin: 0, fontSize: 13, color: C.textSec, lineHeight: 1.5 }}>
                    Enter your email and we'll send you a link to set a new password.
                  </p>
                </div>
              )}

              <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
                <div>
                  <label style={{ display: 'block', fontSize: 13, fontWeight: 600, color: C.textSec, marginBottom: 6 }}>Email</label>
                  <input type="email" value={email} onChange={e => setEmail(e.target.value)}
                    style={inputStyle} autoComplete="email" required />
                </div>
                {mode !== 'forgot' && (
                  <div>
                    <label style={{ display: 'block', fontSize: 13, fontWeight: 600, color: C.textSec, marginBottom: 6 }}>Password</label>
                    <input type="password" value={password} onChange={e => setPassword(e.target.value)}
                      placeholder="Enter your password" style={inputStyle} autoComplete="current-password" required />
                  </div>
                )}
                {error && (
                  <div style={{
                    padding: '10px 14px', borderRadius: 8,
                    background: 'rgba(239,68,68,0.06)', border: '1px solid rgba(239,68,68,0.15)',
                    color: C.danger, fontSize: 13, fontWeight: 500,
                  }}>{error}</div>
                )}
                <button type="submit" disabled={loading} style={{
                  width: '100%', padding: '13px', background: loading ? C.textMut : C.pri,
                  color: '#fff', border: 'none', borderRadius: 10, fontSize: 15, fontWeight: 700,
                  cursor: loading ? 'default' : 'pointer', fontFamily: 'inherit', marginTop: 4,
                  transition: 'background 0.2s', letterSpacing: '0.02em',
                  boxShadow: loading ? 'none' : '0 4px 14px rgba(20,83,45,0.2)',
                }}>
                  {loading ? 'Please wait...' : mode === 'forgot' ? 'Send Reset Link' : 'Sign In'}
                </button>
              </form>

              {mode === 'login' && (
                <div style={{ textAlign: 'center', marginTop: 16 }}>
                  <button onClick={() => { setMode('forgot'); setError(''); }}
                    style={{ background: 'none', border: 'none', color: C.textMut, fontSize: 13, cursor: 'pointer', fontFamily: 'inherit', textDecoration: 'underline', padding: 0 }}>
                    Forgot your password?
                  </button>
                  <div style={{ marginTop: 12 }}>
                    <span style={{ fontSize: 13, color: C.textMut }}>Don't have an account? </span>
                    <a href="/signup" style={{ fontSize: 13, color: C.pri, fontWeight: 600, textDecoration: 'none' }}>Sign Up</a>
                  </div>
                </div>
              )}

              {mode === 'forgot' && (
                <div style={{ textAlign: 'center', marginTop: 16 }}>
                  <button onClick={() => { setMode('login'); setError(''); }}
                    style={{ background: 'none', border: 'none', color: C.textMut, fontSize: 13, cursor: 'pointer', fontFamily: 'inherit', textDecoration: 'underline', padding: 0 }}>
                    Back to Sign In
                  </button>
                </div>
              )}
            </>
          )}

          {/* Footer */}
          <div style={{ textAlign: 'center', marginTop: 24, fontSize: 11, color: C.textMut }}>
            <span style={{ fontSize: 10, opacity: 0.7 }}>&copy; 2026 K9 Operations LLC. All Rights Reserved.</span>
            <div style={{ marginTop: 6, display: 'flex', justifyContent: 'center', gap: 12 }}>
              <button onClick={() => setLegalModal('tos')} style={linkBtnStyle}>Terms of Service</button>
              <span style={{ color: C.border, fontSize: 10 }}>|</span>
              <button onClick={() => setLegalModal('privacy')} style={linkBtnStyle}>Privacy Policy</button>
            </div>
          </div>
        </div>
      </div>

      {legalModal && <LegalModal type={legalModal} onClose={() => setLegalModal(null)} />}
    </>
  );
}
