-- Align compliance evidence uploads with the Compliance permission model.
--
-- The original labor attachment policies predate dynamic Compliance and only
-- trusted the broad labor management helper. They also required too many
-- folder segments for the `employee/requirements/requirement/file.pdf` paths
-- generated by the app.

DROP POLICY IF EXISTS labor_employee_attachments_requirement_evidence_select ON storage.objects;
CREATE POLICY labor_employee_attachments_requirement_evidence_select
  ON storage.objects
  FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'labor-employee-attachments'
    AND array_length(storage.foldername(name), 1) >= 3
    AND (storage.foldername(name))[1] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    AND (storage.foldername(name))[2] = 'requirements'
    AND EXISTS (
      SELECT 1
      FROM public.labor_employees e
      WHERE e.id = ((storage.foldername(name))[1])::uuid
        AND (
          public.labor_has_management_access(e.location_id)
          OR (
            (storage.foldername(name))[3] LIKE 'performance-review-%'
            AND public.labor_has_lite_permission(e.location_id, 'Labor Compliance View PDFs')
          )
        )
    )
  );

DROP POLICY IF EXISTS labor_employee_attachments_requirement_evidence_insert ON storage.objects;
CREATE POLICY labor_employee_attachments_requirement_evidence_insert
  ON storage.objects
  FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'labor-employee-attachments'
    AND array_length(storage.foldername(name), 1) >= 3
    AND (storage.foldername(name))[1] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    AND (storage.foldername(name))[2] = 'requirements'
    AND EXISTS (
      SELECT 1
      FROM public.labor_employees e
      WHERE e.id = ((storage.foldername(name))[1])::uuid
        AND (
          public.labor_has_management_access(e.location_id)
          OR (
            (storage.foldername(name))[3] LIKE 'performance-review-%'
            AND public.labor_compliance_can_update_evidence(e.location_id)
          )
        )
    )
  );

DROP POLICY IF EXISTS labor_employee_attachments_requirement_evidence_delete ON storage.objects;
CREATE POLICY labor_employee_attachments_requirement_evidence_delete
  ON storage.objects
  FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'labor-employee-attachments'
    AND array_length(storage.foldername(name), 1) >= 3
    AND (storage.foldername(name))[1] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    AND (storage.foldername(name))[2] = 'requirements'
    AND EXISTS (
      SELECT 1
      FROM public.labor_employees e
      WHERE e.id = ((storage.foldername(name))[1])::uuid
        AND (
          public.labor_has_management_access(e.location_id)
          OR (
            (storage.foldername(name))[3] LIKE 'performance-review-%'
            AND public.labor_compliance_can_update_evidence(e.location_id)
          )
        )
    )
  );

DROP POLICY IF EXISTS labor_employee_documents_compliance_evidence_read ON public.labor_employee_documents;
CREATE POLICY labor_employee_documents_compliance_evidence_read ON public.labor_employee_documents
  FOR SELECT TO authenticated
  USING (
    document_type = 'performance_review_evidence'
    AND storage_bucket = 'labor-employee-attachments'
    AND storage_path LIKE (labor_employee_id::text || '/requirements/performance-review-%')
    AND COALESCE(metadata->>'source_module', '') IN ('performance_reviews', 'compliance_requirements')
    AND EXISTS (
      SELECT 1
      FROM public.labor_employees e
      WHERE e.id = labor_employee_id
        AND (
          public.labor_compliance_can_update_evidence(e.location_id)
          OR public.labor_has_lite_permission(e.location_id, 'Labor Compliance View PDFs')
        )
    )
  );

DROP POLICY IF EXISTS labor_employee_documents_compliance_evidence_insert ON public.labor_employee_documents;
CREATE POLICY labor_employee_documents_compliance_evidence_insert ON public.labor_employee_documents
  FOR INSERT TO authenticated
  WITH CHECK (
    document_type = 'performance_review_evidence'
    AND storage_bucket = 'labor-employee-attachments'
    AND storage_path LIKE (labor_employee_id::text || '/requirements/performance-review-%')
    AND COALESCE(metadata->>'source_module', '') IN ('performance_reviews', 'compliance_requirements')
    AND EXISTS (
      SELECT 1
      FROM public.labor_employees e
      WHERE e.id = labor_employee_id
        AND public.labor_compliance_can_update_evidence(e.location_id)
    )
  );

DROP POLICY IF EXISTS labor_employee_documents_compliance_evidence_delete ON public.labor_employee_documents;
CREATE POLICY labor_employee_documents_compliance_evidence_delete ON public.labor_employee_documents
  FOR DELETE TO authenticated
  USING (
    document_type = 'performance_review_evidence'
    AND storage_bucket = 'labor-employee-attachments'
    AND storage_path LIKE (labor_employee_id::text || '/requirements/performance-review-%')
    AND COALESCE(metadata->>'source_module', '') IN ('performance_reviews', 'compliance_requirements')
    AND EXISTS (
      SELECT 1
      FROM public.labor_employees e
      WHERE e.id = labor_employee_id
        AND public.labor_compliance_can_update_evidence(e.location_id)
    )
  );
